#!/usr/bin/env python3
# Generated By: Claude Code (claude-opus-5[1m])
"""PreToolUse guards shared by the Claude Code and Codex harnesses.

This package is the whole installable surface of the my-claude-stuff
distribution, and the one definition of the guards. my-codex-stuff installs
the distribution rather than copying the files, so there is no second copy to
drift and a Codex-only machine needs no ~/.claude on disk.

Both hooks invoke it as a module -- ``python3 -m harness_guards.block_commands``
-- so neither harness needs to know where pip put it. Stdlib only, and each
module stands alone: a shared helper would be one more thing an installed
dependency has to resolve, and the duplicated part is ten lines.

Both harnesses block the same way -- exit 2 with a reason on stderr. Verified
for Codex 0.154.0 from the string ``PreToolUse hook exited with code 2 but did
not write a blocking reason to stderr`` in its binary, and from the embedded
``pre-tool-use.command.input`` schema, whose field names (``tool_name``,
``tool_input``, ``cwd``) match Claude Code's.
"""
