#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""PreToolUse hook that blocks access to sensitive directories and files.

Reads JSON from stdin with tool_name, tool_input, and cwd. Extracts paths
from shell commands (with ~/, $HOME expansion and cwd-relative resolution)
and from structured tool inputs (Read, Edit, Write, Glob, Grep, NotebookEdit).
Checks resolved absolute paths against blocked patterns.
Exits 2 to block, 0 to allow -- both Claude Code and Codex read that.

Blocked directories: ~/.ssh, ~/.aws, ~/.kube, ~/.ocm, ~/.config/gws
Blocked files: ~/.claude/*credentials*, *.kdbx, .env
Blocked URIs: file:// in WebFetch (use Read tool instead)

The file patterns mirror the Read/Grep entries in claude/settings.json.d/
deny.json, which Codex has no equivalent of -- its config.toml carries no
deny list. Enforcing them here covers both harnesses, and on the Claude side
widens them from Read/Grep-only to every tool this hook sees.
"""

import json
import os
import re
import shlex
import sys
from pathlib import Path

_HOME = re.escape(Path.home().as_posix())

BLOCKED_PATH_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(rf"^{_HOME}/\.ssh(/|$)"), "~/.ssh"),
    (re.compile(rf"^{_HOME}/\.aws(/|$)"), "~/.aws"),
    (re.compile(rf"^{_HOME}/\.kube(/|$)"), "~/.kube"),
    (re.compile(rf"^{_HOME}/\.ocm(/|$)"), "~/.ocm"),
    (re.compile(rf"^{_HOME}/\.claude/.*credentials"), "credentials file"),
    (re.compile(rf"^{_HOME}/\.config/gws(/|$)"), "~/.config/gws"),
    # Not home-anchored: deny.json matches these anywhere (`**/*.kdbx`,
    # `**/.env`), and a checked-out .env is as sensitive as one in $HOME.
    (re.compile(r"\.kdbx$"), "KeePass database"),
    (re.compile(r"/\.env$"), ".env file"),
]

# Tools with known path fields
_TOOL_PATH_FIELDS: dict[str, list[str]] = {
    "Read": ["file_path"],
    "Edit": ["file_path"],
    "Write": ["file_path"],
    "Glob": ["pattern", "path"],
    "Grep": ["path"],
    "NotebookEdit": ["notebook_path"],
}


def resolve_path(candidate: str, cwd: str) -> str:
    """Resolve a path candidate to an absolute path.

    Expands ~ and $HOME via stdlib, resolves relative paths against cwd.
    """
    p = Path(os.path.expandvars(candidate)).expanduser()
    if not p.is_absolute():
        p = Path(cwd) / p
    return p.resolve().as_posix()


def check_path(resolved: str) -> str | None:
    """Return description if resolved path matches a blocked pattern, else None."""
    for pattern, description in BLOCKED_PATH_PATTERNS:
        if pattern.search(resolved):
            return description
    return None


def extract_paths_structured(tool_name: str, tool_input: dict, cwd: str) -> list[str]:
    """Extract and resolve paths from structured tool inputs."""
    fields = _TOOL_PATH_FIELDS.get(tool_name)
    if not fields:
        return []
    resolved: list[str] = []
    for field in fields:
        value = tool_input.get(field)
        if value and isinstance(value, str):
            resolved.append(resolve_path(value, cwd))
    return resolved


def _has_command_chaining(command: str) -> bool:
    """Detect semicolon-based command chaining outside of quoted strings."""
    in_single = False
    in_double = False
    i = 0
    while i < len(command):
        ch = command[i]
        if ch == "\\" and in_double and i + 1 < len(command):
            i += 2
            continue
        if ch == "'" and not in_double:
            in_single = not in_single
        elif ch == '"' and not in_single:
            in_double = not in_double
        elif ch == ";" and not in_single and not in_double:
            return True
        i += 1
    return False


def extract_paths_bash(command: str, cwd: str) -> list[str]:
    """Extract path-like tokens from a Bash command.

    Blocks semicolon-chained commands (prevents variable-based path
    obfuscation). Tokenizes, skips flags, and resolves each token via
    resolve_path (which handles ~, $HOME, and relative paths against cwd).
    """
    # Tokenize — shlex handles quotes, falls back to split on error
    try:
        tokens = shlex.split(command)
    except ValueError:
        tokens = command.split()

    resolved: list[str] = []
    for token in tokens:
        if not token.startswith("-"):
            resolved.append(resolve_path(token, cwd))
    return resolved


# Codex's `tool_input` schema is `true` -- any JSON -- and its exec tool is not
# called `Bash`, so the command is found by key rather than by tool name.
# `command` and `cmd` only: an `input` or `script` key would also match an
# apply_patch body, and a README that contains the word sudo is not a command.
#
# ponytail: the real Codex key is unconfirmed. Codex cannot run in the personal
# sandbox this was written in (no OpenAI host is in the network policy), so no
# live payload was available. Confirm against one and drop whichever guess is
# wrong.
_COMMAND_KEYS = ("command", "cmd")


def extract_command(tool_input: object) -> str:
    """Return the shell command in a tool input, or an empty string."""
    if not isinstance(tool_input, dict):
        return ""
    for key in _COMMAND_KEYS:
        value = tool_input.get(key)
        if isinstance(value, str):
            return value
        # An argv list, e.g. ["bash", "-lc", "cd x && git push"]. Joined on
        # spaces, not with shlex.join: that quotes the script into a single
        # token, and the chain splitters below respect quotes, so the chained
        # command inside would never be seen.
        if isinstance(value, list) and all(isinstance(item, str) for item in value):
            return " ".join(value)
    return ""


def extract_paths(tool_name: str, tool_input: dict, cwd: str) -> list[str]:
    """Extract all path candidates from a tool invocation."""
    # Any tool carrying a command is treated as a shell tool. Claude Code calls
    # it Bash; Codex does not, and renames its exec tool between releases, so
    # keying on the command is what makes one hook serve both.
    command = extract_command(tool_input)
    if command:
        return extract_paths_bash(command, cwd)
    # ponytail: the structured map is still Claude's tool names. Codex's
    # equivalents (apply_patch and whatever its read tool is called) fall
    # through to no paths -- see _TOOL_PATH_FIELDS above.
    return extract_paths_structured(tool_name, tool_input, cwd)


def main() -> None:
    """Read tool input from stdin and block access to sensitive paths."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})
    if not isinstance(tool_input, dict):
        return
    cwd = data.get("cwd", ".")

    command = extract_command(tool_input)
    if command and _has_command_chaining(command):
        print(
            "BLOCKED: semicolon command chaining is not allowed",
            file=sys.stderr,
        )
        sys.exit(2)

    if tool_name == "WebFetch":
        url = tool_input.get("url", "")
        if url.startswith("file://"):
            print(
                "BLOCKED: file:// URI is not allowed (use the Read tool)",
                file=sys.stderr,
            )
            sys.exit(2)

    paths = extract_paths(tool_name, tool_input, cwd)
    for path in paths:
        blocked = check_path(path)
        if blocked:
            print(f"BLOCKED: access to {blocked} is not allowed", file=sys.stderr)
            sys.exit(2)


if __name__ == "__main__":
    main()
