#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Conftest to prevent tests from modifying real config files."""

import pathlib

import pytest

BLOCKED_PATHS = [
    pathlib.Path.home() / ".claude",
    pathlib.Path.home() / ".config" / "claude",
]


def _is_blocked(path: pathlib.Path) -> bool:
    resolved = str(path.resolve())
    return any(resolved.startswith(str(b)) for b in BLOCKED_PATHS)


def _guard_read_text(original):
    def guarded(self, *args, **kwargs):
        if _is_blocked(self):
            raise PermissionError(f"test attempted to read from protected path: {self}")
        return original(self, *args, **kwargs)

    return guarded


def _guard_write_text(original):
    def guarded(self, *args, **kwargs):
        if _is_blocked(self):
            raise PermissionError(f"test attempted to write to protected path: {self}")
        return original(self, *args, **kwargs)

    return guarded


def _guard_copy2(original):
    def guarded(src, dst, *args, **kwargs):
        if _is_blocked(pathlib.Path(dst)):
            raise PermissionError(f"test attempted to copy to protected path: {dst}")
        return original(src, dst, *args, **kwargs)

    return guarded


@pytest.fixture(autouse=True)
def block_real_config_writes(monkeypatch):
    """Block all writes to ~/.claude and ~/.config/claude in every test."""
    original_write_text = pathlib.Path.write_text
    original_copy2 = __import__("shutil").copy2

    original_read_text = pathlib.Path.read_text

    monkeypatch.setattr(pathlib.Path, "read_text", _guard_read_text(original_read_text))
    monkeypatch.setattr(
        pathlib.Path, "write_text", _guard_write_text(original_write_text)
    )
    monkeypatch.setattr("shutil.copy2", _guard_copy2(original_copy2))


@pytest.fixture
def src_dest_dirs(tmp_path):
    """Create and return (src_dir, dest_dir) under tmp_path."""
    src_dir = tmp_path / "src"
    dest_dir = tmp_path / "dest"
    src_dir.mkdir()
    dest_dir.mkdir()
    return src_dir, dest_dir
