#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Conftest: prevent tests from modifying real config or sending notifications."""

import pathlib
import subprocess

import pytest

BLOCKED_PATHS = [
    pathlib.Path.home() / ".claude",
    pathlib.Path.home() / ".config" / "claude",
]


def _is_blocked(path: pathlib.Path) -> bool:
    try:
        return any(path.resolve().is_relative_to(b) for b in BLOCKED_PATHS)
    except (OSError, ValueError):
        return True


def _guard_read_text(original):
    def guarded(self, *args, **kwargs):
        if _is_blocked(self):
            raise PermissionError(f"test attempted to read from protected path: {self}")
        return original(self, *args, **kwargs)

    return guarded


def _guard_write_text(original):
    def guarded(self, *args, **kwargs):
        if _is_blocked(self):
            raise PermissionError(f"test attempted to write to protected path: {self}")
        return original(self, *args, **kwargs)

    return guarded


def _guard_copy2(original):
    def guarded(src, dst, *args, **kwargs):
        if _is_blocked(pathlib.Path(dst)):
            raise PermissionError(f"test attempted to copy to protected path: {dst}")
        return original(src, dst, *args, **kwargs)

    return guarded


def _guard_open(original):
    def guarded(file, *args, **kwargs):
        if _is_blocked(pathlib.Path(file)):
            raise PermissionError(f"test attempted to open protected path: {file}")
        return original(file, *args, **kwargs)

    return guarded


def _guard_subprocess(func_name):
    def decorator(original):
        def guarded(*args, **kwargs):
            cmd_args = args[0] if args else kwargs.get("args", [])
            if isinstance(cmd_args, str):
                cmd_desc = cmd_args
            elif isinstance(cmd_args, (list, tuple)) and cmd_args:
                cmd_desc = " ".join(str(a) for a in cmd_args)
            else:
                cmd_desc = repr(cmd_args)
            raise PermissionError(
                f"test attempted to run real command via {func_name}: {cmd_desc}"
            )

        return guarded

    return decorator


@pytest.fixture(autouse=True)
def block_real_config_writes(monkeypatch):
    """Block all I/O to ~/.claude and ~/.config/claude in every test."""
    import builtins

    original_read_text = pathlib.Path.read_text
    original_write_text = pathlib.Path.write_text
    original_copy2 = __import__("shutil").copy2
    original_open = builtins.open

    monkeypatch.setattr(pathlib.Path, "read_text", _guard_read_text(original_read_text))
    monkeypatch.setattr(
        pathlib.Path, "write_text", _guard_write_text(original_write_text)
    )
    monkeypatch.setattr("shutil.copy2", _guard_copy2(original_copy2))
    monkeypatch.setattr("builtins.open", _guard_open(original_open))
    monkeypatch.setattr(
        "subprocess.run", _guard_subprocess("subprocess.run")(subprocess.run)
    )
    monkeypatch.setattr(
        "subprocess.Popen", _guard_subprocess("subprocess.Popen")(subprocess.Popen)
    )
    monkeypatch.setattr(
        "subprocess.call", _guard_subprocess("subprocess.call")(subprocess.call)
    )
    monkeypatch.setattr(
        "subprocess.check_call",
        _guard_subprocess("subprocess.check_call")(subprocess.check_call),
    )
    monkeypatch.setattr(
        "subprocess.check_output",
        _guard_subprocess("subprocess.check_output")(subprocess.check_output),
    )


@pytest.fixture
def src_dest_dirs(tmp_path):
    """Create and return (src_dir, dest_dir) under tmp_path."""
    src_dir = tmp_path / "src"
    dest_dir = tmp_path / "dest"
    src_dir.mkdir()
    dest_dir.mkdir()
    return src_dir, dest_dir
