#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/prompt_log.py."""

import io
import json
import pathlib
import sys
from datetime import datetime
from unittest import mock

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import prompt_log  # noqa: E402


class TestValidSessionId:
    def test_valid_alphanumeric(self):
        assert prompt_log._valid_session_id("abc-123") is True

    def test_valid_uuid_like(self):
        uuid = "9a8dee8e-8e7f-4058-8df1-9d1c72e991bd"
        assert prompt_log._valid_session_id(uuid) is True

    def test_valid_underscore(self):
        assert prompt_log._valid_session_id("session_1") is True

    def test_rejects_empty(self):
        assert prompt_log._valid_session_id("") is False

    def test_rejects_path_traversal(self):
        assert prompt_log._valid_session_id("../etc/passwd") is False

    def test_rejects_slash(self):
        assert prompt_log._valid_session_id("foo/bar") is False

    def test_rejects_backslash(self):
        assert prompt_log._valid_session_id("foo\\bar") is False

    def test_rejects_space(self):
        assert prompt_log._valid_session_id("foo bar") is False

    def test_rejects_null_byte(self):
        assert prompt_log._valid_session_id("foo\x00bar") is False


class TestGitBranch:
    def test_returns_branch_name(self):
        result = mock.Mock()
        result.returncode = 0
        result.stdout = "feature-x\n"
        with mock.patch("prompt_log.subprocess.run", return_value=result) as mock_run:
            assert prompt_log._git_branch("/some/repo") == "feature-x"
            mock_run.assert_called_once()
            args = mock_run.call_args
            assert args[0][0] == ["git", "rev-parse", "--abbrev-ref", "HEAD"]
            assert args[1]["cwd"] == "/some/repo"

    def test_nonzero_exit_returns_empty(self):
        result = mock.Mock()
        result.returncode = 128
        result.stdout = ""
        with mock.patch("prompt_log.subprocess.run", return_value=result):
            assert prompt_log._git_branch("/not/a/repo") == ""

    def test_oserror_returns_empty(self):
        with mock.patch("prompt_log.subprocess.run", side_effect=OSError):
            assert prompt_log._git_branch("/some/path") == ""

    def test_timeout_returns_empty(self):
        from subprocess import TimeoutExpired

        with mock.patch(
            "prompt_log.subprocess.run", side_effect=TimeoutExpired("git", 2)
        ):
            assert prompt_log._git_branch("/some/path") == ""


class TestExtractQuestionEntry:
    def test_question_with_options(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": {
                "questions": [
                    {
                        "question": "Which approach?",
                        "header": "Approach",
                        "options": [
                            {"label": "Option A", "description": "First"},
                            {"label": "Option B", "description": "Second"},
                        ],
                        "multiSelect": False,
                    }
                ],
                "answers": {"Which approach?": "Option A"},
            },
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert isinstance(result, list)
        assert len(result) == 1
        entry = result[0]
        assert entry["event_type"] == "question"
        assert entry["question"] == "Which approach?"
        assert entry["options"] == [
            {"label": "Option A", "description": "First"},
            {"label": "Option B", "description": "Second"},
        ]
        assert entry["answer"] == "Option A"
        assert entry["session_id"] == "abc-123"
        assert entry["git_branch"] == "main"

    def test_question_without_options(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": {
                "questions": [
                    {
                        "question": "What should I do?",
                        "header": "Action",
                        "options": [],
                        "multiSelect": False,
                    }
                ],
                "answers": {"What should I do?": "Just do it"},
            },
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert isinstance(result, list)
        entry = result[0]
        assert entry["event_type"] == "question"
        assert entry["question"] == "What should I do?"
        assert "options" not in entry
        assert entry["answer"] == "Just do it"

    def test_multiple_questions(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": {
                "questions": [
                    {
                        "question": "Q1?",
                        "header": "First",
                        "options": [
                            {"label": "A", "description": "a"},
                            {"label": "B", "description": "b"},
                        ],
                        "multiSelect": False,
                    },
                    {
                        "question": "Q2?",
                        "header": "Second",
                        "options": [
                            {"label": "X", "description": "x"},
                            {"label": "Y", "description": "y"},
                        ],
                        "multiSelect": False,
                    },
                ],
                "answers": {"Q1?": "A", "Q2?": "Y"},
            },
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert isinstance(result, list)
        assert len(result) == 2
        assert result[0]["question"] == "Q1?"
        assert result[0]["answer"] == "A"
        assert result[1]["question"] == "Q2?"
        assert result[1]["answer"] == "Y"

    def test_question_with_string_tool_input(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": json.dumps(
                {
                    "questions": [
                        {
                            "question": "Pick one",
                            "options": [{"label": "A"}, {"label": "B"}],
                        }
                    ],
                    "answers": {"Pick one": "B"},
                }
            ),
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert isinstance(result, list)
        entry = result[0]
        assert entry["question"] == "Pick one"
        assert entry["options"] == [
            {"label": "A", "description": ""},
            {"label": "B", "description": ""},
        ]
        assert entry["answer"] == "B"

    def test_question_with_invalid_string_tool_input(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": "not json",
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert result is None

    def test_post_tool_use_non_ask_user_returns_none(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "Bash",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
        }
        assert prompt_log._extract_entry(data) is None

    def test_question_missing_answer(self):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "tool_input": {
                "questions": [
                    {
                        "question": "Yes or no?",
                        "header": "Confirm",
                        "options": [
                            {"label": "Yes", "description": "y"},
                            {"label": "No", "description": "n"},
                        ],
                        "multiSelect": False,
                    }
                ],
                "answers": {},
            },
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            result = prompt_log._extract_entry(data)

        assert isinstance(result, list)
        assert result[0]["answer"] == ""


class TestExtractEntry:
    def test_prompt_event(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "prompt": "How do I fix this?",
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["event_type"] == "prompt"
        assert entry["session_id"] == "abc-123"
        assert entry["working_dir"] == "/home/user/project"
        assert entry["git_branch"] == "main"
        assert entry["content"] == "How do I fix this?"
        # Verify ISO format timestamp
        datetime.fromisoformat(entry["timestamp"])

    def test_stop_event(self):
        data = {
            "hook_event_name": "Stop",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "last_assistant_message": "Here is the answer.",
        }
        with mock.patch("prompt_log._git_branch", return_value="feature-x"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["event_type"] == "response"
        assert entry["content"] == "Here is the answer."

    def test_stop_event_missing_message(self):
        data = {
            "hook_event_name": "Stop",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["content"] == ""

    def test_invalid_session_id_returns_none(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "../etc/passwd",
            "prompt": "test",
        }
        assert prompt_log._extract_entry(data) is None

    def test_missing_session_id_returns_none(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "prompt": "test",
        }
        assert prompt_log._extract_entry(data) is None

    def test_unknown_event_returns_none(self):
        data = {
            "hook_event_name": "PreToolUse",
            "session_id": "abc-123",
        }
        assert prompt_log._extract_entry(data) is None

    def test_empty_cwd_skips_git(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "abc-123",
            "cwd": "",
            "prompt": "test",
        }
        with mock.patch("prompt_log._git_branch") as mock_git:
            entry = prompt_log._extract_entry(data)
            mock_git.assert_not_called()

        assert entry is not None
        assert entry["git_branch"] == ""


class TestWriteEntry:
    def test_creates_directory_and_appends(self, tmp_path):
        entry = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "Hello",
        }
        mock_dir = str(tmp_path / "prompt-log")
        with mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir):
            prompt_log._write_entry(entry)

        log_file = tmp_path / "prompt-log" / "2026-03-19" / "abc-123.jsonl"
        assert log_file.exists()
        lines = log_file.read_text().strip().split("\n")
        assert len(lines) == 1
        parsed = json.loads(lines[0])
        assert parsed["event_type"] == "prompt"
        assert parsed["content"] == "Hello"

    def test_appends_multiple_entries(self, tmp_path):
        entry1 = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "First",
        }
        entry2 = {
            "timestamp": "2026-03-19T10:30:05+00:00",
            "event_type": "response",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "Second",
        }
        mock_dir = str(tmp_path / "prompt-log")
        with mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir):
            prompt_log._write_entry(entry1)
            prompt_log._write_entry(entry2)

        log_file = tmp_path / "prompt-log" / "2026-03-19" / "abc-123.jsonl"
        lines = log_file.read_text().strip().split("\n")
        assert len(lines) == 2

    def test_different_dates_different_dirs(self, tmp_path):
        entry1 = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "",
            "git_branch": "",
            "content": "Day 1",
        }
        entry2 = {
            "timestamp": "2026-03-20T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "",
            "git_branch": "",
            "content": "Day 2",
        }
        mock_dir = str(tmp_path / "prompt-log")
        with mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir):
            prompt_log._write_entry(entry1)
            prompt_log._write_entry(entry2)

        log_base = tmp_path / "prompt-log"
        assert (log_base / "2026-03-19" / "abc-123.jsonl").exists()
        assert (log_base / "2026-03-20" / "abc-123.jsonl").exists()


class TestMain:
    def test_prompt_event_writes_log(self, tmp_path, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "prompt": "What is this?",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        mock_dir = str(tmp_path / "prompt-log")
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir),
        ):
            prompt_log.main()

        log_dir = tmp_path / "prompt-log"
        jsonl_files = list(log_dir.rglob("*.jsonl"))
        assert len(jsonl_files) == 1
        line = json.loads(jsonl_files[0].read_text().strip())
        assert line["event_type"] == "prompt"
        assert line["content"] == "What is this?"

    def test_stop_event_writes_log(self, tmp_path, monkeypatch):
        data = {
            "hook_event_name": "Stop",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "last_assistant_message": "Done.",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        mock_dir = str(tmp_path / "prompt-log")
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir),
        ):
            prompt_log.main()

        log_dir = tmp_path / "prompt-log"
        jsonl_files = list(log_dir.rglob("*.jsonl"))
        assert len(jsonl_files) == 1
        line = json.loads(jsonl_files[0].read_text().strip())
        assert line["event_type"] == "response"
        assert line["content"] == "Done."

    def test_question_event_writes_log(self, tmp_path, monkeypatch):
        data = {
            "hook_event_name": "PostToolUse",
            "tool_name": "AskUserQuestion",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "tool_input": {
                "questions": [
                    {
                        "question": "Continue?",
                        "header": "Confirm",
                        "options": [
                            {"label": "yes", "description": "proceed"},
                            {"label": "no", "description": "stop"},
                        ],
                        "multiSelect": False,
                    }
                ],
                "answers": {"Continue?": "yes"},
            },
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        mock_dir = str(tmp_path / "prompt-log")
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log.PROMPT_LOG_DIR", mock_dir),
        ):
            prompt_log.main()

        log_dir = tmp_path / "prompt-log"
        jsonl_files = list(log_dir.rglob("*.jsonl"))
        assert len(jsonl_files) == 1
        line = json.loads(jsonl_files[0].read_text().strip())
        assert line["event_type"] == "question"
        assert line["question"] == "Continue?"
        assert line["options"] == [
            {"label": "yes", "description": "proceed"},
            {"label": "no", "description": "stop"},
        ]
        assert line["answer"] == "yes"

    def test_bad_json_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        prompt_log.main()

    def test_empty_stdin_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        prompt_log.main()

    def test_invalid_session_id_no_crash(self, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "../bad",
            "prompt": "test",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        prompt_log.main()

    def test_write_failure_no_crash(self, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "prompt": "test",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log._write_entry", side_effect=OSError("disk full")),
        ):
            prompt_log.main()
