#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/prompt_log.py."""

import io
import json
import pathlib
import sys
from datetime import datetime
from unittest import mock

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import prompt_log  # noqa: E402


class TestValidSessionId:
    def test_valid_alphanumeric(self):
        assert prompt_log._valid_session_id("abc-123") is True

    def test_valid_uuid_like(self):
        uuid = "9a8dee8e-8e7f-4058-8df1-9d1c72e991bd"
        assert prompt_log._valid_session_id(uuid) is True

    def test_valid_underscore(self):
        assert prompt_log._valid_session_id("session_1") is True

    def test_rejects_empty(self):
        assert prompt_log._valid_session_id("") is False

    def test_rejects_path_traversal(self):
        assert prompt_log._valid_session_id("../etc/passwd") is False

    def test_rejects_slash(self):
        assert prompt_log._valid_session_id("foo/bar") is False

    def test_rejects_backslash(self):
        assert prompt_log._valid_session_id("foo\\bar") is False

    def test_rejects_space(self):
        assert prompt_log._valid_session_id("foo bar") is False

    def test_rejects_null_byte(self):
        assert prompt_log._valid_session_id("foo\x00bar") is False


class TestGitBranch:
    def test_returns_branch_name(self):
        result = mock.Mock()
        result.returncode = 0
        result.stdout = "feature-x\n"
        with mock.patch("prompt_log.subprocess.run", return_value=result) as mock_run:
            assert prompt_log._git_branch("/some/repo") == "feature-x"
            mock_run.assert_called_once()
            args = mock_run.call_args
            assert args[0][0] == ["git", "rev-parse", "--abbrev-ref", "HEAD"]
            assert args[1]["cwd"] == "/some/repo"

    def test_nonzero_exit_returns_empty(self):
        result = mock.Mock()
        result.returncode = 128
        result.stdout = ""
        with mock.patch("prompt_log.subprocess.run", return_value=result):
            assert prompt_log._git_branch("/not/a/repo") == ""

    def test_oserror_returns_empty(self):
        with mock.patch("prompt_log.subprocess.run", side_effect=OSError):
            assert prompt_log._git_branch("/some/path") == ""

    def test_timeout_returns_empty(self):
        from subprocess import TimeoutExpired

        with mock.patch(
            "prompt_log.subprocess.run", side_effect=TimeoutExpired("git", 2)
        ):
            assert prompt_log._git_branch("/some/path") == ""


class TestExtractEntry:
    def test_prompt_event(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "prompt": "How do I fix this?",
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["event_type"] == "prompt"
        assert entry["session_id"] == "abc-123"
        assert entry["working_dir"] == "/home/user/project"
        assert entry["git_branch"] == "main"
        assert entry["content"] == "How do I fix this?"
        # Verify ISO format timestamp
        datetime.fromisoformat(entry["timestamp"])

    def test_stop_event(self):
        data = {
            "hook_event_name": "Stop",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
            "last_assistant_message": "Here is the answer.",
        }
        with mock.patch("prompt_log._git_branch", return_value="feature-x"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["event_type"] == "response"
        assert entry["content"] == "Here is the answer."

    def test_stop_event_missing_message(self):
        data = {
            "hook_event_name": "Stop",
            "session_id": "abc-123",
            "cwd": "/home/user/project",
        }
        with mock.patch("prompt_log._git_branch", return_value="main"):
            entry = prompt_log._extract_entry(data)

        assert entry is not None
        assert entry["content"] == ""

    def test_invalid_session_id_returns_none(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "../etc/passwd",
            "prompt": "test",
        }
        assert prompt_log._extract_entry(data) is None

    def test_missing_session_id_returns_none(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "prompt": "test",
        }
        assert prompt_log._extract_entry(data) is None

    def test_unknown_event_returns_none(self):
        data = {
            "hook_event_name": "PreToolUse",
            "session_id": "abc-123",
        }
        assert prompt_log._extract_entry(data) is None

    def test_empty_cwd_skips_git(self):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "abc-123",
            "cwd": "",
            "prompt": "test",
        }
        with mock.patch("prompt_log._git_branch") as mock_git:
            entry = prompt_log._extract_entry(data)
            mock_git.assert_not_called()

        assert entry is not None
        assert entry["git_branch"] == ""


class TestWriteEntry:
    def test_creates_directory_and_appends(self, tmp_path):
        entry = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "Hello",
        }
        with mock.patch("prompt_log.os.path.expanduser", return_value=str(tmp_path)):
            prompt_log._write_entry(entry)

        log_file = tmp_path / ".claude" / "prompt-log" / "2026-03-19" / "abc-123.jsonl"
        assert log_file.exists()
        lines = log_file.read_text().strip().split("\n")
        assert len(lines) == 1
        parsed = json.loads(lines[0])
        assert parsed["event_type"] == "prompt"
        assert parsed["content"] == "Hello"

    def test_appends_multiple_entries(self, tmp_path):
        entry1 = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "First",
        }
        entry2 = {
            "timestamp": "2026-03-19T10:30:05+00:00",
            "event_type": "response",
            "session_id": "abc-123",
            "working_dir": "/home/user/project",
            "git_branch": "main",
            "content": "Second",
        }
        with mock.patch("prompt_log.os.path.expanduser", return_value=str(tmp_path)):
            prompt_log._write_entry(entry1)
            prompt_log._write_entry(entry2)

        log_file = tmp_path / ".claude" / "prompt-log" / "2026-03-19" / "abc-123.jsonl"
        lines = log_file.read_text().strip().split("\n")
        assert len(lines) == 2

    def test_different_dates_different_dirs(self, tmp_path):
        entry1 = {
            "timestamp": "2026-03-19T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "",
            "git_branch": "",
            "content": "Day 1",
        }
        entry2 = {
            "timestamp": "2026-03-20T10:30:00+00:00",
            "event_type": "prompt",
            "session_id": "abc-123",
            "working_dir": "",
            "git_branch": "",
            "content": "Day 2",
        }
        with mock.patch("prompt_log.os.path.expanduser", return_value=str(tmp_path)):
            prompt_log._write_entry(entry1)
            prompt_log._write_entry(entry2)

        log_base = tmp_path / ".claude" / "prompt-log"
        assert (log_base / "2026-03-19" / "abc-123.jsonl").exists()
        assert (log_base / "2026-03-20" / "abc-123.jsonl").exists()


class TestMain:
    def test_prompt_event_writes_log(self, tmp_path, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "prompt": "What is this?",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log.os.path.expanduser", return_value=str(tmp_path)),
        ):
            prompt_log.main()

        log_dir = tmp_path / ".claude" / "prompt-log"
        jsonl_files = list(log_dir.rglob("*.jsonl"))
        assert len(jsonl_files) == 1
        line = json.loads(jsonl_files[0].read_text().strip())
        assert line["event_type"] == "prompt"
        assert line["content"] == "What is this?"

    def test_stop_event_writes_log(self, tmp_path, monkeypatch):
        data = {
            "hook_event_name": "Stop",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "last_assistant_message": "Done.",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log.os.path.expanduser", return_value=str(tmp_path)),
        ):
            prompt_log.main()

        log_dir = tmp_path / ".claude" / "prompt-log"
        jsonl_files = list(log_dir.rglob("*.jsonl"))
        assert len(jsonl_files) == 1
        line = json.loads(jsonl_files[0].read_text().strip())
        assert line["event_type"] == "response"
        assert line["content"] == "Done."

    def test_bad_json_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        prompt_log.main()

    def test_empty_stdin_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        prompt_log.main()

    def test_invalid_session_id_no_crash(self, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "../bad",
            "prompt": "test",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        prompt_log.main()

    def test_write_failure_no_crash(self, monkeypatch):
        data = {
            "hook_event_name": "UserPromptSubmit",
            "session_id": "sess-1",
            "cwd": "/home/user/project",
            "prompt": "test",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with (
            mock.patch("prompt_log._git_branch", return_value="main"),
            mock.patch("prompt_log._write_entry", side_effect=OSError("disk full")),
        ):
            prompt_log.main()
