#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/notify.py."""

import io
import json
import pathlib
import sys
from unittest import mock

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import notify  # noqa: E402


class TestParseHookInput:
    def test_permission_prompt(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "Allow Bash(git status)?",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Approval Needed"
        assert result.body == "Allow Bash(git status)?"
        assert result.urgency == "critical"

    def test_permission_prompt_no_message(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.body == "Claude Code is waiting for your approval."

    def test_elicitation_dialog(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "elicitation_dialog",
            "message": "MCP server needs input",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Input Needed"
        assert result.body == "MCP server needs input"
        assert result.urgency == "critical"

    def test_idle_prompt_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "idle_prompt",
        }
        assert notify.parse_hook_input(data) is None

    def test_auth_success_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "auth_success",
        }
        assert notify.parse_hook_input(data) is None

    def test_unknown_notification_type_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "something_new",
        }
        assert notify.parse_hook_input(data) is None

    def test_stop_event(self):
        data = {"hook_event_name": "Stop"}
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Task Complete"
        assert result.urgency == "normal"

    def test_unknown_event_ignored(self):
        data = {"hook_event_name": "SessionStart"}
        assert notify.parse_hook_input(data) is None

    def test_empty_dict(self):
        assert notify.parse_hook_input({}) is None

    def test_missing_hook_event_name(self):
        data = {"notification_type": "permission_prompt"}
        assert notify.parse_hook_input(data) is None

    def test_empty_message_uses_default(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.body == "Claude Code is waiting for your approval."


class TestDetectPlatform:
    def test_linux_native(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19.7-100.fc42.x86_64"
        m = mock.mock_open(read_data=proc_version)
        with mock.patch("builtins.open", m):
            assert notify.detect_platform() == "linux"

    def test_wsl_detected_as_windows(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 5.15.0-1-Microsoft standard WSL2"
        m = mock.mock_open(read_data=proc_version)
        with mock.patch("builtins.open", m):
            assert notify.detect_platform() == "windows"

    def test_win32(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "win32")
        assert notify.detect_platform() == "windows"

    def test_linux_proc_version_missing(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        with mock.patch("builtins.open", side_effect=OSError):
            assert notify.detect_platform() == "linux"

    def test_darwin_unknown(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "darwin")
        assert notify.detect_platform() == "unknown"


class TestSendLinux:
    def test_calls_notify_send(self):
        n = notify.Notification(title="Test", body="Hello", urgency="normal")
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.send_linux(n)
            mock_run.assert_called_once_with(
                ["notify-send", "--urgency", "normal", "Test", "Hello"],
                check=False,
            )

    def test_critical_urgency(self):
        n = notify.Notification(title="Urgent", body="Now", urgency="critical")
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.send_linux(n)
            args = mock_run.call_args[0][0]
            assert args[2] == "critical"


class TestSendWindows:
    def test_raises_not_implemented(self):
        n = notify.Notification(title="Test", body="Hello", urgency="normal")
        with pytest.raises(NotImplementedError):
            notify.send_windows(n)


class TestMain:
    def test_permission_prompt_sends_notification(self, monkeypatch):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "Allow?",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19"
        with mock.patch("builtins.open", mock.mock_open(read_data=proc_version)):
            with mock.patch("notify.subprocess.run") as mock_run:
                notify.main()
                mock_run.assert_called_once()
                args = mock_run.call_args[0][0]
                assert args[3] == "Approval Needed"
                assert args[4] == "Allow?"

    def test_stop_sends_notification(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19"
        with mock.patch("builtins.open", mock.mock_open(read_data=proc_version)):
            with mock.patch("notify.subprocess.run") as mock_run:
                notify.main()
                mock_run.assert_called_once()

    def test_non_actionable_no_notification(self, monkeypatch):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "idle_prompt",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.main()
            mock_run.assert_not_called()

    def test_bad_json_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        notify.main()  # should not raise

    def test_empty_stdin_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        notify.main()  # should not raise

    def test_unknown_platform_no_crash(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "darwin")
        notify.main()  # should not raise

    def test_windows_platform_no_crash(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "win32")
        notify.main()  # should not raise (NotImplementedError caught)
