#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/reconcile.py."""

import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))
from reconcile import (  # noqa: E402
    EXIT_ERROR,
    EXIT_SUCCESS,
    merge_settings,
    reconcile_claude_md,
    reconcile_settings,
    main,
)


class TestMergeSettings:
    def test_empty_dest(self):
        src = {"key": "value", "nested": {"a": 1}}
        result = merge_settings({}, src)
        assert result == src

    def test_preserves_dest_only_keys(self):
        dest = {"model": "opus", "extra": "keep"}
        src = {"new_key": "added"}
        result = merge_settings(dest, src)
        assert result["model"] == "opus"
        assert result["extra"] == "keep"
        assert result["new_key"] == "added"

    def test_src_overwrites_scalars(self):
        dest = {"spinnerTipsEnabled": True, "autoUpdatesChannel": "stable"}
        src = {"spinnerTipsEnabled": False, "autoUpdatesChannel": "latest"}
        result = merge_settings(dest, src)
        assert result["spinnerTipsEnabled"] is False
        assert result["autoUpdatesChannel"] == "latest"

    def test_list_union_preserves_order(self):
        dest = {"allow": ["a", "b", "c"]}
        src = {"allow": ["b", "d", "e"]}
        result = merge_settings(dest, src)
        assert result["allow"] == ["a", "b", "c", "d", "e"]

    def test_list_union_no_duplicates(self):
        dest = {"items": ["x", "y"]}
        src = {"items": ["y", "z", "x"]}
        result = merge_settings(dest, src)
        assert result["items"] == ["x", "y", "z"]

    def test_nested_dict_merge(self):
        dest = {"permissions": {"allow": ["Bash(extra:*)"], "defaultMode": "ask"}}
        src = {"permissions": {"allow": ["Bash(ls:*)"], "defaultMode": "acceptEdits"}}
        result = merge_settings(dest, src)
        assert result["permissions"]["allow"] == ["Bash(extra:*)", "Bash(ls:*)"]
        assert result["permissions"]["defaultMode"] == "acceptEdits"

    def test_dict_merge_preserves_dest_only_nested_keys(self):
        dest = {"plugins": {"a": True, "b": True}}
        src = {"plugins": {"b": False, "c": True}}
        result = merge_settings(dest, src)
        assert result["plugins"] == {"a": True, "b": False, "c": True}

    def test_src_dict_over_dest_non_dict(self):
        dest = {"key": "string"}
        src = {"key": {"nested": True}}
        result = merge_settings(dest, src)
        assert result["key"] == {"nested": True}

    def test_src_scalar_over_dest_dict(self):
        dest = {"key": {"nested": True}}
        src = {"key": "replaced"}
        result = merge_settings(dest, src)
        assert result["key"] == "replaced"


class TestReconcileClaudeMd:
    def test_copies_when_different(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_identical(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_copies_when_dest_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir, dryrun=True)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "old content"

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "CLAUDE.md").write_text("content")

        reconcile_claude_md(src_dir, dest_dir)

        assert dest_dir.exists()
        assert (dest_dir / "CLAUDE.md").read_text() == "content"


class TestReconcileSettings:
    def test_merges_into_empty_dest(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        src_data = {
            "permissions": {"allow": ["Bash(ls:*)"]},
            "spinnerTipsEnabled": False,
        }
        (src_dir / "settings.json").write_text(json.dumps(src_data))
        (dest_dir / "settings.json").write_text("{}")

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == src_data

    def test_preserves_dest_only_keys(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))
        (dest_dir / "settings.json").write_text(json.dumps({"model": "opus", "a": 0}))

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["model"] == "opus"
        assert result["a"] == 1

    def test_unions_permission_lists(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(ls:*)", "WebSearch"]}})
        )
        (dest_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(extra:*)", "WebSearch"]}})
        )

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["permissions"]["allow"] == [
            "Bash(extra:*)",
            "WebSearch",
            "Bash(ls:*)",
        ]

    def test_already_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"new": True}))
        (dest_dir / "settings.json").write_text(json.dumps({"old": True}))

        changed = reconcile_settings(src_dir, dest_dir, dryrun=True)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"old": True}

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))

        reconcile_settings(src_dir, dest_dir)

        assert dest_dir.exists()
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"a": 1}

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False


class TestMain:
    def test_returns_error_when_src_missing(self, tmp_path):
        result = main([str(tmp_path / "nonexistent"), str(tmp_path / "dest")])
        assert result == EXIT_ERROR

    def test_returns_success_when_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        result = main([str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS

    def test_dryrun_does_not_modify(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new")
        (dest_dir / "CLAUDE.md").write_text("old")

        result = main(["--dryrun", str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS
        assert (dest_dir / "CLAUDE.md").read_text() == "old"

    def test_quiet_suppresses_output(self, src_dest_dirs, capsys):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        main(["--quiet", str(src_dir), str(dest_dir)])

        captured = capsys.readouterr()
        assert captured.out == ""


class TestBlockRealConfigWrites:
    """Verify the conftest guard blocks writes to real config paths."""

    def test_write_to_real_claude_dir_blocked(self):
        real_path = pathlib.Path.home() / ".claude" / "test_canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            real_path.write_text("should not be written")

    def test_copy_to_real_claude_dir_blocked(self, tmp_path):
        import shutil

        src = tmp_path / "src.txt"
        src.write_text("canary")
        dest = pathlib.Path.home() / ".claude" / "test_canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            shutil.copy2(src, dest)
