#!/usr/bin/env python3
# Generated By: Claude Code (claude-opus-5)
"""Tests for claude/settings.json.d/ fragments.

Hook retention is opt-in: openshell-sandbox's strip-settings.py keeps a hook
only if it carries a truthy `_keep`, and drops everything else on the way into
a sandbox. Nothing about that failure is loud -- an unmarked no-op is simply
absent, and the telemetry it existed to trigger stops.
"""

import json
import pathlib

import pytest

FRAGMENTS = (
    pathlib.Path(__file__).resolve().parent.parent / "claude" / "settings.json.d"
)
NOOP_FRAGMENT = FRAGMENTS / "hooks-noop.json"


def hooks_in(path):
    """Every (event, hook) pair in a settings fragment."""
    data = json.loads(path.read_text(encoding="utf-8"))
    return [
        (event, hook)
        for event, rules in (data.get("hooks") or {}).items()
        for rule in rules
        for hook in rule.get("hooks", [])
    ]


class TestNoopHooksAreMarked:
    """The no-ops exist solely to make Claude Code emit OTEL events for a hook
    type that would otherwise have none. All of them have to reach a sandbox."""

    def test_fragment_exists(self):
        assert NOOP_FRAGMENT.is_file(), f"missing {NOOP_FRAGMENT}"

    def test_every_noop_hook_is_marked(self):
        unmarked = [
            event for event, hook in hooks_in(NOOP_FRAGMENT) if not hook.get("_keep")
        ]
        assert not unmarked, (
            "these no-op hooks would be stripped out of a sandbox, silently "
            f"ending their telemetry: {unmarked}"
        )

    def test_marker_says_why(self):
        """A bare `true` survives stripping but tells the next reader nothing."""
        for event, hook in hooks_in(NOOP_FRAGMENT):
            marker = hook.get("_keep")
            assert (
                isinstance(marker, str) and marker.strip()
            ), f"{event}: _keep should be a reason, not {marker!r}"

    @pytest.mark.parametrize("fragment", sorted(FRAGMENTS.glob("hooks-*.json")))
    def test_fragments_are_valid_hook_shapes(self, fragment):
        """`make format` sorts these with jq; a malformed one still parses."""
        for event, hook in hooks_in(fragment):
            assert hook.get("type") == "command", f"{fragment.name} {event}: {hook}"
            assert hook.get("command"), f"{fragment.name} {event}: empty command"
