#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/notify.py."""

import io
import json
import pathlib
import sys
from unittest import mock

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import notify  # noqa: E402


class TestParseHookInput:
    def test_permission_prompt(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "Allow Bash(git status)?",
            "cwd": "/home/user/project",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Approval Needed"
        assert result.body == "Allow Bash(git status)?"
        assert result.urgency == "critical"
        assert result.cwd == "/home/user/project"

    def test_permission_prompt_no_message(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.body == "Claude Code is waiting for your approval."

    def test_elicitation_dialog(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "elicitation_dialog",
            "message": "MCP server needs input",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Input Needed"
        assert result.body == "MCP server needs input"
        assert result.urgency == "critical"

    def test_idle_prompt_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "idle_prompt",
        }
        assert notify.parse_hook_input(data) is None

    def test_auth_success_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "auth_success",
        }
        assert notify.parse_hook_input(data) is None

    def test_unknown_notification_type_ignored(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "something_new",
        }
        assert notify.parse_hook_input(data) is None

    def test_stop_event(self):
        data = {"hook_event_name": "Stop", "cwd": "/home/user/project"}
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.title == "Task Complete"
        assert result.urgency == "normal"
        assert result.cwd == "/home/user/project"

    def test_cwd_defaults_to_empty(self):
        data = {"hook_event_name": "Stop"}
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.cwd == ""

    def test_unknown_event_ignored(self):
        data = {"hook_event_name": "SessionStart"}
        assert notify.parse_hook_input(data) is None

    def test_empty_dict(self):
        assert notify.parse_hook_input({}) is None

    def test_missing_hook_event_name(self):
        data = {"notification_type": "permission_prompt"}
        assert notify.parse_hook_input(data) is None

    def test_empty_message_uses_default(self):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "",
        }
        result = notify.parse_hook_input(data)
        assert result is not None
        assert result.body == "Claude Code is waiting for your approval."


class TestDetectPlatform:
    def test_linux_native(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19.7-100.fc42.x86_64"
        m = mock.mock_open(read_data=proc_version)
        with mock.patch("builtins.open", m):
            assert notify.detect_platform() == "linux"

    def test_wsl_detected_as_windows(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 5.15.0-1-Microsoft standard WSL2"
        m = mock.mock_open(read_data=proc_version)
        with mock.patch("builtins.open", m):
            assert notify.detect_platform() == "windows"

    def test_win32(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "win32")
        assert notify.detect_platform() == "windows"

    def test_linux_proc_version_missing(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "linux")
        with mock.patch("builtins.open", side_effect=OSError):
            assert notify.detect_platform() == "linux"

    def test_darwin_unknown(self, monkeypatch):
        monkeypatch.setattr(sys, "platform", "darwin")
        assert notify.detect_platform() == "unknown"


class TestShellJoin:
    def test_simple_args(self):
        assert notify._shell_join(["echo", "hello"]) == "echo hello"

    def test_args_with_spaces(self):
        result = notify._shell_join(["code", "/path/with spaces/dir"])
        assert "with spaces" in result
        # Should be quoted
        assert "'" in result or "\\" in result


class TestBuildNotifyCmd:
    def test_without_cwd(self):
        n = notify.Notification(title="Test", body="Hello", urgency="normal")
        cmd = notify._build_notify_cmd(n)
        assert cmd == ["notify-send", "--urgency", "normal", "Test", "Hello"]
        assert "--action" not in cmd
        assert "--wait" not in cmd

    def test_with_cwd(self):
        n = notify.Notification(
            title="Test", body="Hello", urgency="normal", cwd="/home/user/project"
        )
        cmd = notify._build_notify_cmd(n)
        assert "--action" in cmd
        assert "focus=Focus" in cmd
        assert "--wait" in cmd
        assert cmd[-2] == "Test"
        assert cmd[-1] == "Hello"


class TestSendLinux:
    def test_calls_notify_send_without_cwd(self):
        n = notify.Notification(title="Test", body="Hello", urgency="normal")
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.send_linux(n)
            mock_run.assert_called_once_with(
                ["notify-send", "--urgency", "normal", "Test", "Hello"],
                check=False,
            )

    def test_critical_urgency(self):
        n = notify.Notification(title="Urgent", body="Now", urgency="critical")
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.send_linux(n)
            args = mock_run.call_args[0][0]
            assert args[2] == "critical"

    def test_with_cwd_spawns_background_process(self):
        n = notify.Notification(
            title="Test", body="Hello", urgency="normal", cwd="/home/user/project"
        )
        with mock.patch("notify.shutil.which", return_value="/usr/bin/code"):
            with mock.patch("notify.subprocess.Popen") as mock_popen:
                notify.send_linux(n)
                mock_popen.assert_called_once()
                call_args = mock_popen.call_args
                cmd_list = call_args[0][0]
                assert cmd_list[0] == "bash"
                assert cmd_list[1] == "-c"
                script = cmd_list[2]
                assert "notify-send" in script
                assert "focus" in script
                assert "/home/user/project" in script
                assert call_args[1]["start_new_session"] is True

    def test_with_cwd_does_not_call_run(self):
        n = notify.Notification(
            title="Test", body="Hello", urgency="normal", cwd="/home/user/project"
        )
        with mock.patch("notify.shutil.which", return_value="/usr/bin/code"):
            with mock.patch("notify.subprocess.Popen"):
                with mock.patch("notify.subprocess.run") as mock_run:
                    notify.send_linux(n)
                    mock_run.assert_not_called()

    def test_with_cwd_falls_back_to_code_if_which_fails(self):
        n = notify.Notification(
            title="Test", body="Hello", urgency="normal", cwd="/tmp"
        )
        with mock.patch("notify.shutil.which", return_value=None):
            with mock.patch("notify.subprocess.Popen") as mock_popen:
                notify.send_linux(n)
                script = mock_popen.call_args[0][0][2]
                assert "code" in script


class TestSendWindows:
    def test_raises_not_implemented(self):
        n = notify.Notification(title="Test", body="Hello", urgency="normal")
        with pytest.raises(NotImplementedError):
            notify.send_windows(n)


class TestMain:
    def test_permission_prompt_sends_notification(self, monkeypatch):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "permission_prompt",
            "message": "Allow?",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19"
        with mock.patch("builtins.open", mock.mock_open(read_data=proc_version)):
            with mock.patch("notify.subprocess.run") as mock_run:
                notify.main()
                mock_run.assert_called_once()
                args = mock_run.call_args[0][0]
                assert args[3] == "Approval Needed"
                assert args[4] == "Allow?"

    def test_stop_sends_notification(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "linux")
        proc_version = "Linux version 6.19"
        with mock.patch("builtins.open", mock.mock_open(read_data=proc_version)):
            with mock.patch("notify.subprocess.run") as mock_run:
                notify.main()
                mock_run.assert_called_once()

    def test_non_actionable_no_notification(self, monkeypatch):
        data = {
            "hook_event_name": "Notification",
            "notification_type": "idle_prompt",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with mock.patch("notify.subprocess.run") as mock_run:
            notify.main()
            mock_run.assert_not_called()

    def test_bad_json_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        notify.main()  # should not raise

    def test_empty_stdin_no_crash(self, monkeypatch):
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        notify.main()  # should not raise

    def test_unknown_platform_no_crash(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "darwin")
        notify.main()  # should not raise

    def test_windows_platform_no_crash(self, monkeypatch):
        data = {"hook_event_name": "Stop"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(sys, "platform", "win32")
        notify.main()  # should not raise (NotImplementedError caught)
