#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for statusline.py.

All file I/O is redirected to tmp_path. No real credentials or
config files are ever read.
"""

import io
import json
import time

import pytest

from scripts import statusline

SAMPLE_USAGE_RESPONSE = {
    "five_hour": {
        "utilization": 7.0,
        "resets_at": "2026-03-17T07:00:00+00:00",
    },
    "seven_day": {
        "utilization": 4.0,
        "resets_at": "2026-03-22T17:00:00+00:00",
    },
}

SAMPLE_STDIN = {
    "model": {"display_name": "Opus 4.6"},
    "context_window": {"used_percentage": 12},
}


@pytest.fixture(autouse=True)
def isolate_paths(tmp_path, monkeypatch):
    """Redirect all module-level paths to tmp_path."""
    cache_file = tmp_path / "oauth_usage.json"
    creds_file = tmp_path / "credentials.json"
    monkeypatch.setattr(statusline, "USAGE_CACHE_FILE", cache_file)
    monkeypatch.setattr(statusline, "CREDENTIALS_FILE", creds_file)
    monkeypatch.delenv("CLAUDE_CODE_USE_VERTEX", raising=False)
    return tmp_path, cache_file, creds_file


# --- format_duration ---


class TestFormatDuration:
    def test_zero(self):
        assert statusline.format_duration(0) == "0s"

    def test_negative_clamps(self):
        assert statusline.format_duration(-5) == "0s"

    def test_seconds_only(self):
        assert statusline.format_duration(45) == "45s"

    def test_minutes_seconds(self):
        assert statusline.format_duration(90) == "1m30s"

    def test_minutes_exact(self):
        assert statusline.format_duration(120) == "2m"

    def test_hours_minutes(self):
        assert statusline.format_duration(3720) == "1h2m"

    def test_hours_exact(self):
        assert statusline.format_duration(7200) == "2h"

    def test_days_hours(self):
        assert statusline.format_duration(90000) == "1d1h"

    def test_days_exact(self):
        assert statusline.format_duration(86400) == "1d"

    def test_days_no_minutes(self):
        # 2 days 0 hours — should be just "2d", not "2d0h"
        assert statusline.format_duration(172800) == "2d"

    def test_multi_day(self):
        # 4 days 12 hours
        assert statusline.format_duration(4 * 86400 + 12 * 3600) == "4d12h"

    def test_never_three_units(self):
        # 1d 2h 30m 15s — should be "1d2h", not "1d2h30m"
        assert statusline.format_duration(86400 + 7200 + 1800 + 15) == "1d2h"


# --- format_remaining ---


class TestFormatRemaining:
    def test_none_input(self):
        assert statusline.format_remaining(None) is None

    def test_empty_string(self):
        assert statusline.format_remaining("") is None

    def test_invalid_timestamp(self):
        assert statusline.format_remaining("not-a-date") is None

    def test_past_returns_zero(self, monkeypatch):
        assert statusline.format_remaining("2020-01-01T00:00:00+00:00") == "0s"

    def test_future_timestamp(self, monkeypatch):
        from datetime import datetime, timezone, timedelta

        future = datetime.now(timezone.utc) + timedelta(hours=3, minutes=4)
        result = statusline.format_remaining(future.isoformat())
        assert result.startswith("3h")

    def test_days_remaining(self, monkeypatch):
        from datetime import datetime, timezone, timedelta

        future = datetime.now(timezone.utc) + timedelta(days=4, hours=12)
        result = statusline.format_remaining(future.isoformat())
        assert result.startswith("4d")


# --- get_oauth_token ---


class TestGetOauthToken:
    def test_returns_token(self, isolate_paths):
        _, _, creds_file = isolate_paths
        creds_file.write_text(
            json.dumps({"claudeAiOauth": {"accessToken": "tok_abc"}}),
            encoding="utf-8",
        )
        assert statusline.get_oauth_token() == "tok_abc"

    def test_missing_file(self):
        assert statusline.get_oauth_token() is None

    def test_malformed_json(self, isolate_paths):
        _, _, creds_file = isolate_paths
        creds_file.write_text("{bad", encoding="utf-8")
        assert statusline.get_oauth_token() is None

    def test_missing_key(self, isolate_paths):
        _, _, creds_file = isolate_paths
        creds_file.write_text(json.dumps({"other": {}}), encoding="utf-8")
        assert statusline.get_oauth_token() is None


# --- fetch_usage ---


class TestFetchUsage:
    def test_no_token_returns_none(self, monkeypatch):
        monkeypatch.setattr(statusline, "get_oauth_token", lambda: None)
        assert statusline.fetch_usage() is None

    def test_success(self, monkeypatch):
        monkeypatch.setattr(statusline, "get_oauth_token", lambda: "tok")
        resp_body = json.dumps(SAMPLE_USAGE_RESPONSE).encode()
        mock_resp = io.BytesIO(resp_body)

        class FakeContext:
            def __enter__(self):
                return mock_resp

            def __exit__(self, *a):
                pass

        monkeypatch.setattr(
            statusline.urllib.request,
            "urlopen",
            lambda req, timeout=None: FakeContext(),
        )
        result = statusline.fetch_usage()
        assert result["five_hour"]["utilization"] == 7.0

    def test_network_error(self, monkeypatch):
        monkeypatch.setattr(statusline, "get_oauth_token", lambda: "tok")
        monkeypatch.setattr(
            statusline.urllib.request,
            "urlopen",
            lambda req, timeout=None: (_ for _ in ()).throw(
                statusline.urllib.error.URLError("fail")
            ),
        )
        assert statusline.fetch_usage() is None


# --- get_usage ---


class TestGetUsage:
    def test_fresh_cache_hit(self, isolate_paths, monkeypatch):
        _, cache_file, _ = isolate_paths
        cache_time = time.time() - 30
        cached = {"v": SAMPLE_USAGE_RESPONSE, "t": cache_time}
        cache_file.write_text(json.dumps(cached), encoding="utf-8")

        fetch_called = []
        monkeypatch.setattr(
            statusline,
            "fetch_usage",
            lambda: fetch_called.append(1),
        )

        usage, age, stale = statusline.get_usage()
        assert usage == SAMPLE_USAGE_RESPONSE
        assert age >= 30
        assert stale is False
        assert len(fetch_called) == 0

    def test_stale_cache_triggers_fetch(self, isolate_paths, monkeypatch):
        _, cache_file, _ = isolate_paths
        stale_time = time.time() - statusline.USAGE_CACHE_TTL_SECONDS - 10
        cached = {"v": {"old": True}, "t": stale_time}
        cache_file.write_text(json.dumps(cached), encoding="utf-8")

        monkeypatch.setattr(
            statusline,
            "fetch_usage",
            lambda: SAMPLE_USAGE_RESPONSE,
        )

        usage, age, stale = statusline.get_usage()
        assert usage == SAMPLE_USAGE_RESPONSE
        assert age == 0
        assert stale is False

    def test_fetch_failure_uses_stale_cache(self, isolate_paths, monkeypatch):
        _, cache_file, _ = isolate_paths
        stale_time = time.time() - statusline.USAGE_CACHE_TTL_SECONDS - 10
        cached = {"v": {"stale": True}, "t": stale_time}
        cache_file.write_text(json.dumps(cached), encoding="utf-8")

        monkeypatch.setattr(statusline, "fetch_usage", lambda: None)

        usage, age, stale = statusline.get_usage()
        assert usage == {"stale": True}
        assert age >= statusline.USAGE_CACHE_TTL_SECONDS
        assert stale is True

    def test_no_cache_no_fetch(self, monkeypatch):
        monkeypatch.setattr(statusline, "fetch_usage", lambda: None)
        usage, age, stale = statusline.get_usage()
        assert usage is None
        assert age == 0
        assert stale is False

    def test_fetch_writes_cache(self, isolate_paths, monkeypatch):
        _, cache_file, _ = isolate_paths
        monkeypatch.setattr(
            statusline,
            "fetch_usage",
            lambda: SAMPLE_USAGE_RESPONSE,
        )

        statusline.get_usage()
        assert cache_file.exists()
        written = json.loads(cache_file.read_text(encoding="utf-8"))
        assert written["v"] == SAMPLE_USAGE_RESPONSE

    def test_corrupt_cache_ignored(self, isolate_paths, monkeypatch):
        _, cache_file, _ = isolate_paths
        cache_file.write_text("{corrupt", encoding="utf-8")

        monkeypatch.setattr(
            statusline,
            "fetch_usage",
            lambda: SAMPLE_USAGE_RESPONSE,
        )
        usage, age, stale = statusline.get_usage()
        assert usage == SAMPLE_USAGE_RESPONSE
        assert stale is False


# --- main ---


class TestMain:
    def _run_main(
        self,
        monkeypatch,
        capsys,
        stdin_data,
        usage=None,
        age=0,
        stale=False,
    ):
        monkeypatch.setattr(
            "sys.stdin",
            io.StringIO(json.dumps(stdin_data)),
        )
        monkeypatch.setattr(
            statusline,
            "get_usage",
            lambda: (usage, age, stale),
        )
        statusline.main()
        return capsys.readouterr().out.strip()

    def test_invalid_stdin(self, monkeypatch, capsys):
        monkeypatch.setattr("sys.stdin", io.StringIO("not json"))
        monkeypatch.setattr(
            statusline,
            "get_usage",
            lambda: (None, 0, False),
        )
        statusline.main()
        assert capsys.readouterr().out.strip() == "Claude Code"

    def test_basic_output(self, monkeypatch, capsys):
        output = self._run_main(monkeypatch, capsys, SAMPLE_STDIN)
        assert "Model: Opus 4.6" in output
        assert "Context: 12%" in output

    def test_with_usage_fresh(self, monkeypatch, capsys):
        from datetime import datetime, timezone, timedelta

        future_5h = (
            datetime.now(timezone.utc) + timedelta(hours=3, minutes=4)
        ).isoformat()
        future_1w = (
            datetime.now(timezone.utc) + timedelta(days=4, hours=12)
        ).isoformat()
        usage = {
            "five_hour": {"utilization": 7.0, "resets_at": future_5h},
            "seven_day": {"utilization": 4.0, "resets_at": future_1w},
        }
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=usage,
            age=120,
            stale=False,
        )
        # Labels should be time-remaining, not "5h"/"1w"
        assert "7%" in output
        assert "4%" in output
        assert "3h" in output  # ~3h remaining for 5h bucket
        assert "4d" in output  # ~4d remaining for weekly
        assert "(2m)" in output
        assert "!" not in output

    def test_with_usage_stale(self, monkeypatch, capsys):
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=SAMPLE_USAGE_RESPONSE,
            age=600,
            stale=True,
        )
        assert "7%" in output
        assert "(!10m)" in output

    def test_with_usage_just_fetched(self, monkeypatch, capsys):
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=SAMPLE_USAGE_RESPONSE,
            age=0,
            stale=False,
        )
        assert "(0s)" in output

    def test_no_usage(self, monkeypatch, capsys):
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=None,
        )
        assert "%" not in output or "Context: 12%" in output
        assert "(" not in output

    def test_missing_resets_at_uses_fallback_label(self, monkeypatch, capsys):
        usage = {
            "five_hour": {"utilization": 10.0},
            "seven_day": {"utilization": 5.0},
        }
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=usage,
        )
        assert "5h: 10%" in output
        assert "1w: 5%" in output

    def test_no_context_window(self, monkeypatch, capsys):
        data = {"model": {"display_name": "Sonnet"}}
        output = self._run_main(monkeypatch, capsys, data)
        assert "Context:" not in output
        assert "Model: Sonnet" in output

    def test_default_model(self, monkeypatch, capsys):
        output = self._run_main(monkeypatch, capsys, {})
        assert "Model: Claude" in output

    def test_vertex_mode(self, monkeypatch, capsys):
        monkeypatch.setenv("CLAUDE_CODE_USE_VERTEX", "1")
        data = {
            **SAMPLE_STDIN,
            "cost": {"total_cost_usd": 1.50},
            "session_id": "test-session",
        }
        monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(data)))
        monkeypatch.setattr(
            statusline,
            "get_usage",
            lambda: (None, 0, False),
        )

        import types

        mock_tracker = types.ModuleType("session_tracker")
        mock_tracker.track_session = lambda data: None
        mock_tracker.get_daily_cost = lambda: 5.25
        monkeypatch.setitem(
            __import__("sys").modules,
            "scripts.session_tracker",
            mock_tracker,
        )

        statusline.main()
        output = capsys.readouterr().out.strip()
        assert "Session: $1.50" in output
        assert "Today: $5.25" in output

    def test_no_cost_in_vertex(self, monkeypatch, capsys):
        monkeypatch.setenv("CLAUDE_CODE_USE_VERTEX", "1")
        monkeypatch.setattr(
            "sys.stdin",
            io.StringIO(json.dumps(SAMPLE_STDIN)),
        )
        monkeypatch.setattr(
            statusline,
            "get_usage",
            lambda: (None, 0, False),
        )

        import types

        mock_tracker = types.ModuleType("session_tracker")
        mock_tracker.track_session = lambda data: None
        mock_tracker.get_daily_cost = lambda: 0.0
        monkeypatch.setitem(
            __import__("sys").modules,
            "scripts.session_tracker",
            mock_tracker,
        )

        statusline.main()
        output = capsys.readouterr().out.strip()
        assert "Session: $0.00" in output

    def test_no_session_cost_without_vertex(self, monkeypatch, capsys):
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=SAMPLE_USAGE_RESPONSE,
        )
        assert "Session:" not in output
        assert "Today:" not in output

    def test_null_usage_fields(self, monkeypatch, capsys):
        usage = {
            "five_hour": None,
            "seven_day": {"utilization": 3.0},
        }
        output = self._run_main(
            monkeypatch,
            capsys,
            SAMPLE_STDIN,
            usage=usage,
        )
        # five_hour is None so should be skipped
        # seven_day has no resets_at so falls back to "1w"
        assert "1w: 3%" in output
