#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/session_tracker.py."""

import json
from datetime import date

import pytest

from scripts.session_tracker import (
    _normalize_project_dir,
    get_daily_cost,
    get_previous_day_cost,
    get_project_cost,
    track_session,
)


def _make_session_data(session_id="abc-123", cost_usd=1.50, project_dir=None):
    data = {
        "session_id": session_id,
        "model": {"id": "claude-opus-4-6", "display_name": "Opus 4.6"},
        "cost": {"total_cost_usd": cost_usd},
        "context_window": {"used_percentage": 10},
    }
    if project_dir is not None:
        data["workspace"] = {"project_dir": project_dir}
    return data


class TestTrackSession:
    def test_creates_date_dir_and_file(self, tmp_path):
        data = _make_session_data()
        track_session(data, base_dir=tmp_path)

        today_dir = tmp_path / date.today().isoformat()
        assert today_dir.is_dir()

        session_file = today_dir / "abc-123.json"
        assert session_file.exists()

        saved = json.loads(session_file.read_text())
        assert saved["session_id"] == "abc-123"
        assert saved["cost"]["total_cost_usd"] == 1.50

    def test_overwrites_on_update(self, tmp_path):
        track_session(_make_session_data(cost_usd=1.00), base_dir=tmp_path)
        track_session(_make_session_data(cost_usd=2.50), base_dir=tmp_path)

        session_file = tmp_path / date.today().isoformat() / "abc-123.json"
        saved = json.loads(session_file.read_text())
        assert saved["cost"]["total_cost_usd"] == 2.50

    def test_multiple_sessions(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=1.00), base_dir=tmp_path
        )
        track_session(
            _make_session_data(session_id="s2", cost_usd=3.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        files = list(today_dir.glob("*.json"))
        assert len(files) == 2

    def test_skips_missing_session_id(self, tmp_path):
        data = {"cost": {"total_cost_usd": 1.00}}
        track_session(data, base_dir=tmp_path)
        assert not list(tmp_path.iterdir())

    def test_rejects_path_traversal(self, tmp_path):
        data = _make_session_data(session_id="../../etc/evil")
        track_session(data, base_dir=tmp_path)
        assert not list(tmp_path.iterdir())

    def test_rejects_slash_in_session_id(self, tmp_path):
        data = _make_session_data(session_id="foo/bar")
        track_session(data, base_dir=tmp_path)
        assert not list(tmp_path.iterdir())

    def test_preserves_full_blob(self, tmp_path):
        data = _make_session_data()
        data["extra_field"] = "preserved"
        data["workspace"] = {"cwd": "/some/path"}
        track_session(data, base_dir=tmp_path)

        session_file = tmp_path / date.today().isoformat() / "abc-123.json"
        saved = json.loads(session_file.read_text())
        assert saved["extra_field"] == "preserved"
        assert saved["workspace"]["cwd"] == "/some/path"


class TestGetDailyCost:
    def test_sums_all_sessions(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=1.50), base_dir=tmp_path
        )
        track_session(
            _make_session_data(session_id="s2", cost_usd=2.25), base_dir=tmp_path
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(3.75)

    def test_returns_zero_for_missing_dir(self, tmp_path):
        assert get_daily_cost(base_dir=tmp_path) == 0.0

    def test_skips_malformed_json(self, tmp_path):
        track_session(
            _make_session_data(session_id="good", cost_usd=5.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        bad_file = today_dir / "bad.json"
        bad_file.write_text("not json{{{")

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(5.00)

    def test_handles_missing_cost_field(self, tmp_path):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir(parents=True)
        no_cost_file = today_dir / "no-cost.json"
        no_cost_file.write_text(json.dumps({"session_id": "x"}))

        track_session(
            _make_session_data(session_id="good", cost_usd=3.00), base_dir=tmp_path
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(3.00)

    def test_ignores_non_json_files(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=2.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        (today_dir / "notes.txt").write_text("not a session")

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(2.00)

    def test_only_reads_today(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=2.00), base_dir=tmp_path
        )

        yesterday_dir = tmp_path / "2020-01-01"
        yesterday_dir.mkdir()
        old_file = yesterday_dir / "old-session.json"
        old_file.write_text(
            json.dumps(_make_session_data(session_id="old", cost_usd=99.00))
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(2.00)


class TestGetPreviousDayCost:
    def test_sums_most_recent_prior_day(self, tmp_path):
        yesterday = tmp_path / "2020-01-01"
        yesterday.mkdir()
        (yesterday / "s1.json").write_text(
            json.dumps(_make_session_data(session_id="s1", cost_usd=2.00))
        )
        (yesterday / "s2.json").write_text(
            json.dumps(_make_session_data(session_id="s2", cost_usd=3.50))
        )

        # Today's data should be ignored
        track_session(
            _make_session_data(session_id="today", cost_usd=99.00),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == pytest.approx(5.50)
        assert count == 2

    def test_picks_most_recent_day(self, tmp_path):
        old = tmp_path / "2020-01-01"
        old.mkdir()
        (old / "s1.json").write_text(
            json.dumps(_make_session_data(session_id="s1", cost_usd=1.00))
        )

        recent = tmp_path / "2020-06-15"
        recent.mkdir()
        (recent / "s2.json").write_text(
            json.dumps(_make_session_data(session_id="s2", cost_usd=7.00))
        )

        # Today's dir so both prior dirs qualify
        track_session(
            _make_session_data(session_id="today", cost_usd=0.10),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == pytest.approx(7.00)
        assert count == 1

    def test_returns_zero_when_no_prior_days(self, tmp_path):
        # Only today exists
        track_session(
            _make_session_data(session_id="s1", cost_usd=5.00),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == 0.0
        assert count == 0

    def test_returns_zero_for_missing_dir(self, tmp_path):
        total, count = get_previous_day_cost(base_dir=tmp_path / "nonexistent")
        assert total == 0.0
        assert count == 0

    def test_skips_malformed_json(self, tmp_path):
        day = tmp_path / "2020-01-01"
        day.mkdir()
        (day / "good.json").write_text(
            json.dumps(_make_session_data(session_id="good", cost_usd=4.00))
        )
        (day / "bad.json").write_text("not json{{{")

        # Need today to exist so 2020-01-01 counts as "previous"
        track_session(
            _make_session_data(session_id="today", cost_usd=0.10),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == pytest.approx(4.00)
        assert count == 1

    def test_ignores_non_json_files(self, tmp_path):
        day = tmp_path / "2020-01-01"
        day.mkdir()
        (day / "s1.json").write_text(
            json.dumps(_make_session_data(session_id="s1", cost_usd=2.00))
        )
        (day / "notes.txt").write_text("not a session")

        track_session(
            _make_session_data(session_id="today", cost_usd=0.10),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == pytest.approx(2.00)
        assert count == 1

    def test_handles_missing_cost_field(self, tmp_path):
        day = tmp_path / "2020-01-01"
        day.mkdir()
        (day / "no-cost.json").write_text(json.dumps({"session_id": "x"}))
        (day / "good.json").write_text(
            json.dumps(_make_session_data(session_id="good", cost_usd=3.00))
        )

        track_session(
            _make_session_data(session_id="today", cost_usd=0.10),
            base_dir=tmp_path,
        )

        total, count = get_previous_day_cost(base_dir=tmp_path)
        assert total == pytest.approx(3.00)
        # Both files are counted (one has cost 0.0, other has 3.00)
        assert count == 2


class TestNormalizeProjectDir:
    def test_plain_path_unchanged(self):
        path = "/home/user/source/myproject"
        assert _normalize_project_dir(path) == path

    def test_strips_worktree_suffix(self):
        wt = "/home/user/source/myproject/git-worktrees/abc123"
        assert _normalize_project_dir(wt) == "/home/user/source/myproject"

    def test_no_worktree_name_unchanged(self):
        # git-worktrees at the end without a child stays as-is
        path = "/home/user/git-worktrees"
        assert _normalize_project_dir(path) == path

    def test_windows_path_unchanged(self):
        path = "C:/Users/jewza/source/myproject"
        assert _normalize_project_dir(path) == path

    def test_windows_worktree_stripped(self):
        wt = "C:/Users/jewza/source/myproject/git-worktrees/abc123"
        assert _normalize_project_dir(wt) == "C:/Users/jewza/source/myproject"

    def test_windows_backslash_path(self):
        # PurePosixPath treats backslashes as part of the name, not separators.
        # Callers are expected to normalize to forward slashes before calling.
        path = "C:/Users/jewza/source/myproject"
        assert _normalize_project_dir(path) == path


class TestGetProjectCost:
    def test_sums_across_dates(self, tmp_path):
        # Create sessions in multiple date dirs
        d1 = tmp_path / "2026-03-18"
        d1.mkdir()
        d2 = tmp_path / "2026-03-19"
        d2.mkdir()

        proj = "/home/user/myproject"
        (d1 / "s1.json").write_text(
            json.dumps(
                _make_session_data(session_id="s1", cost_usd=2.00, project_dir=proj)
            )
        )
        (d2 / "s2.json").write_text(
            json.dumps(
                _make_session_data(session_id="s2", cost_usd=3.50, project_dir=proj)
            )
        )

        total = get_project_cost(proj, base_dir=tmp_path)
        assert total == pytest.approx(5.50)

    def test_filters_by_project_dir(self, tmp_path):
        d = tmp_path / "2026-03-18"
        d.mkdir()

        (d / "s1.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s1", cost_usd=2.00, project_dir="/proj/a"
                )
            )
        )
        (d / "s2.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s2", cost_usd=5.00, project_dir="/proj/b"
                )
            )
        )

        assert get_project_cost("/proj/a", base_dir=tmp_path) == pytest.approx(2.00)
        assert get_project_cost("/proj/b", base_dir=tmp_path) == pytest.approx(5.00)

    def test_worktree_rollup(self, tmp_path):
        d = tmp_path / "2026-03-18"
        d.mkdir()

        (d / "s1.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s1",
                    cost_usd=4.00,
                    project_dir="/home/user/myproject/git-worktrees/1234",
                )
            )
        )
        (d / "s2.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s2",
                    cost_usd=1.00,
                    project_dir="/home/user/myproject",
                )
            )
        )

        total = get_project_cost("/home/user/myproject", base_dir=tmp_path)
        assert total == pytest.approx(5.00)

    def test_returns_zero_for_unknown_project(self, tmp_path):
        d = tmp_path / "2026-03-18"
        d.mkdir()
        (d / "s1.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s1", cost_usd=2.00, project_dir="/proj/a"
                )
            )
        )

        assert get_project_cost("/proj/unknown", base_dir=tmp_path) == 0.0

    def test_handles_missing_workspace(self, tmp_path):
        d = tmp_path / "2026-03-18"
        d.mkdir()

        # Session without workspace field
        (d / "s1.json").write_text(
            json.dumps(_make_session_data(session_id="s1", cost_usd=2.00))
        )
        # Session with workspace
        (d / "s2.json").write_text(
            json.dumps(
                _make_session_data(
                    session_id="s2", cost_usd=3.00, project_dir="/proj/a"
                )
            )
        )

        assert get_project_cost("/proj/a", base_dir=tmp_path) == pytest.approx(3.00)
