#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/block_paths.py."""

import io
import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import block_paths  # noqa: E402

HOME = str(pathlib.Path.home())


class TestCheckPath:
    """Test blocked path pattern matching."""

    @pytest.mark.parametrize(
        "path,expected",
        [
            (f"{HOME}/.ssh", "~/.ssh"),
            (f"{HOME}/.ssh/", "~/.ssh"),
            (f"{HOME}/.ssh/id_rsa", "~/.ssh"),
            (f"{HOME}/.ssh/config", "~/.ssh"),
            (f"{HOME}/.ssh/known_hosts", "~/.ssh"),
            (f"{HOME}/.aws", "~/.aws"),
            (f"{HOME}/.aws/credentials", "~/.aws"),
            (f"{HOME}/.aws/config", "~/.aws"),
            (f"{HOME}/.kube", "~/.kube"),
            (f"{HOME}/.kube/config", "~/.kube"),
            (f"{HOME}/.ocm", "~/.ocm"),
            (f"{HOME}/.ocm/ocm.json", "~/.ocm"),
            (f"{HOME}/.claude/credentials", "credentials file"),
            (f"{HOME}/.claude/my-credentials", "credentials file"),
            (f"{HOME}/.claude/sub/dir/credentials.json", "credentials file"),
        ],
    )
    def test_blocked_paths(self, path: str, expected: str) -> None:
        assert block_paths.check_path(path) == expected

    @pytest.mark.parametrize(
        "path",
        [
            f"{HOME}/.ssh-backup",
            f"{HOME}/.ssh-backup/key",
            f"{HOME}/.sshrc",
            f"{HOME}/.aws-old",
            f"{HOME}/.kube-config",
            f"{HOME}/.ocm-backup",
            f"{HOME}/.claude/settings.json",
            f"{HOME}/.claude/CLAUDE.md",
            f"{HOME}/projects/myapp",
            "/tmp/safe",
            f"{HOME}/source/code.py",
        ],
    )
    def test_allowed_paths(self, path: str) -> None:
        assert block_paths.check_path(path) is None


class TestResolvePath:
    """Test path resolution logic."""

    def test_absolute_unchanged(self) -> None:
        result = block_paths.resolve_path("/usr/local/bin", "/tmp")
        assert result == "/usr/local/bin"

    def test_tilde_expansion(self) -> None:
        result = block_paths.resolve_path("~/.ssh/config", "/tmp")
        assert result == f"{HOME}/.ssh/config"

    def test_home_var_expansion(self) -> None:
        result = block_paths.resolve_path("$HOME/.ssh/config", "/tmp")
        assert result == f"{HOME}/.ssh/config"

    def test_relative_resolved_against_cwd(self) -> None:
        result = block_paths.resolve_path("id_rsa", f"{HOME}/.ssh")
        assert result == f"{HOME}/.ssh/id_rsa"

    def test_relative_with_subdir(self) -> None:
        result = block_paths.resolve_path("sub/file.txt", "/tmp/project")
        assert result == "/tmp/project/sub/file.txt"

    def test_dot_dot_normalized(self) -> None:
        result = block_paths.resolve_path("../secret", f"{HOME}/.ssh/keys")
        assert result == f"{HOME}/.ssh/secret"


class TestExtractPathsStructured:
    """Test path extraction from structured tool inputs."""

    def test_read_file_path(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Read", {"file_path": f"{HOME}/.ssh/config"}, "/tmp"
        )
        assert paths == [f"{HOME}/.ssh/config"]

    def test_edit_file_path(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Edit", {"file_path": f"{HOME}/.aws/credentials"}, "/tmp"
        )
        assert paths == [f"{HOME}/.aws/credentials"]

    def test_write_file_path(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Write", {"file_path": "/tmp/safe.txt"}, "/tmp"
        )
        assert paths == ["/tmp/safe.txt"]

    def test_glob_pattern_and_path(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Glob",
            {"pattern": "**/*.pem", "path": f"{HOME}/.ssh"},
            "/tmp",
        )
        assert len(paths) == 2
        assert f"{HOME}/.ssh" in paths[1]

    def test_grep_path(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Grep", {"path": f"{HOME}/.kube", "pattern": "server:"}, "/tmp"
        )
        assert paths == [f"{HOME}/.kube"]

    def test_notebook_edit(self) -> None:
        paths = block_paths.extract_paths_structured(
            "NotebookEdit", {"notebook_path": "/tmp/notebook.ipynb"}, "/tmp"
        )
        assert paths == ["/tmp/notebook.ipynb"]

    def test_unknown_tool_returns_empty(self) -> None:
        paths = block_paths.extract_paths_structured(
            "WebSearch", {"query": "hello"}, "/tmp"
        )
        assert paths == []

    def test_missing_field_skipped(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Read", {"other_field": "value"}, "/tmp"
        )
        assert paths == []

    def test_relative_file_path_resolved(self) -> None:
        paths = block_paths.extract_paths_structured(
            "Read", {"file_path": "config"}, f"{HOME}/.ssh"
        )
        assert paths == [f"{HOME}/.ssh/config"]


class TestExtractPathsBash:
    """Test path extraction from Bash commands."""

    def test_tilde_ssh(self) -> None:
        paths = block_paths.extract_paths_bash("cat ~/.ssh/id_rsa", "/tmp")
        resolved = [p for p in paths if ".ssh" in p]
        assert any(p == f"{HOME}/.ssh/id_rsa" for p in resolved)

    def test_dollar_home_ssh(self) -> None:
        paths = block_paths.extract_paths_bash("cat $HOME/.ssh/id_rsa", "/tmp")
        resolved = [p for p in paths if ".ssh" in p]
        assert any(p == f"{HOME}/.ssh/id_rsa" for p in resolved)

    def test_absolute_ssh(self) -> None:
        paths = block_paths.extract_paths_bash(f"cat {HOME}/.ssh/id_rsa", "/tmp")
        assert f"{HOME}/.ssh/id_rsa" in paths

    def test_relative_in_blocked_cwd(self) -> None:
        paths = block_paths.extract_paths_bash("cat id_rsa", f"{HOME}/.ssh")
        assert f"{HOME}/.ssh/id_rsa" in paths

    def test_mixed_command(self) -> None:
        cmd = "cp ~/.ssh/id_rsa /tmp/backup"
        paths = block_paths.extract_paths_bash(cmd, "/tmp")
        ssh_paths = [p for p in paths if ".ssh" in p]
        assert any(p == f"{HOME}/.ssh/id_rsa" for p in ssh_paths)

    def test_flags_skipped(self) -> None:
        paths = block_paths.extract_paths_bash("ls -la /tmp/safe", "/tmp")
        assert "/tmp/safe" in paths
        # -la should not appear as a resolved path containing .ssh etc.
        for p in paths:
            assert not p.endswith("-la")

    def test_safe_command_no_blocked(self) -> None:
        paths = block_paths.extract_paths_bash("ls /tmp/safe", "/tmp")
        for p in paths:
            assert block_paths.check_path(p) is None


class TestExtractPaths:
    """Test the top-level extract_paths dispatcher."""

    def test_bash_dispatches(self) -> None:
        paths = block_paths.extract_paths(
            "Bash", {"command": "cat ~/.ssh/config"}, "/tmp"
        )
        assert any(f"{HOME}/.ssh/config" == p for p in paths)

    def test_read_dispatches(self) -> None:
        paths = block_paths.extract_paths(
            "Read", {"file_path": f"{HOME}/.ssh/config"}, "/tmp"
        )
        assert paths == [f"{HOME}/.ssh/config"]

    def test_empty_bash_command(self) -> None:
        paths = block_paths.extract_paths("Bash", {"command": ""}, "/tmp")
        assert paths == []

    def test_no_bash_command(self) -> None:
        paths = block_paths.extract_paths("Bash", {}, "/tmp")
        assert paths == []

    def test_unknown_tool(self) -> None:
        paths = block_paths.extract_paths("WebSearch", {"query": "hello"}, "/tmp")
        assert paths == []


class TestCommandChaining:
    """Semicolon command chaining must be blocked in Bash commands."""

    @pytest.mark.parametrize(
        "command",
        [
            "FOO=ssh; ls ~/.${FOO}/",
            "ls /tmp; cat ~/.ssh/config",
            "echo hello; echo world",
            "cd /tmp; ls",
        ],
    )
    def test_semicolon_chaining_blocked(
        self, command: str, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": command},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_semicolon_in_quotes_allowed(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "grep 'foo;bar' /tmp/file.txt"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_semicolon_in_double_quotes_allowed(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": 'grep "foo;bar" /tmp/file.txt'},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_no_semicolon_allowed(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "ls /tmp"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_chaining_message_on_stderr(
        self,
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "echo a; echo b"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit):
            block_paths.main()
        captured = capsys.readouterr()
        assert "semicolon command chaining" in captured.err

    def test_chaining_only_applies_to_bash(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {
            "tool_name": "Read",
            "tool_input": {"file_path": "/tmp/file;name.txt"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise


class TestIntegration:
    """End-to-end tests for main() with stdin simulation."""

    def test_read_ssh_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Read",
            "tool_input": {"file_path": f"{HOME}/.ssh/config"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_read_safe_allowed(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Read",
            "tool_input": {"file_path": "/tmp/safe.txt"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_bash_ssh_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "cat ~/.ssh/id_rsa"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_bash_relative_in_ssh_blocked(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "cat id_rsa"},
            "cwd": f"{HOME}/.ssh",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_glob_aws_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Glob",
            "tool_input": {"pattern": "**/*", "path": f"{HOME}/.aws"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_grep_kube_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Grep",
            "tool_input": {"path": f"{HOME}/.kube", "pattern": "server"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_write_credentials_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Write",
            "tool_input": {
                "file_path": f"{HOME}/.claude/credentials",
                "content": "secret",
            },
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_edit_credentials_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Edit",
            "tool_input": {
                "file_path": f"{HOME}/.claude/credentials.json",
            },
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_unknown_tool_allowed(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "WebSearch",
            "tool_input": {"query": "hello"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_empty_stdin(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        block_paths.main()  # should not raise

    def test_bad_json(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        block_paths.main()  # should not raise

    def test_no_tool_input(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {"tool_name": "Read"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise

    def test_blocked_message_on_stderr(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        data = {
            "tool_name": "Read",
            "tool_input": {"file_path": f"{HOME}/.ssh/config"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit):
            block_paths.main()
        captured = capsys.readouterr()
        assert "BLOCKED: access to ~/.ssh is not allowed" in captured.err

    def test_bash_dollar_home_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Bash",
            "tool_input": {"command": "cat $HOME/.aws/credentials"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_paths.main()
        assert exc_info.value.code == 2

    def test_ssh_backup_not_blocked(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {
            "tool_name": "Read",
            "tool_input": {"file_path": f"{HOME}/.ssh-backup/key"},
            "cwd": "/tmp",
        }
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_paths.main()  # should not raise
