#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/block_commands.py."""

import io
import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))

import block_commands  # noqa: E402


class TestCheckCommand:
    """Test pattern matching for blocked commands."""

    @pytest.mark.parametrize(
        "command,expected",
        [
            ("git add .", "git add"),
            ("git add -A", "git add"),
            ("git add file.txt", "git add"),
            ("git   add file.txt", "git add"),
            ("git push", "git push"),
            ("git push origin main", "git push"),
            ("git push --force", "git push"),
            ("sudo rm -rf /", "sudo"),
            ("sudo apt install foo", "sudo"),
            ("make reconcile", "make reconcile"),
            ("make  reconcile", "make reconcile"),
        ],
    )
    def test_blocked_commands(self, command: str, expected: str) -> None:
        assert block_commands.check_command(command) == expected

    @pytest.mark.parametrize(
        "command",
        [
            "git status",
            "git commit -m test",
            "git diff",
            "git log",
            "git stash",
            "ls -la",
            "make test",
            "make format",
            "python3 script.py",
            "echo hello",
            "",
        ],
    )
    def test_allowed_commands(self, command: str) -> None:
        assert block_commands.check_command(command) is None

    def test_su_standalone(self) -> None:
        assert block_commands.check_command("su") == "su"
        assert block_commands.check_command("su -") == "su"
        assert block_commands.check_command("su root") == "su"

    def test_su_in_pipeline(self) -> None:
        assert block_commands.check_command("echo x | su") == "su"
        assert block_commands.check_command("cmd && su") == "su"
        assert block_commands.check_command("cmd || su") == "su"
        assert block_commands.check_command("cmd; su") == "su"

    def test_su_not_substring(self) -> None:
        assert block_commands.check_command("git submodule status") is None
        assert block_commands.check_command("sudo apt install") == "sudo"
        assert block_commands.check_command("surplus") is None
        assert block_commands.check_command("result") is None

    def test_git_push_in_chain(self) -> None:
        assert block_commands.check_command("git add . && git push") is not None

    def test_sudo_in_chain(self) -> None:
        assert block_commands.check_command("ls && sudo rm foo") == "sudo"

    @pytest.mark.parametrize(
        "command,expected",
        [
            ("/usr/bin/git add .", "git add"),
            ("/usr/local/bin/git push origin main", "git push"),
            ("/usr/bin/sudo rm -rf /", "sudo"),
            ("/usr/bin/make reconcile", "make reconcile"),
            ("./bin/git add foo", "git add"),
            ("/sbin/su", "su"),
        ],
    )
    def test_path_qualified_commands_blocked(
        self, command: str, expected: str
    ) -> None:
        assert block_commands.check_command(command) == expected

    @pytest.mark.parametrize(
        "command,expected",
        [
            ("env git add .", "git add"),
            ("env git push origin main", "git push"),
            ("env -i sudo rm foo", "sudo"),
            ("env make reconcile", "make reconcile"),
        ],
    )
    def test_env_prefixed_commands_blocked(
        self, command: str, expected: str
    ) -> None:
        assert block_commands.check_command(command) == expected

    @pytest.mark.parametrize(
        "command,expected",
        [
            ("git -C /some/path add foo", "git add"),
            ("git -C /some/path push origin main", "git push"),
            ("/usr/bin/git -C /some/path add foo", "git add"),
            ("git --git-dir=/tmp/.git add .", "git add"),
            ("git -c user.name=test push", "git push"),
            ("git -C /path --work-tree=/tmp add file.txt", "git add"),
        ],
    )
    def test_git_flags_before_subcommand_blocked(
        self, command: str, expected: str
    ) -> None:
        assert block_commands.check_command(command) == expected

    @pytest.mark.parametrize(
        "command,expected",
        [
            ("make -C /some/path reconcile", "make reconcile"),
            ("make -f Makefile reconcile", "make reconcile"),
            ("make --directory=/path reconcile", "make reconcile"),
            ("/usr/bin/make -C /tmp reconcile", "make reconcile"),
        ],
    )
    def test_make_flags_before_target_blocked(
        self, command: str, expected: str
    ) -> None:
        assert block_commands.check_command(command) == expected

    def test_blocked_word_in_heredoc_not_matched(self) -> None:
        cmd = 'git commit -m "$(cat <<\'EOF\'\ngit add blocked\nEOF\n)"'
        assert block_commands.check_command(cmd) is None

    def test_blocked_word_before_heredoc_still_matched(self) -> None:
        cmd = 'git push && cat <<EOF\nhello\nEOF'
        assert block_commands.check_command(cmd) == "git push"


class TestMain:
    def test_blocked_command_exits_2(self, monkeypatch: pytest.MonkeyPatch) -> None:
        data = {"tool_input": {"command": "git push origin main"}}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit) as exc_info:
            block_commands.main()
        assert exc_info.value.code == 2

    def test_allowed_command_exits_normally(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {"tool_input": {"command": "git status"}}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_commands.main()  # should not raise

    def test_empty_command_exits_normally(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {"tool_input": {"command": ""}}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_commands.main()  # should not raise

    def test_no_command_field_exits_normally(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {"tool_input": {}}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_commands.main()  # should not raise

    def test_no_tool_input_exits_normally(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        data = {"tool_name": "Bash"}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        block_commands.main()  # should not raise

    def test_bad_json_no_crash(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
        block_commands.main()  # should not raise

    def test_empty_stdin_no_crash(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(sys, "stdin", io.StringIO(""))
        block_commands.main()  # should not raise

    def test_blocked_message_on_stderr(
        self, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        data = {"tool_input": {"command": "sudo rm -rf /"}}
        monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(data)))
        with pytest.raises(SystemExit):
            block_commands.main()
        captured = capsys.readouterr()
        assert "BLOCKED: sudo is not allowed" in captured.err
