#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/reconcile.py."""

import json
import pathlib

import pytest

from scripts.reconcile import (
    EXIT_ERROR,
    EXIT_SUCCESS,
    main,
    merge_settings,
    reconcile_claude_md,
    reconcile_scripts,
    reconcile_settings,
)


class TestMergeSettings:
    def test_empty_dest(self):
        src = {"key": "value", "nested": {"a": 1}}
        result = merge_settings({}, src)
        assert result == src

    def test_preserves_dest_only_keys(self):
        dest = {"model": "opus", "extra": "keep"}
        src = {"new_key": "added"}
        result = merge_settings(dest, src)
        assert result["model"] == "opus"
        assert result["extra"] == "keep"
        assert result["new_key"] == "added"

    def test_src_overwrites_scalars(self):
        dest = {"spinnerTipsEnabled": True, "autoUpdatesChannel": "stable"}
        src = {"spinnerTipsEnabled": False, "autoUpdatesChannel": "latest"}
        result = merge_settings(dest, src)
        assert result["spinnerTipsEnabled"] is False
        assert result["autoUpdatesChannel"] == "latest"

    def test_list_union_preserves_order(self):
        dest = {"allow": ["a", "b", "c"]}
        src = {"allow": ["b", "d", "e"]}
        result = merge_settings(dest, src)
        assert result["allow"] == ["a", "b", "c", "d", "e"]

    def test_list_union_no_duplicates(self):
        dest = {"items": ["x", "y"]}
        src = {"items": ["y", "z", "x"]}
        result = merge_settings(dest, src)
        assert result["items"] == ["x", "y", "z"]

    def test_nested_dict_merge(self):
        dest = {"permissions": {"allow": ["Bash(extra:*)"], "defaultMode": "ask"}}
        src = {"permissions": {"allow": ["Bash(ls:*)"], "defaultMode": "acceptEdits"}}
        result = merge_settings(dest, src)
        assert result["permissions"]["allow"] == ["Bash(extra:*)", "Bash(ls:*)"]
        assert result["permissions"]["defaultMode"] == "acceptEdits"

    def test_dict_merge_preserves_dest_only_nested_keys(self):
        dest = {"plugins": {"a": True, "b": True}}
        src = {"plugins": {"b": False, "c": True}}
        result = merge_settings(dest, src)
        assert result["plugins"] == {"a": True, "b": False, "c": True}

    def test_src_dict_over_dest_non_dict(self):
        dest = {"key": "string"}
        src = {"key": {"nested": True}}
        result = merge_settings(dest, src)
        assert result["key"] == {"nested": True}

    def test_src_scalar_over_dest_dict(self):
        dest = {"key": {"nested": True}}
        src = {"key": "replaced"}
        result = merge_settings(dest, src)
        assert result["key"] == "replaced"


class TestReconcileClaudeMd:
    def test_copies_when_different(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_identical(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_copies_when_dest_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir, dryrun=True)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "old content"

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "CLAUDE.md").write_text("content")

        reconcile_claude_md(src_dir, dest_dir)

        assert dest_dir.exists()
        assert (dest_dir / "CLAUDE.md").read_text() == "content"


class TestReconcileSettings:
    def test_merges_into_empty_dest(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        src_data = {
            "permissions": {"allow": ["Bash(ls:*)"]},
            "spinnerTipsEnabled": False,
        }
        (src_dir / "settings.json").write_text(json.dumps(src_data))
        (dest_dir / "settings.json").write_text("{}")

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == src_data

    def test_preserves_dest_only_keys(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))
        (dest_dir / "settings.json").write_text(json.dumps({"model": "opus", "a": 0}))

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["model"] == "opus"
        assert result["a"] == 1

    def test_unions_permission_lists(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(ls:*)", "WebSearch"]}})
        )
        (dest_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(extra:*)", "WebSearch"]}})
        )

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["permissions"]["allow"] == [
            "Bash(extra:*)",
            "WebSearch",
            "Bash(ls:*)",
        ]

    def test_already_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"new": True}))
        (dest_dir / "settings.json").write_text(json.dumps({"old": True}))

        changed = reconcile_settings(src_dir, dest_dir, dryrun=True)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"old": True}

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))

        reconcile_settings(src_dir, dest_dir)

        assert dest_dir.exists()
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"a": 1}

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False


class TestReconcileScripts:
    def test_copies_scripts(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "foo.py").write_text("print(1)")
        (scripts_dir / "bar.py").write_text("print(2)")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is True
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        assert (dest_scripts / "foo.py").read_text() == "print(1)"
        assert (dest_scripts / "bar.py").read_text() == "print(2)"

    def test_skips_identical_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        dest_scripts.mkdir(parents=True)
        (scripts_dir / "same.py").write_text("same")
        (dest_scripts / "same.py").write_text("same")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is False

    def test_overwrites_changed_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        dest_scripts.mkdir(parents=True)
        (scripts_dir / "mod.py").write_text("new")
        (dest_scripts / "mod.py").write_text("old")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is True
        assert (dest_scripts / "mod.py").read_text() == "new"

    def test_dryrun_does_not_write(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "new.py").write_text("content")

        changed = reconcile_scripts(repo_dir, dest_dir, dryrun=True)

        assert changed is True
        assert not (dest_dir / "my-claude-stuff" / "scripts" / "new.py").exists()

    def test_missing_scripts_dir(self, tmp_path):
        repo_dir = tmp_path / "repo"
        repo_dir.mkdir()
        dest_dir = tmp_path / "dest"
        dest_dir.mkdir()

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is False

    def test_only_copies_py_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "good.py").write_text("ok")
        (scripts_dir / "notes.txt").write_text("skip me")

        reconcile_scripts(repo_dir, dest_dir)

        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        assert (dest_scripts / "good.py").exists()
        assert not (dest_scripts / "notes.txt").exists()


class TestMain:
    def test_returns_error_when_src_missing(self, tmp_path):
        result = main([str(tmp_path / "nonexistent"), str(tmp_path / "dest")])
        assert result == EXIT_ERROR

    def test_returns_success_when_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        result = main([str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS

    def test_dryrun_does_not_modify(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new")
        (dest_dir / "CLAUDE.md").write_text("old")

        result = main(["--dryrun", str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS
        assert (dest_dir / "CLAUDE.md").read_text() == "old"

    def test_quiet_suppresses_output(self, src_dest_dirs, capsys):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        main(["--quiet", str(src_dir), str(dest_dir)])

        captured = capsys.readouterr()
        assert captured.out == ""


class TestConfTestGuard:
    """Verify the conftest guard blocks all I/O to protected paths.

    Every guard must block both ~/.claude and ~/.config/claude,
    and must fail closed (block on error, never allow through).
    """

    # --- write_text ---

    def test_write_text_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    def test_write_text_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    def test_write_text_blocked_nested_subdir(self):
        path = pathlib.Path.home() / ".claude" / "deep" / "nested" / "f.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    # --- read_text ---

    def test_read_text_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.read_text()

    def test_read_text_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.read_text()

    # --- shutil.copy2 ---

    def test_copy2_blocked(self, tmp_path):
        import shutil

        src = tmp_path / "src.txt"
        src.write_text("canary")
        dest = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            shutil.copy2(src, dest)

    # --- builtins.open ---

    def test_open_write_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "w")

    def test_open_read_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "r")

    def test_open_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "r")

    # --- tmp_path is allowed ---

    def test_write_text_allowed_tmp_path(self, tmp_path):
        path = tmp_path / "ok.txt"
        path.write_text("allowed")
        assert path.read_text() == "allowed"

    def test_open_allowed_tmp_path(self, tmp_path):
        path = tmp_path / "ok.txt"
        with open(path, "w") as fh:
            fh.write("allowed")
        with open(path, "r") as fh:
            assert fh.read() == "allowed"

    # --- fail closed: _is_blocked returns True on error ---

    def test_is_blocked_fails_closed(self, monkeypatch):
        from tests.conftest import _is_blocked

        # Force resolve() to raise, simulating an unresolvable path
        def bad_resolve(self):
            raise OSError("cannot resolve")

        monkeypatch.setattr(pathlib.Path, "resolve", bad_resolve)
        assert _is_blocked(pathlib.Path("/some/random/path")) is True
