#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/session_tracker.py."""

import json
import pathlib
import sys
from datetime import date

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "scripts"))
from session_tracker import get_daily_cost, track_session  # noqa: E402


def _make_session_data(session_id="abc-123", cost_usd=1.50):
    return {
        "session_id": session_id,
        "model": {"id": "claude-opus-4-6", "display_name": "Opus 4.6"},
        "cost": {"total_cost_usd": cost_usd},
        "context_window": {"used_percentage": 10},
    }


class TestTrackSession:
    def test_creates_date_dir_and_file(self, tmp_path):
        data = _make_session_data()
        track_session(data, base_dir=tmp_path)

        today_dir = tmp_path / date.today().isoformat()
        assert today_dir.is_dir()

        session_file = today_dir / "abc-123.json"
        assert session_file.exists()

        saved = json.loads(session_file.read_text())
        assert saved["session_id"] == "abc-123"
        assert saved["cost"]["total_cost_usd"] == 1.50

    def test_overwrites_on_update(self, tmp_path):
        track_session(_make_session_data(cost_usd=1.00), base_dir=tmp_path)
        track_session(_make_session_data(cost_usd=2.50), base_dir=tmp_path)

        session_file = tmp_path / date.today().isoformat() / "abc-123.json"
        saved = json.loads(session_file.read_text())
        assert saved["cost"]["total_cost_usd"] == 2.50

    def test_multiple_sessions(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=1.00), base_dir=tmp_path
        )
        track_session(
            _make_session_data(session_id="s2", cost_usd=3.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        files = list(today_dir.glob("*.json"))
        assert len(files) == 2

    def test_skips_missing_session_id(self, tmp_path):
        data = {"cost": {"total_cost_usd": 1.00}}
        track_session(data, base_dir=tmp_path)
        assert not list(tmp_path.iterdir())

    def test_preserves_full_blob(self, tmp_path):
        data = _make_session_data()
        data["extra_field"] = "preserved"
        data["workspace"] = {"cwd": "/some/path"}
        track_session(data, base_dir=tmp_path)

        session_file = tmp_path / date.today().isoformat() / "abc-123.json"
        saved = json.loads(session_file.read_text())
        assert saved["extra_field"] == "preserved"
        assert saved["workspace"]["cwd"] == "/some/path"


class TestGetDailyCost:
    def test_sums_all_sessions(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=1.50), base_dir=tmp_path
        )
        track_session(
            _make_session_data(session_id="s2", cost_usd=2.25), base_dir=tmp_path
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(3.75)

    def test_returns_zero_for_missing_dir(self, tmp_path):
        assert get_daily_cost(base_dir=tmp_path) == 0.0

    def test_skips_malformed_json(self, tmp_path):
        track_session(
            _make_session_data(session_id="good", cost_usd=5.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        bad_file = today_dir / "bad.json"
        bad_file.write_text("not json{{{")

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(5.00)

    def test_handles_missing_cost_field(self, tmp_path):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir(parents=True)
        no_cost_file = today_dir / "no-cost.json"
        no_cost_file.write_text(json.dumps({"session_id": "x"}))

        track_session(
            _make_session_data(session_id="good", cost_usd=3.00), base_dir=tmp_path
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(3.00)

    def test_ignores_non_json_files(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=2.00), base_dir=tmp_path
        )

        today_dir = tmp_path / date.today().isoformat()
        (today_dir / "notes.txt").write_text("not a session")

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(2.00)

    def test_only_reads_today(self, tmp_path):
        track_session(
            _make_session_data(session_id="s1", cost_usd=2.00), base_dir=tmp_path
        )

        yesterday_dir = tmp_path / "2020-01-01"
        yesterday_dir.mkdir()
        old_file = yesterday_dir / "old-session.json"
        old_file.write_text(
            json.dumps(_make_session_data(session_id="old", cost_usd=99.00))
        )

        total = get_daily_cost(base_dir=tmp_path)
        assert total == pytest.approx(2.00)
