#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/reconcile.py."""

import json
import pathlib

import pytest

from scripts.reconcile import (
    EXIT_ERROR,
    EXIT_SUCCESS,
    _adapt_hooks,
    _adapt_python_command,
    load_settings_with_fragments,
    main,
    merge_settings,
    reconcile_claude_md,
    reconcile_scripts,
    reconcile_settings,
)


class TestMergeSettings:
    def test_empty_dest(self):
        src = {"key": "value", "nested": {"a": 1}}
        result = merge_settings({}, src)
        assert result == src

    def test_preserves_dest_only_keys(self):
        dest = {"model": "opus", "extra": "keep"}
        src = {"new_key": "added"}
        result = merge_settings(dest, src)
        assert result["model"] == "opus"
        assert result["extra"] == "keep"
        assert result["new_key"] == "added"

    def test_src_overwrites_scalars(self):
        dest = {"spinnerTipsEnabled": True, "autoUpdatesChannel": "stable"}
        src = {"spinnerTipsEnabled": False, "autoUpdatesChannel": "latest"}
        result = merge_settings(dest, src)
        assert result["spinnerTipsEnabled"] is False
        assert result["autoUpdatesChannel"] == "latest"

    def test_list_union_preserves_order(self):
        dest = {"allow": ["a", "b", "c"]}
        src = {"allow": ["b", "d", "e"]}
        result = merge_settings(dest, src)
        assert result["allow"] == ["a", "b", "c", "d", "e"]

    def test_list_union_no_duplicates(self):
        dest = {"items": ["x", "y"]}
        src = {"items": ["y", "z", "x"]}
        result = merge_settings(dest, src)
        assert result["items"] == ["x", "y", "z"]

    def test_nested_dict_merge(self):
        dest = {"permissions": {"allow": ["Bash(extra:*)"], "defaultMode": "ask"}}
        src = {"permissions": {"allow": ["Bash(ls:*)"], "defaultMode": "acceptEdits"}}
        result = merge_settings(dest, src)
        assert result["permissions"]["allow"] == ["Bash(extra:*)", "Bash(ls:*)"]
        assert result["permissions"]["defaultMode"] == "acceptEdits"

    def test_dict_merge_preserves_dest_only_nested_keys(self):
        dest = {"plugins": {"a": True, "b": True}}
        src = {"plugins": {"b": False, "c": True}}
        result = merge_settings(dest, src)
        assert result["plugins"] == {"a": True, "b": False, "c": True}

    def test_src_dict_over_dest_non_dict(self):
        dest = {"key": "string"}
        src = {"key": {"nested": True}}
        result = merge_settings(dest, src)
        assert result["key"] == {"nested": True}

    def test_src_scalar_over_dest_dict(self):
        dest = {"key": {"nested": True}}
        src = {"key": "replaced"}
        result = merge_settings(dest, src)
        assert result["key"] == "replaced"


class TestAdaptPythonCommand:
    def test_replaces_python3_on_windows(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        assert _adapt_python_command("python3 ~/foo.py") == "py -3 ~/foo.py"

    def test_preserves_python3_on_linux(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Linux")
        assert _adapt_python_command("python3 ~/foo.py") == "python3 ~/foo.py"

    def test_preserves_python3_on_darwin(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Darwin")
        assert _adapt_python_command("python3 ~/foo.py") == "python3 ~/foo.py"

    def test_no_change_when_no_python3_prefix(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        assert _adapt_python_command("node ~/foo.js") == "node ~/foo.js"

    def test_only_replaces_at_start(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        # "python3" not at start should not be replaced
        assert _adapt_python_command("env python3 ~/foo.py") == "env python3 ~/foo.py"


class TestAdaptHooks:
    def test_adapts_hook_commands(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        settings = {
            "hooks": {
                "PreToolUse": [
                    {
                        "hooks": [
                            {
                                "command": "python3 ~/.claude/scripts/block.py",
                                "type": "command",
                            }
                        ],
                        "matcher": "Bash",
                    }
                ]
            }
        }
        result = _adapt_hooks(settings)
        hook_cmd = result["hooks"]["PreToolUse"][0]["hooks"][0]["command"]
        assert hook_cmd == "py -3 ~/.claude/scripts/block.py"

    def test_adapts_statusline_command(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        settings = {
            "statusLine": {
                "command": "python3 ~/.claude/scripts/status.py",
                "type": "command",
            }
        }
        result = _adapt_hooks(settings)
        assert result["statusLine"]["command"] == "py -3 ~/.claude/scripts/status.py"

    def test_no_change_on_linux(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Linux")
        settings = {
            "hooks": {
                "PreToolUse": [
                    {
                        "hooks": [
                            {
                                "command": "python3 ~/.claude/scripts/block.py",
                                "type": "command",
                            }
                        ],
                        "matcher": "Bash",
                    }
                ]
            },
            "statusLine": {
                "command": "python3 ~/.claude/scripts/status.py",
                "type": "command",
            },
        }
        result = _adapt_hooks(settings)
        assert (
            result["hooks"]["PreToolUse"][0]["hooks"][0]["command"]
            == "python3 ~/.claude/scripts/block.py"
        )
        assert result["statusLine"]["command"] == "python3 ~/.claude/scripts/status.py"

    def test_preserves_non_hook_keys(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        settings = {
            "spinnerTipsEnabled": False,
            "permissions": {"allow": ["Bash(ls:*)"]},
        }
        result = _adapt_hooks(settings)
        assert result["spinnerTipsEnabled"] is False
        assert result["permissions"] == {"allow": ["Bash(ls:*)"]}

    def test_does_not_mutate_input(self, monkeypatch):
        monkeypatch.setattr("scripts.reconcile.platform.system", lambda: "Windows")
        original_cmd = "python3 ~/.claude/scripts/block.py"
        settings = {
            "hooks": {
                "PreToolUse": [
                    {
                        "hooks": [{"command": original_cmd, "type": "command"}],
                        "matcher": "",
                    }
                ]
            }
        }
        _adapt_hooks(settings)
        # Original should be unchanged
        assert settings["hooks"]["PreToolUse"][0]["hooks"][0]["command"] == original_cmd


class TestReconcileClaudeMd:
    def test_copies_when_different(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_identical(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_copies_when_dest_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "new content"

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_claude_md(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new content")
        (dest_dir / "CLAUDE.md").write_text("old content")

        changed = reconcile_claude_md(src_dir, dest_dir, dryrun=True)

        assert changed is True
        assert (dest_dir / "CLAUDE.md").read_text() == "old content"

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "CLAUDE.md").write_text("content")

        reconcile_claude_md(src_dir, dest_dir)

        assert dest_dir.exists()
        assert (dest_dir / "CLAUDE.md").read_text() == "content"


class TestReconcileSettings:
    def test_merges_into_empty_dest(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        src_data = {
            "permissions": {"allow": ["Bash(ls:*)"]},
            "spinnerTipsEnabled": False,
        }
        (src_dir / "settings.json").write_text(json.dumps(src_data))
        (dest_dir / "settings.json").write_text("{}")

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == src_data

    def test_preserves_dest_only_keys(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))
        (dest_dir / "settings.json").write_text(json.dumps({"model": "opus", "a": 0}))

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["model"] == "opus"
        assert result["a"] == 1

    def test_unions_permission_lists(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(ls:*)", "WebSearch"]}})
        )
        (dest_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Bash(extra:*)", "WebSearch"]}})
        )

        reconcile_settings(src_dir, dest_dir)

        result = json.loads((dest_dir / "settings.json").read_text())
        assert result["permissions"]["allow"] == [
            "Bash(extra:*)",
            "WebSearch",
            "Bash(ls:*)",
        ]

    def test_already_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False

    def test_dryrun_does_not_write(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(json.dumps({"new": True}))
        (dest_dir / "settings.json").write_text(json.dumps({"old": True}))

        changed = reconcile_settings(src_dir, dest_dir, dryrun=True)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"old": True}

    def test_creates_dest_dir_if_missing(self, tmp_path):
        src_dir = tmp_path / "src"
        dest_dir = tmp_path / "dest" / "nested"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))

        reconcile_settings(src_dir, dest_dir)

        assert dest_dir.exists()
        result = json.loads((dest_dir / "settings.json").read_text())
        assert result == {"a": 1}

    def test_skips_when_src_missing(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is False


class TestReconcileScripts:
    def test_copies_scripts(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "foo.py").write_text("print(1)")
        (scripts_dir / "bar.py").write_text("print(2)")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is True
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        assert (dest_scripts / "foo.py").read_text() == "print(1)"
        assert (dest_scripts / "bar.py").read_text() == "print(2)"

    def test_skips_identical_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        dest_scripts.mkdir(parents=True)
        (scripts_dir / "same.py").write_text("same")
        (dest_scripts / "same.py").write_text("same")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is False

    def test_overwrites_changed_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        dest_scripts.mkdir(parents=True)
        (scripts_dir / "mod.py").write_text("new")
        (dest_scripts / "mod.py").write_text("old")

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is True
        assert (dest_scripts / "mod.py").read_text() == "new"

    def test_dryrun_does_not_write(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "new.py").write_text("content")

        changed = reconcile_scripts(repo_dir, dest_dir, dryrun=True)

        assert changed is True
        assert not (dest_dir / "my-claude-stuff" / "scripts" / "new.py").exists()

    def test_missing_scripts_dir(self, tmp_path):
        repo_dir = tmp_path / "repo"
        repo_dir.mkdir()
        dest_dir = tmp_path / "dest"
        dest_dir.mkdir()

        changed = reconcile_scripts(repo_dir, dest_dir)

        assert changed is False

    def test_only_copies_py_files(self, tmp_path):
        repo_dir = tmp_path / "repo"
        dest_dir = tmp_path / "dest"
        scripts_dir = repo_dir / "scripts"
        scripts_dir.mkdir(parents=True)
        dest_dir.mkdir()
        (scripts_dir / "good.py").write_text("ok")
        (scripts_dir / "notes.txt").write_text("skip me")

        reconcile_scripts(repo_dir, dest_dir)

        dest_scripts = dest_dir / "my-claude-stuff" / "scripts"
        assert (dest_scripts / "good.py").exists()
        assert not (dest_scripts / "notes.txt").exists()


class TestMain:
    def test_returns_error_when_src_missing(self, tmp_path):
        result = main([str(tmp_path / "nonexistent"), str(tmp_path / "dest")])
        assert result == EXIT_ERROR

    def test_returns_success_when_in_sync(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        result = main([str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS

    def test_dryrun_does_not_modify(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("new")
        (dest_dir / "CLAUDE.md").write_text("old")

        result = main(["--dryrun", str(src_dir), str(dest_dir)])

        assert result == EXIT_SUCCESS
        assert (dest_dir / "CLAUDE.md").read_text() == "old"

    def test_quiet_suppresses_output(self, src_dest_dirs, capsys):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "CLAUDE.md").write_text("same")
        (dest_dir / "CLAUDE.md").write_text("same")
        data = json.dumps({"key": "value"})
        (src_dir / "settings.json").write_text(data)
        (dest_dir / "settings.json").write_text(data)

        main(["--quiet", str(src_dir), str(dest_dir)])

        captured = capsys.readouterr()
        assert captured.out == ""


class TestLoadSettingsWithFragments:
    def test_fragments_merged_alphabetically(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "01-first.json").write_text(json.dumps({"b": 2}))
        (d_dir / "02-second.json").write_text(json.dumps({"c": 3}))

        result = load_settings_with_fragments(src_dir)

        assert result == {"a": 1, "b": 2, "c": 3}

    def test_fragment_lists_union_with_base(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["A", "B"]}})
        )
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "extra.json").write_text(
            json.dumps({"permissions": {"allow": ["B", "C"]}})
        )

        result = load_settings_with_fragments(src_dir)

        assert result["permissions"]["allow"] == ["A", "B", "C"]

    def test_multiple_fragments_accumulate(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["A"]}})
        )
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "01.json").write_text(json.dumps({"permissions": {"allow": ["B"]}}))
        (d_dir / "02.json").write_text(json.dumps({"permissions": {"allow": ["C"]}}))

        result = load_settings_with_fragments(src_dir)

        assert result["permissions"]["allow"] == ["A", "B", "C"]

    def test_empty_d_directory(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        base = {"key": "value"}
        (src_dir / "settings.json").write_text(json.dumps(base))
        (src_dir / "settings.json.d").mkdir()

        result = load_settings_with_fragments(src_dir)

        assert result == base

    def test_missing_d_directory(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        base = {"key": "value"}
        (src_dir / "settings.json").write_text(json.dumps(base))

        result = load_settings_with_fragments(src_dir)

        assert result == base

    def test_non_json_files_ignored(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"a": 1}))
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "notes.txt").write_text("not json")
        (d_dir / "README.md").write_text("also not json")
        (d_dir / "real.json").write_text(json.dumps({"b": 2}))

        result = load_settings_with_fragments(src_dir)

        assert result == {"a": 1, "b": 2}

    def test_fragment_with_non_permission_keys(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(
            json.dumps({"spinnerTipsEnabled": False})
        )
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "ui.json").write_text(
            json.dumps({"spinnerTipsEnabled": True, "theme": "dark"})
        )

        result = load_settings_with_fragments(src_dir)

        assert result["spinnerTipsEnabled"] is True
        assert result["theme"] == "dark"

    def test_scalar_merge_order_last_wins(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        (src_dir / "settings.json").write_text(json.dumps({"x": 0}))
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "aaa.json").write_text(json.dumps({"x": 1}))
        (d_dir / "zzz.json").write_text(json.dumps({"x": 2}))

        result = load_settings_with_fragments(src_dir)

        assert result["x"] == 2

    def test_missing_base_and_no_d_dir_returns_empty(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()

        result = load_settings_with_fragments(src_dir)

        assert result == {}

    def test_fragments_only_no_base_file(self, tmp_path):
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "a.json").write_text(json.dumps({"x": 1}))
        (d_dir / "b.json").write_text(json.dumps({"permissions": {"allow": ["A"]}}))

        result = load_settings_with_fragments(src_dir)

        assert result["x"] == 1
        assert result["permissions"]["allow"] == ["A"]

    def test_reconcile_with_fragments_only(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "config.json").write_text(
            json.dumps({"permissions": {"allow": ["X"]}})
        )
        (dest_dir / "settings.json").write_text(json.dumps({}))

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert "X" in result["permissions"]["allow"]

    def test_integration_fragments_flow_through_reconcile(self, src_dest_dirs):
        src_dir, dest_dir = src_dest_dirs
        (src_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["A"]}})
        )
        d_dir = src_dir / "settings.json.d"
        d_dir.mkdir()
        (d_dir / "extra.json").write_text(json.dumps({"permissions": {"allow": ["B"]}}))
        (dest_dir / "settings.json").write_text(
            json.dumps({"permissions": {"allow": ["Z"]}})
        )

        changed = reconcile_settings(src_dir, dest_dir)

        assert changed is True
        result = json.loads((dest_dir / "settings.json").read_text())
        assert "Z" in result["permissions"]["allow"]
        assert "A" in result["permissions"]["allow"]
        assert "B" in result["permissions"]["allow"]


class TestConfTestGuard:
    """Verify the conftest guard blocks all I/O to protected paths.

    Every guard must block both ~/.claude and ~/.config/claude,
    and must fail closed (block on error, never allow through).
    """

    # --- write_text ---

    def test_write_text_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    def test_write_text_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    def test_write_text_blocked_nested_subdir(self):
        path = pathlib.Path.home() / ".claude" / "deep" / "nested" / "f.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.write_text("blocked")

    # --- read_text ---

    def test_read_text_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.read_text()

    def test_read_text_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            path.read_text()

    # --- shutil.copy2 ---

    def test_copy2_blocked(self, tmp_path):
        import shutil

        src = tmp_path / "src.txt"
        src.write_text("canary")
        dest = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            shutil.copy2(src, dest)

    # --- builtins.open ---

    def test_open_write_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "w")

    def test_open_read_blocked_claude_dir(self):
        path = pathlib.Path.home() / ".claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "r")

    def test_open_blocked_config_claude_dir(self):
        path = pathlib.Path.home() / ".config" / "claude" / "canary.txt"
        with pytest.raises(PermissionError, match="protected path"):
            open(path, "r")

    # --- tmp_path is allowed ---

    def test_write_text_allowed_tmp_path(self, tmp_path):
        path = tmp_path / "ok.txt"
        path.write_text("allowed")
        assert path.read_text() == "allowed"

    def test_open_allowed_tmp_path(self, tmp_path):
        path = tmp_path / "ok.txt"
        with open(path, "w") as fh:
            fh.write("allowed")
        with open(path, "r") as fh:
            assert fh.read() == "allowed"

    # --- fail closed: _is_blocked returns True on error ---

    def test_is_blocked_fails_closed(self, monkeypatch):
        from tests.conftest import _is_blocked

        # Force resolve() to raise, simulating an unresolvable path
        def bad_resolve(self):
            raise OSError("cannot resolve")

        monkeypatch.setattr(pathlib.Path, "resolve", bad_resolve)
        assert _is_blocked(pathlib.Path("/some/random/path")) is True
