#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/memory_sync.py."""

from scripts.memory_sync import diff, sync


class TestSync:
    def test_copies_new_files(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("alpha")
        (src / "b.md").write_text("beta")

        changed = sync(src_dir=src, dest_dir=dest)

        assert changed is True
        assert (dest / "a.md").read_text() == "alpha"
        assert (dest / "b.md").read_text() == "beta"

    def test_overwrites_different_files(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("new")
        (dest / "a.md").write_text("old")

        changed = sync(src_dir=src, dest_dir=dest)

        assert changed is True
        assert (dest / "a.md").read_text() == "new"

    def test_skips_identical_files(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("same")
        (dest / "a.md").write_text("same")

        changed = sync(src_dir=src, dest_dir=dest)

        assert changed is False

    def test_creates_dest_dir(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest" / "nested"
        src.mkdir()
        (src / "a.md").write_text("content")

        sync(src_dir=src, dest_dir=dest)

        assert (dest / "a.md").read_text() == "content"

    def test_ignores_non_md_files(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("keep")
        (src / "notes.txt").write_text("skip")

        sync(src_dir=src, dest_dir=dest)

        assert (dest / "a.md").exists()
        assert not (dest / "notes.txt").exists()

    def test_dryrun_does_not_write(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("content")

        changed = sync(src_dir=src, dest_dir=dest, dryrun=True)

        assert changed is True
        assert not (dest / "a.md").exists()

    def test_empty_src_returns_false(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()

        changed = sync(src_dir=src, dest_dir=dest)

        assert changed is False

    def test_missing_src_dir_returns_false(self, tmp_path):
        dest = tmp_path / "dest"
        dest.mkdir()

        changed = sync(src_dir=tmp_path / "nonexistent", dest_dir=dest)

        assert changed is False

    def test_preserves_dest_only_files(self, tmp_path):
        src = tmp_path / "src"
        dest = tmp_path / "dest"
        src.mkdir()
        dest.mkdir()
        (src / "a.md").write_text("from src")
        (dest / "b.md").write_text("dest only")

        sync(src_dir=src, dest_dir=dest)

        assert (dest / "a.md").read_text() == "from src"
        assert (dest / "b.md").read_text() == "dest only"


class TestDiff:
    def test_reports_repo_only(self, tmp_path, capsys):
        repo = tmp_path / "repo"
        live = tmp_path / "live"
        repo.mkdir()
        live.mkdir()
        (repo / "a.md").write_text("content")

        diff(repo_dir=repo, live_dir=live)

        output = capsys.readouterr().out
        assert "repo only:" in output
        assert "a.md" in output

    def test_reports_live_only(self, tmp_path, capsys):
        repo = tmp_path / "repo"
        live = tmp_path / "live"
        repo.mkdir()
        live.mkdir()
        (live / "b.md").write_text("content")

        diff(repo_dir=repo, live_dir=live)

        output = capsys.readouterr().out
        assert "live only:" in output
        assert "b.md" in output

    def test_reports_different(self, tmp_path, capsys):
        repo = tmp_path / "repo"
        live = tmp_path / "live"
        repo.mkdir()
        live.mkdir()
        (repo / "a.md").write_text("repo version")
        (live / "a.md").write_text("live version")

        diff(repo_dir=repo, live_dir=live)

        output = capsys.readouterr().out
        assert "different:" in output
        assert "a.md" in output

    def test_reports_in_sync(self, tmp_path, capsys):
        repo = tmp_path / "repo"
        live = tmp_path / "live"
        repo.mkdir()
        live.mkdir()
        (repo / "a.md").write_text("same")
        (live / "a.md").write_text("same")

        diff(repo_dir=repo, live_dir=live)

        output = capsys.readouterr().out
        assert "In sync" in output

    def test_both_empty(self, tmp_path, capsys):
        repo = tmp_path / "repo"
        live = tmp_path / "live"
        repo.mkdir()
        live.mkdir()

        diff(repo_dir=repo, live_dir=live)

        output = capsys.readouterr().out
        assert "empty" in output

    def test_missing_dirs(self, tmp_path, capsys):
        diff(repo_dir=tmp_path / "nope1", live_dir=tmp_path / "nope2")

        output = capsys.readouterr().out
        assert "empty" in output
