#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for scripts/backfill_prior_cost.py."""

import json
from datetime import date
from unittest import mock

from scripts.backfill_prior_cost import main
from scripts.session_tracker import SESSION_FILE_SUFFIX


class TestMain:
    def test_no_today_directory(self, tmp_path, capsys):
        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()
        output = capsys.readouterr().out
        assert "No directory for today" in output

    def test_skips_file_with_prior_cost(self, tmp_path, capsys):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()
        session = today_dir / f"sess-1{SESSION_FILE_SUFFIX}"
        session.write_text(json.dumps({"session_id": "sess-1", "_prior_cost": 5.0}))

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()
        output = capsys.readouterr().out
        assert "0 fixed, 1 skipped" in output

    def test_fixes_file_with_prior_cost_found(self, tmp_path, capsys):
        # Create a prior day with cost data
        prior_dir = tmp_path / "2020-01-01"
        prior_dir.mkdir()
        (prior_dir / f"sess-1{SESSION_FILE_SUFFIX}").write_text(
            json.dumps({"session_id": "sess-1", "cost": {"total_cost_usd": 3.00}})
        )

        # Create today's file without _prior_cost
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()
        session = today_dir / f"sess-1{SESSION_FILE_SUFFIX}"
        session.write_text(
            json.dumps({"session_id": "sess-1", "cost": {"total_cost_usd": 5.00}})
        )

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()

        output = capsys.readouterr().out
        assert "1 fixed, 0 skipped" in output
        assert "prior=$3.0000" in output

        saved = json.loads(session.read_text())
        assert saved["_prior_cost"] == 3.00

    def test_skips_file_with_zero_prior(self, tmp_path, capsys):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()
        session = today_dir / f"sess-1{SESSION_FILE_SUFFIX}"
        session.write_text(
            json.dumps({"session_id": "sess-1", "cost": {"total_cost_usd": 2.00}})
        )

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()

        output = capsys.readouterr().out
        assert "0 fixed, 1 skipped" in output

    def test_skips_malformed_json(self, tmp_path, capsys):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()
        bad = today_dir / f"bad{SESSION_FILE_SUFFIX}"
        bad.write_text("not json{{{")

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()

        output = capsys.readouterr().out
        assert "0 fixed, 0 skipped" in output

    def test_skips_non_json_files(self, tmp_path, capsys):
        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()
        (today_dir / "notes.txt").write_text("not a session")

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()

        output = capsys.readouterr().out
        assert "0 fixed, 0 skipped" in output

    def test_mixed_scenario(self, tmp_path, capsys):
        # Prior day data
        prior_dir = tmp_path / "2020-01-01"
        prior_dir.mkdir()
        (prior_dir / f"fixable{SESSION_FILE_SUFFIX}").write_text(
            json.dumps({"session_id": "fixable", "cost": {"total_cost_usd": 2.00}})
        )

        today_dir = tmp_path / date.today().isoformat()
        today_dir.mkdir()

        # File that already has _prior_cost (skipped)
        (today_dir / f"has-prior{SESSION_FILE_SUFFIX}").write_text(
            json.dumps({"session_id": "has-prior", "_prior_cost": 1.0})
        )
        # File that will be fixed (prior > 0)
        (today_dir / f"fixable{SESSION_FILE_SUFFIX}").write_text(
            json.dumps({"session_id": "fixable", "cost": {"total_cost_usd": 5.00}})
        )
        # File with no prior (skipped)
        (today_dir / f"no-prior{SESSION_FILE_SUFFIX}").write_text(
            json.dumps({"session_id": "no-prior", "cost": {"total_cost_usd": 1.00}})
        )
        # Malformed JSON (skipped via continue)
        (today_dir / f"corrupt{SESSION_FILE_SUFFIX}").write_text("{bad")
        # Non-JSON file (skipped via suffix check)
        (today_dir / "readme.txt").write_text("ignore me")

        with mock.patch("scripts.backfill_prior_cost.BASE_DIR", tmp_path):
            main()

        output = capsys.readouterr().out
        assert "1 fixed, 2 skipped" in output
