#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Tests for statusline.py.

All file I/O is redirected to tmp_path. No real credentials or
config files are ever read.
"""

import io
import json
import re
import time

from scripts import statusline

# Far-future epoch seconds so format_remaining yields a positive duration in
# tests that don't care about the exact value.
_FAR_FUTURE = 4102444800.0  # 2100-01-01 UTC

SAMPLE_STDIN = {
    "model": {"display_name": "Opus 4.6"},
    "context_window": {"used_percentage": 12},
}


# --- _configure_logging ---


class TestConfigureLogging:
    def test_oserror_handled_silently(self, monkeypatch):
        # Reset the flag so _configure_logging runs again
        monkeypatch.setattr(statusline, "_log_configured", False)
        monkeypatch.setattr(
            statusline.LOG_DIR.__class__,
            "mkdir",
            lambda *a, **kw: (_ for _ in ()).throw(OSError("no perms")),
        )
        statusline._configure_logging()  # should not raise


# --- format_duration ---


class TestFormatDuration:
    def test_zero(self):
        assert statusline.format_duration(0) == "0s"

    def test_negative_clamps(self):
        assert statusline.format_duration(-5) == "0s"

    def test_seconds_only(self):
        assert statusline.format_duration(45) == "45s"

    def test_minutes_seconds(self):
        assert statusline.format_duration(90) == "1m30s"

    def test_minutes_exact(self):
        assert statusline.format_duration(120) == "2m"

    def test_hours_minutes(self):
        assert statusline.format_duration(3720) == "1h2m"

    def test_hours_exact(self):
        assert statusline.format_duration(7200) == "2h"

    def test_days_hours(self):
        assert statusline.format_duration(90000) == "1d1h"

    def test_days_exact(self):
        assert statusline.format_duration(86400) == "1d"

    def test_days_no_minutes(self):
        # 2 days 0 hours — should be just "2d", not "2d0h"
        assert statusline.format_duration(172800) == "2d"

    def test_multi_day(self):
        # 4 days 12 hours
        assert statusline.format_duration(4 * 86400 + 12 * 3600) == "4d12h"

    def test_never_three_units(self):
        # 1d 2h 30m 15s — should be "1d2h", not "1d2h30m"
        assert statusline.format_duration(86400 + 7200 + 1800 + 15) == "1d2h"


# --- format_remaining ---


class TestFormatRemaining:
    def test_none_input(self):
        assert statusline.format_remaining(None) is None

    def test_invalid_type(self):
        assert statusline.format_remaining("not-a-number") is None

    def test_past_returns_zero(self):
        # Year 2000 — far in the past
        assert statusline.format_remaining(946684800.0) == "0s"

    def test_zero_returns_zero(self):
        # Treated as past relative to "now"
        assert statusline.format_remaining(0) == "0s"

    def test_future_timestamp(self):
        future = time.time() + 3 * 3600 + 4 * 60
        result = statusline.format_remaining(future)
        assert result.startswith("3h")

    def test_days_remaining(self):
        future = time.time() + 4 * 86400 + 12 * 3600
        result = statusline.format_remaining(future)
        assert result.startswith("4d")


# --- main ---


class TestMain:
    def _run_main(self, monkeypatch, capsys, stdin_data):
        monkeypatch.setattr(
            "sys.stdin",
            io.StringIO(json.dumps(stdin_data)),
        )
        statusline.main()
        raw = capsys.readouterr().out.strip()
        return re.sub(r"\033\[[0-9;]*m", "", raw)

    def test_invalid_stdin(self, monkeypatch, capsys):
        monkeypatch.setattr("sys.stdin", io.StringIO("not json"))
        statusline.main()
        assert capsys.readouterr().out.strip() == "Claude Code"

    def test_basic_output(self, monkeypatch, capsys):
        output = self._run_main(monkeypatch, capsys, SAMPLE_STDIN)
        assert "Opus 4.6" in output
        assert "Context: 12%" in output

    def test_no_context_window(self, monkeypatch, capsys):
        data = {"model": {"display_name": "Sonnet"}}
        output = self._run_main(monkeypatch, capsys, data)
        assert "Context:" not in output
        assert "Sonnet" in output

    def test_default_model(self, monkeypatch, capsys):
        output = self._run_main(monkeypatch, capsys, {})
        assert "Claude" in output

    def test_cost_display(self, monkeypatch, capsys, tmp_path):
        data = {
            **SAMPLE_STDIN,
            "cost": {"total_cost_usd": 1.50},
            "session_id": "test-session",
            "workspace": {"project_dir": str(tmp_path)},
        }
        monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(data)))

        import types

        mock_tracker = types.ModuleType("session_tracker")
        mock_tracker.track_session = lambda data: None
        mock_tracker.get_daily_cost = lambda: 5.25
        mock_tracker.get_project_cost = lambda project_dir: 42.00
        monkeypatch.setitem(
            __import__("sys").modules,
            "scripts.session_tracker",
            mock_tracker,
        )

        statusline.main()
        raw = capsys.readouterr().out.strip()
        output = re.sub(r"\033\[[0-9;]*m", "", raw)
        assert "S/T/P: $1.50 / $5.25 / $42.00" in output

    def test_no_cost_shows_zero(self, monkeypatch, capsys):
        monkeypatch.setattr(
            "sys.stdin",
            io.StringIO(json.dumps(SAMPLE_STDIN)),
        )

        import types

        mock_tracker = types.ModuleType("session_tracker")
        mock_tracker.track_session = lambda data: None
        mock_tracker.get_daily_cost = lambda: 0.0
        mock_tracker.get_project_cost = lambda project_dir: 0.0
        monkeypatch.setitem(
            __import__("sys").modules,
            "scripts.session_tracker",
            mock_tracker,
        )

        statusline.main()
        raw = capsys.readouterr().out.strip()
        output = re.sub(r"\033\[[0-9;]*m", "", raw)
        assert "S/T/P: $0.00" in output

    def test_project_cost_displayed(self, monkeypatch, capsys, tmp_path):
        data = {
            **SAMPLE_STDIN,
            "cost": {"total_cost_usd": 0.50},
            "session_id": "s1",
            "workspace": {"project_dir": str(tmp_path)},
        }
        monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(data)))

        import types

        mock_tracker = types.ModuleType("session_tracker")
        mock_tracker.track_session = lambda data: None
        mock_tracker.get_daily_cost = lambda: 1.00
        mock_tracker.get_project_cost = lambda project_dir: 245.00
        monkeypatch.setitem(
            __import__("sys").modules,
            "scripts.session_tracker",
            mock_tracker,
        )

        statusline.main()
        raw = capsys.readouterr().out.strip()
        output = re.sub(r"\033\[[0-9;]*m", "", raw)
        assert "S/T/P: $0.50 / $1.00 / $245.00" in output
