#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""One-time backfill: add _prior_cost to today's session files.

Sessions written before the _prior_cost feature was added don't have
the field. This script finds today's sessions that also exist in a
prior day's directory and writes the prior cost into them.

Safe to run multiple times — skips files that already have _prior_cost.
"""

import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.config import DATA_DIR  # noqa: E402
from scripts.session_tracker import SESSION_FILE_SUFFIX, _find_prior_cost  # noqa: E402

BASE_DIR = DATA_DIR / "session-tracker"


def main() -> None:
    today_str = date.today().isoformat()
    today_dir = BASE_DIR / today_str
    if not today_dir.is_dir():
        print(f"No directory for today ({today_str})")
        return

    fixed = 0
    skipped = 0
    for session_file in today_dir.iterdir():
        if session_file.suffix != SESSION_FILE_SUFFIX:
            continue
        try:
            with open(session_file, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except (json.JSONDecodeError, OSError):
            continue

        if "_prior_cost" in data:
            skipped += 1
            continue

        prior = _find_prior_cost(session_file.name, today_str, BASE_DIR)
        if prior > 0.0:
            data["_prior_cost"] = prior
            with open(session_file, "w", encoding="utf-8") as fh:
                json.dump(data, fh)
            print(f"  {session_file.name}: prior=${prior:.4f}")
            fixed += 1
        else:
            skipped += 1

    print(f"Done: {fixed} fixed, {skipped} skipped")


if __name__ == "__main__":
    main()
