#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""PreToolUse hook that blocks restricted commands.

Reads JSON from stdin with tool_input.command and checks against blocked
command patterns. Exits 2 to block, 0 to allow.

Blocked commands:
  - git add
  - git push
  - git reset
  - git clean
  - git branch
  - git stash
  - sudo
  - su (standalone, not as substring)
  - rm with recursive flags (-r, -R, --recursive)
  - make reconcile
  - git commit with --amend or -a flag
"""

import json
import re
import sys

# Optional path prefix: /usr/bin/, /usr/local/bin/, ./bin/, env, etc.
_PATH = r"(?:[a-zA-Z0-9_./-]*/)?"
_ENV = r"(?:\benv\s+(?:-\S+\s+)*)?"
# Optional flags between command and subcommand (e.g. git -C /path, make -f file)
_FLAGS = r"(?:\s+(?:-\S+|\S+=\S+)(?:\s+\S+)?)*"

BLOCKED_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+add\b"), "git add"),
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+push\b"), "git push"),
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+reset\b"), "git reset"),
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+clean\b"), "git clean"),
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+branch\b"), "git branch"),
    (re.compile(rf"{_ENV}{_PATH}git{_FLAGS}\s+stash\b"), "git stash"),
    (re.compile(rf"{_ENV}{_PATH}sudo\b"), "sudo"),
    (
        re.compile(rf"(?:^|&&|\|\||;|\|)\s*{_ENV}{_PATH}su\s*(?:$|\s|&&|\|\||;|\|)"),
        "su",
    ),
    (
        re.compile(rf"{_ENV}{_PATH}rm\s+.*(-[a-zA-Z]*[rR][a-zA-Z]*|--recursive)\b"),
        "rm (recursive)",
    ),
    (re.compile(rf"{_ENV}{_PATH}make{_FLAGS}\s+reconcile\b"), "make reconcile"),
    (
        re.compile(
            rf"{_ENV}{_PATH}git{_FLAGS}\s+commit\s.*(?:--amend\b|(?<=\s)-[a-zA-Z]*a[a-zA-Z]*)(?:\s|$)"
        ),
        "git commit (--amend/-a)",
    ),
]


def check_command(command: str) -> str | None:
    """Return the blocked command name if matched, or None if allowed.

    Only checks the command portion before any heredoc (<<) to avoid
    false positives from blocked words appearing in string literals.
    """
    # Strip heredoc body and quoted strings to avoid false positives
    check_text = command.split("<<")[0] if "<<" in command else command
    for pattern, name in BLOCKED_PATTERNS:
        if pattern.search(check_text):
            return name
    return None


def main() -> None:
    """Read tool input from stdin and block restricted commands."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    tool_input = data.get("tool_input", {})
    if isinstance(tool_input, dict):
        command = tool_input.get("command", "")
    else:
        command = data.get("command", "")
    if not command:
        return

    blocked = check_command(command)
    if blocked:
        print(f"BLOCKED: {blocked} is not allowed", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
