#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""PreToolUse hook that blocks restricted commands.

Reads JSON from stdin with tool_input.command and checks against blocked
command patterns. Exits 2 to block, 0 to allow.

Blocked commands:
  - git add
  - git push
  - sudo
  - su (standalone, not as substring)
  - make reconcile
"""

import json
import re
import sys

BLOCKED_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\bgit\s+add\b"), "git add"),
    (re.compile(r"\bgit\s+push\b"), "git push"),
    (re.compile(r"\bsudo\b"), "sudo"),
    (re.compile(r"(?:^|&&|\|\||;|\|)\s*su\s*(?:$|\s|&&|\|\||;|\|)"), "su"),
    (re.compile(r"\bmake\s+reconcile\b"), "make reconcile"),
]


def check_command(command: str) -> str | None:
    """Return the blocked command name if matched, or None if allowed."""
    for pattern, name in BLOCKED_PATTERNS:
        if pattern.search(command):
            return name
    return None


def main() -> None:
    """Read tool input from stdin and block restricted commands."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    tool_input = data.get("tool_input", {})
    if isinstance(tool_input, dict):
        command = tool_input.get("command", "")
    else:
        command = data.get("command", "")
    if not command:
        return

    blocked = check_command(command)
    if blocked:
        print(f"BLOCKED: {blocked} is not allowed", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
