#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Shared constants for my-claude-stuff scripts."""

from pathlib import Path

# Root data directory for all script artifacts
DATA_DIR = Path.home() / ".claude" / "my-claude-stuff-data"

# ANSI color codes
ANSI_RED = "\033[31m"
ANSI_YELLOW = "\033[33m"
ANSI_GREEN = "\033[32m"
ANSI_ORANGE = "\033[38;5;208m"
ANSI_PURPLE = "\033[38;5;141m"
ANSI_RESET = "\033[0m"

# Color threshold breakpoints (fraction, 0.0-1.0)
THRESHOLD_MID = 0.6
THRESHOLD_HIGH = 0.9
