#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Bidirectional sync for Claude Code global memory files.

Provides pull, push, and diff operations between the repo copy
(claude/memory/) and the live copy (~/.claude/memory/).

Usage:
  memory_sync.py pull [--dryrun]   # ~/.claude/memory/ -> claude/memory/
  memory_sync.py push [--dryrun]   # claude/memory/ -> ~/.claude/memory/
  memory_sync.py diff              # show differences
"""

import argparse
import shutil
import sys
from pathlib import Path

GLOB_PATTERN = "*.md"


def _list_files(directory: Path) -> dict[str, Path]:
    """Return {filename: path} for all .md files in directory."""
    if not directory.is_dir():
        return {}
    return {f.name: f for f in sorted(directory.glob(GLOB_PATTERN))}


def sync(
    *,
    src_dir: Path,
    dest_dir: Path,
    dryrun: bool = False,
) -> bool:
    """Copy .md files from src to dest. Returns True if anything changed."""
    src_files = _list_files(src_dir)
    dest_files = _list_files(dest_dir)

    if not src_files:
        print(f"No .md files in {src_dir}")
        return False

    changed = False
    for name, src_path in src_files.items():
        dest_path = dest_dir / name
        src_text = src_path.read_text(encoding="utf-8")

        if name in dest_files:
            dest_text = dest_files[name].read_text(encoding="utf-8")
            if src_text == dest_text:
                continue
            action = "update"
        else:
            action = "add"

        changed = True
        if dryrun:
            print(f"  Would {action}: {name}")
        else:
            dest_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dest_path)
            print(f"  {action.capitalize()}d: {name}")

    if not changed:
        print("  Already in sync.")

    return changed


def diff(*, repo_dir: Path, live_dir: Path) -> None:
    """Show differences between repo and live memory directories."""
    repo_files = _list_files(repo_dir)
    live_files = _list_files(live_dir)
    all_names = sorted(set(repo_files) | set(live_files))

    if not all_names:
        print("Both directories are empty.")
        return

    has_diff = False
    for name in all_names:
        in_repo = name in repo_files
        in_live = name in live_files

        if in_repo and not in_live:
            print(f"  repo only:  {name}")
            has_diff = True
        elif in_live and not in_repo:
            print(f"  live only:  {name}")
            has_diff = True
        else:
            repo_text = repo_files[name].read_text(encoding="utf-8")
            live_text = live_files[name].read_text(encoding="utf-8")
            if repo_text != live_text:
                print(f"  different:  {name}")
                has_diff = True

    if not has_diff:
        print("  In sync.")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="sync Claude Code global memory files")
    parser.add_argument(
        "action",
        choices=["pull", "push", "diff"],
        help="pull (live->repo), push (repo->live), or diff",
    )
    parser.add_argument(
        "--repo-dir",
        type=Path,
        default=None,
        help="repo memory dir (default: claude/memory/ relative to script)",
    )
    parser.add_argument(
        "--live-dir",
        type=Path,
        default=None,
        help="live memory dir (default: ~/.claude/memory/)",
    )
    parser.add_argument(
        "--dryrun", action="store_true", help="preview changes without writing"
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    if args.repo_dir is None:
        args.repo_dir = Path(__file__).resolve().parent.parent / "claude" / "memory"
    if args.live_dir is None:
        args.live_dir = Path.home() / ".claude" / "memory"

    if args.action == "diff":
        print(f"Comparing: {args.repo_dir} <-> {args.live_dir}")
        diff(repo_dir=args.repo_dir, live_dir=args.live_dir)

    elif args.action == "pull":
        print(f"Pull: {args.live_dir} -> {args.repo_dir}")
        sync(src_dir=args.live_dir, dest_dir=args.repo_dir, dryrun=args.dryrun)

    elif args.action == "push":
        print(f"Push: {args.repo_dir} -> {args.live_dir}")
        sync(src_dir=args.repo_dir, dest_dir=args.live_dir, dryrun=args.dryrun)

    return 0


if __name__ == "__main__":
    sys.exit(main())
