#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code hook notification script.

Reads JSON from stdin (Claude Code hook context), determines event type,
and sends a desktop notification for actionable events only:
  - permission_prompt: approval needed
  - elicitation_dialog: input needed
  - Stop: task complete

Non-actionable events (idle_prompt, auth_success) are silently ignored.
Platform-aware: Linux uses notify-send, Windows is stubbed for future.
"""

import json
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass


@dataclass
class Notification:
    title: str
    body: str
    urgency: str  # "low", "normal", "critical"
    cwd: str = ""


ACTIONABLE_NOTIFICATION_TYPES = {
    "permission_prompt": Notification(
        title="Approval Needed",
        body="Claude Code is waiting for your approval.",
        urgency="critical",
    ),
    "elicitation_dialog": Notification(
        title="Input Needed",
        body="Claude Code is waiting for your response.",
        urgency="critical",
    ),
}


def parse_hook_input(data: dict) -> Notification | None:
    """Parse hook JSON and return a Notification, or None if not actionable."""
    event = data.get("hook_event_name", "")

    cwd = data.get("cwd", "")

    if event == "Notification":
        notification_type = data.get("notification_type", "")
        template = ACTIONABLE_NOTIFICATION_TYPES.get(notification_type)
        if template is None:
            return None
        message = data.get("message", "")
        body = message if message else template.body
        return Notification(
            title=template.title, body=body, urgency=template.urgency, cwd=cwd
        )

    if event == "Stop":
        return Notification(
            title="Task Complete",
            body="Claude Code has finished responding.",
            urgency="normal",
            cwd=cwd,
        )

    return None


def detect_platform() -> str:
    """Detect runtime platform: 'linux', 'windows', or 'unknown'."""
    if sys.platform == "win32":
        return "windows"
    if sys.platform.startswith("linux"):
        try:
            with open("/proc/version") as f:
                if "microsoft" in f.read().lower():
                    return "windows"
        except OSError:
            pass
        return "linux"
    return "unknown"


def _shell_join(args: list[str]) -> str:
    """Join command args into a shell-safe string using shlex.quote."""
    return " ".join(shlex.quote(a) for a in args)


def _build_notify_cmd(notification: Notification) -> list[str]:
    """Build the notify-send command list."""
    cmd = [
        "notify-send",
        "--urgency",
        notification.urgency,
    ]
    if notification.cwd:
        cmd += ["--action", "focus=Focus"]
        cmd.append("--wait")
    cmd += [notification.title, notification.body]
    return cmd


def send_linux(notification: Notification) -> None:
    """Send notification via notify-send.

    When cwd is set, spawns a detached background process that waits for the
    user to click the "Focus" action, then opens VS Code at that workspace.
    """
    cmd = _build_notify_cmd(notification)

    if not notification.cwd:
        subprocess.run(cmd, check=False)
        return

    code_bin = shutil.which("code") or "code"
    # Spawn detached process: notify-send --wait prints action key on click,
    # then we open VS Code at the workspace to focus the window.
    wrapper_script = (
        f"action=$({_shell_join(cmd)}) && "
        f'[ "$action" = "focus" ] && '
        f"exec {_shell_join([code_bin, notification.cwd])}"
    )
    subprocess.Popen(
        ["bash", "-c", wrapper_script],
        start_new_session=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def send_windows(notification: Notification) -> None:
    """Send notification on Windows. Not yet implemented."""
    raise NotImplementedError("Windows notifications not yet implemented")


SENDERS = {
    "linux": send_linux,
    "windows": send_windows,
}


def main() -> None:
    """Read hook JSON from stdin, parse, detect platform, and notify."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    notification = parse_hook_input(data)
    if notification is None:
        return

    platform = detect_platform()
    sender = SENDERS.get(platform)
    if sender is None:
        return

    try:
        sender(notification)
    except (NotImplementedError, OSError):
        return


if __name__ == "__main__":
    main()
