#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code hook notification script.

Reads JSON from stdin (Claude Code hook context), determines event type,
and sends a desktop notification for actionable events only:
  - permission_prompt: approval needed
  - elicitation_dialog: input needed
  - Stop: task complete

Non-actionable events (idle_prompt, auth_success) are silently ignored.
Platform-aware: Linux uses notify-send, Windows is stubbed for future.
"""

import json
import subprocess
import sys
from dataclasses import dataclass


@dataclass
class Notification:
    title: str
    body: str
    urgency: str  # "low", "normal", "critical"


ACTIONABLE_NOTIFICATION_TYPES = {
    "permission_prompt": Notification(
        title="Approval Needed",
        body="Claude Code is waiting for your approval.",
        urgency="critical",
    ),
    "elicitation_dialog": Notification(
        title="Input Needed",
        body="Claude Code is waiting for your response.",
        urgency="critical",
    ),
}


def parse_hook_input(data: dict) -> Notification | None:
    """Parse hook JSON and return a Notification, or None if not actionable."""
    event = data.get("hook_event_name", "")

    if event == "Notification":
        notification_type = data.get("notification_type", "")
        template = ACTIONABLE_NOTIFICATION_TYPES.get(notification_type)
        if template is None:
            return None
        message = data.get("message", "")
        body = message if message else template.body
        return Notification(title=template.title, body=body, urgency=template.urgency)

    if event == "Stop":
        return Notification(
            title="Task Complete",
            body="Claude Code has finished responding.",
            urgency="normal",
        )

    return None


def detect_platform() -> str:
    """Detect runtime platform: 'linux', 'windows', or 'unknown'."""
    if sys.platform == "win32":
        return "windows"
    if sys.platform.startswith("linux"):
        try:
            with open("/proc/version") as f:
                if "microsoft" in f.read().lower():
                    return "windows"
        except OSError:
            pass
        return "linux"
    return "unknown"


def send_linux(notification: Notification) -> None:
    """Send notification via notify-send."""
    subprocess.run(
        [
            "notify-send",
            "--urgency",
            notification.urgency,
            notification.title,
            notification.body,
        ],
        check=False,
    )


def send_windows(notification: Notification) -> None:
    """Send notification on Windows. Not yet implemented."""
    raise NotImplementedError("Windows notifications not yet implemented")


SENDERS = {
    "linux": send_linux,
    "windows": send_windows,
}


def main() -> None:
    """Read hook JSON from stdin, parse, detect platform, and notify."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    notification = parse_hook_input(data)
    if notification is None:
        return

    platform = detect_platform()
    sender = SENDERS.get(platform)
    if sender is None:
        return

    try:
        sender(notification)
    except (NotImplementedError, OSError):
        return


if __name__ == "__main__":
    main()
