#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Hook script to log prompts and responses to JSONL files.

Handles two hook events:
  - UserPromptSubmit: logs the user's prompt with metadata
  - Stop: logs Claude's response with metadata

Each session writes to its own file:
  ~/.claude/prompt-log/{date}/{session_id}.jsonl
No locking needed since each session has its own file and hooks are sequential.
All failures are silently ignored to avoid blocking Claude Code.
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone


def _git_branch(cwd: str) -> str:
    """Get current git branch, or empty string on failure."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=2,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        return ""


def _valid_session_id(session_id: str) -> bool:
    """Validate session_id contains only safe characters."""
    return bool(session_id and re.fullmatch(r"[\w-]+", session_id))


def _extract_entry(data: dict) -> dict | None:
    """Extract a log entry from hook data, or None if not applicable."""
    event = data.get("hook_event_name", "")
    session_id = data.get("session_id", "")

    if not _valid_session_id(session_id):
        return None

    cwd = data.get("cwd", "")
    git_branch = _git_branch(cwd) if cwd else ""
    now = datetime.now(timezone.utc)

    if event == "UserPromptSubmit":
        content = data.get("prompt", "")
        entry_type = "prompt"
    elif event == "Stop":
        content = data.get("last_assistant_message", "")
        entry_type = "response"
    else:
        return None

    return {
        "timestamp": now.isoformat(),
        "event_type": entry_type,
        "session_id": session_id,
        "working_dir": cwd,
        "git_branch": git_branch,
        "content": content,
    }


def _write_entry(entry: dict) -> None:
    """Append a JSONL entry to the session log file."""
    date_str = datetime.fromisoformat(entry["timestamp"]).strftime("%Y-%m-%d")
    log_dir = os.path.join(os.path.expanduser("~"), ".claude", "prompt-log", date_str)
    os.makedirs(log_dir, exist_ok=True)

    log_file = os.path.join(log_dir, f"{entry['session_id']}.jsonl")
    with open(log_file, "a") as f:
        f.write(json.dumps(entry, separators=(",", ":")) + "\n")


def _dump_debug(data: dict) -> None:
    """Dump raw hook data for debugging. Clobbers per-event."""
    try:
        debug_dir = os.path.join(
            os.path.expanduser("~"), ".claude", "prompt-log", "debug"
        )
        os.makedirs(debug_dir, exist_ok=True)
        event = data.get("hook_event_name", "unknown")
        debug_file = os.path.join(debug_dir, f"{event}.json")
        with open(debug_file, "w") as f:
            json.dump(data, f, indent=2, default=str)
    except OSError:
        pass


def main() -> None:
    """Read hook JSON from stdin, extract entry, and write to log."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    _dump_debug(data)

    entry = _extract_entry(data)
    if entry is None:
        return

    try:
        _write_entry(entry)
    except OSError:
        return


if __name__ == "__main__":
    main()
