#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Hook script to log prompts and responses to JSONL files.

Handles three hook events:
  - UserPromptSubmit: logs the user's prompt with metadata
  - Stop: logs Claude's response with metadata
  - PostToolUse (AskUserQuestion): logs questions asked and user's answers

Each session writes to its own file:
  ~/.claude/my-claude-stuff-data/prompt-log/{date}/{session_id}.jsonl
No locking needed since each session has its own file and hooks are sequential.
All failures are silently ignored to avoid blocking Claude Code.
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

from scripts.config import DATA_DIR

PROMPT_LOG_DIR = str(DATA_DIR / "prompt-log")


def _git_branch(cwd: str) -> str:
    """Get current git branch, or empty string on failure."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=2,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        return ""


def _valid_session_id(session_id: str) -> bool:
    """Validate session_id contains only safe characters."""
    return bool(session_id and re.fullmatch(r"[\w-]+", session_id))


def _extract_question_entries(
    data: dict, session_id: str, cwd: str, git_branch: str, now: datetime
) -> list[dict]:
    """Extract question/answer log entries from PostToolUse AskUserQuestion.

    AskUserQuestion tool_input contains:
      - questions: list of {question, header, options, multiSelect}
      - answers: dict mapping question text to selected answer(s)
    Returns one log entry per question.
    """
    tool_input = data.get("tool_input", {})
    if isinstance(tool_input, str):
        try:
            tool_input = json.loads(tool_input)
        except (json.JSONDecodeError, TypeError):
            tool_input = {}

    questions = tool_input.get("questions", [])
    answers = tool_input.get("answers", {})

    entries = []
    for q in questions:
        question_text = q.get("question", "")
        options = q.get("options", [])
        option_entries = [
            {"label": opt.get("label", ""), "description": opt.get("description", "")}
            for opt in options
            if isinstance(opt, dict)
        ]
        answer = answers.get(question_text, "")

        entry: dict = {
            "timestamp": now.isoformat(),
            "event_type": "question",
            "session_id": session_id,
            "working_dir": cwd,
            "git_branch": git_branch,
            "question": question_text,
            "answer": answer,
        }
        if option_entries:
            entry["options"] = option_entries
        entries.append(entry)

    return entries


def _extract_entry(data: dict) -> dict | list[dict] | None:
    """Extract a log entry from hook data, or None if not applicable."""
    event = data.get("hook_event_name", "")
    session_id = data.get("session_id", "")

    if not _valid_session_id(session_id):
        return None

    cwd = data.get("cwd", "")
    git_branch = _git_branch(cwd) if cwd else ""
    now = datetime.now(timezone.utc)

    if event == "UserPromptSubmit":
        content = data.get("prompt", "")
        entry_type = "prompt"
    elif event == "Stop":
        content = data.get("last_assistant_message", "")
        entry_type = "response"
    elif event == "PostToolUse" and data.get("tool_name") == "AskUserQuestion":
        entries = _extract_question_entries(data, session_id, cwd, git_branch, now)
        return entries if entries else None
    else:
        return None

    return {
        "timestamp": now.isoformat(),
        "event_type": entry_type,
        "session_id": session_id,
        "working_dir": cwd,
        "git_branch": git_branch,
        "content": content,
    }


def _write_entry(entry: dict) -> None:
    """Append a JSONL entry to the session log file."""
    date_str = datetime.fromisoformat(entry["timestamp"]).strftime("%Y-%m-%d")
    log_dir = os.path.join(PROMPT_LOG_DIR, date_str)
    os.makedirs(log_dir, exist_ok=True)

    log_file = os.path.join(log_dir, f"{entry['session_id']}.jsonl")
    with open(log_file, "a") as f:
        f.write(json.dumps(entry, separators=(",", ":")) + "\n")


def _dump_debug(data: dict) -> None:
    """Dump raw hook data for debugging. Clobbers per-event."""
    try:
        debug_dir = os.path.join(PROMPT_LOG_DIR, "debug")
        os.makedirs(debug_dir, exist_ok=True)
        event = data.get("hook_event_name", "unknown")
        debug_file = os.path.join(debug_dir, f"{event}.json")
        with open(debug_file, "w") as f:
            json.dump(data, f, indent=2, default=str)
    except OSError:
        pass


def main() -> None:
    """Read hook JSON from stdin, extract entry, and write to log."""
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except (json.JSONDecodeError, OSError):
        return

    _dump_debug(data)

    result = _extract_entry(data)
    if result is None:
        return

    entries = result if isinstance(result, list) else [result]
    try:
        for entry in entries:
            _write_entry(entry)
    except OSError:
        return


if __name__ == "__main__":
    main()
