#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Reconcile Claude Code config from source to destination directory.

Push-only: src -> dest. Source keys win, dest-only keys are preserved.

CLAUDE.md: straight copy.
settings.json.d/*.json: fragments are merged into a single settings.json,
then deep-merged with dest -- lists are unioned, dicts are merged (src wins),
scalars from src overwrite dest.
"""

import argparse
import json
import logging
import platform
import shutil
import sys
from pathlib import Path

EXIT_SUCCESS = 0
EXIT_ERROR = 1

logger = logging.getLogger("reconcile")


def merge_settings(dest_data: dict, src_data: dict) -> dict:
    """Merge src settings on top of dest. Src wins, dest-only keys kept."""
    merged = dict(dest_data)

    for key, src_val in src_data.items():
        dest_val = merged.get(key)

        if isinstance(src_val, dict) and isinstance(dest_val, dict):
            merged[key] = merge_settings(dest_val, src_val)
        elif isinstance(src_val, list) and isinstance(dest_val, list):
            seen = set()
            unioned = []
            for item in dest_val + src_val:
                item_key = (
                    json.dumps(item, sort_keys=True)
                    if isinstance(item, (dict, list))
                    else item
                )
                if item_key not in seen:
                    seen.add(item_key)
                    unioned.append(item)
            merged[key] = unioned
        else:
            merged[key] = src_val

    return merged


def load_settings_with_fragments(src_dir: Path) -> dict:
    """Load settings.json and merge any settings.json.d/*.json fragments.

    Either settings.json, settings.json.d/, or both may exist.
    Returns empty dict only when neither is present.
    """
    base_path = src_dir / "settings.json"
    d_dir = src_dir / "settings.json.d"

    data: dict = {}
    if base_path.exists():
        data = json.loads(base_path.read_text(encoding="utf-8"))

    if d_dir.is_dir():
        for fragment_path in sorted(d_dir.glob("*.json"), key=lambda p: p.name):
            fragment = json.loads(fragment_path.read_text(encoding="utf-8"))
            data = merge_settings(data, fragment)
            logger.debug("merged fragment: %s", fragment_path.name)

    return data


def reconcile_claude_md(
    src_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    src = src_dir / "CLAUDE.md"
    dest = dest_dir / "CLAUDE.md"

    if not src.exists():
        logger.warning(f"source does not exist: {src}")
        return False

    if dest.exists() and src.read_text(encoding="utf-8") == dest.read_text(
        encoding="utf-8"
    ):
        logger.info("CLAUDE.md already in sync")
        return False

    if dryrun:
        print(f"Would copy: {src} -> {dest}")
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        if not quiet:
            print(f"Copied: {src} -> {dest}")
    return True


def _adapt_python_command(command: str) -> str:
    """Replace 'python3 ' with platform-appropriate bootstrap command.

    Source settings.json uses 'python3' (works on Linux/macOS).
    On Windows, 'python3' is a Microsoft Store stub; 'py -3' is correct.
    """
    if platform.system() != "Windows":
        return command
    if command.startswith("python3 "):
        return "py -3 " + command[len("python3 ") :]
    return command


def _adapt_hooks(settings: dict) -> dict:
    """Adapt hook and statusLine commands for the current platform."""
    settings = dict(settings)

    # Adapt hook commands
    hooks = settings.get("hooks")
    if isinstance(hooks, dict):
        adapted_hooks = {}
        for event, hook_list in hooks.items():
            adapted_list = []
            for entry in hook_list:
                entry = dict(entry)
                inner_hooks = entry.get("hooks", [])
                adapted_inner = []
                for hook in inner_hooks:
                    hook = dict(hook)
                    if "command" in hook:
                        hook["command"] = _adapt_python_command(hook["command"])
                    adapted_inner.append(hook)
                entry["hooks"] = adapted_inner
                adapted_list.append(entry)
            adapted_hooks[event] = adapted_list
        settings["hooks"] = adapted_hooks

    # Adapt statusLine command
    status_line = settings.get("statusLine")
    if isinstance(status_line, dict) and "command" in status_line:
        status_line = dict(status_line)
        status_line["command"] = _adapt_python_command(status_line["command"])
        settings["statusLine"] = status_line

    return settings


def reconcile_settings(
    src_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    dest = dest_dir / "settings.json"
    has_base = (src_dir / "settings.json").exists()
    has_fragments = (src_dir / "settings.json.d").is_dir()

    if not has_base and not has_fragments:
        logger.warning("no settings.json or settings.json.d/ in %s", src_dir)
        return False

    src_data = load_settings_with_fragments(src_dir)

    if dest.exists():
        dest_data = json.loads(dest.read_text(encoding="utf-8"))
    else:
        dest_data = {}

    merged = merge_settings(dest_data, src_data)
    merged = _adapt_hooks(merged)

    if merged == dest_data:
        logger.info("settings.json already in sync")
        return False

    merged_text = json.dumps(merged, indent=2) + "\n"

    if dryrun:
        print(f"Would merge: {src_dir} -> {dest}")
        print(merged_text, end="")
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(merged_text, encoding="utf-8")
        if not quiet:
            print(f"Merged: {src_dir} -> {dest}")

    return True


def reconcile_config_dir(
    src_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    """Copy all files from src_dir to dest_dir (non-recursive).

    Skips files that are already identical. Creates dest_dir if needed.
    Returns True if any file changed.
    """
    if not src_dir.is_dir():
        return False

    changed = False
    for src_file in sorted(src_dir.iterdir()):
        if not src_file.is_file():
            continue
        dest_file = dest_dir / src_file.name
        try:
            if dest_file.exists() and src_file.read_text(
                encoding="utf-8"
            ) == dest_file.read_text(encoding="utf-8"):
                continue
        except OSError:
            pass

        changed = True
        if dryrun:
            print(f"Would copy: {src_file} -> {dest_file}")
        else:
            dest_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dest_file)
            if not quiet:
                print(f"Copied: {src_file} -> {dest_file}")

    if not changed:
        logger.info("%s already in sync", src_dir.name)

    return changed


def reconcile_scripts(
    repo_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    """Copy scripts/ from repo into dest_dir/my-claude-stuff/scripts/."""
    src_scripts = repo_dir / "scripts"
    dest_scripts = dest_dir / "my-claude-stuff" / "scripts"

    if not src_scripts.is_dir():
        logger.warning(f"source scripts dir not found: {src_scripts}")
        return False

    changed = False
    for src_file in sorted(src_scripts.glob("*.py")):
        dest_file = dest_scripts / src_file.name
        try:
            if dest_file.exists() and src_file.read_text(
                encoding="utf-8"
            ) == dest_file.read_text(encoding="utf-8"):
                continue
        except OSError:
            pass

        changed = True
        if dryrun:
            print(f"Would copy: {src_file} -> {dest_file}")
        else:
            dest_scripts.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dest_file)
            if not quiet:
                print(f"Copied: {src_file} -> {dest_file}")

    return changed


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="push Claude Code config from source to destination"
    )
    parser.add_argument("src", type=Path, help="source directory")
    parser.add_argument("dest", type=Path, help="destination directory")
    parser.add_argument(
        "--dryrun", action="store_true", help="preview changes without writing"
    )
    parser.add_argument("--debug", action="store_true", help="enable debug output")
    parser.add_argument(
        "--quiet", "-q", action="store_true", help="suppress non-essential output"
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    level = logging.WARNING
    if args.debug:
        level = logging.DEBUG
    elif not args.quiet:
        level = logging.INFO
    logging.basicConfig(
        level=level, format="%(asctime)s %(levelname)s %(name)s: %(message)s"
    )

    if not args.src.exists():
        logger.error(f"source dir not found: {args.src}")
        return EXIT_ERROR

    changed = False
    try:
        changed |= reconcile_claude_md(
            args.src, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
        changed |= reconcile_settings(
            args.src, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
        changed |= reconcile_scripts(
            args.src.parent, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
        config_dir = args.src.parent / "config"
        if config_dir.is_dir():
            for subdir in sorted(config_dir.iterdir()):
                if subdir.is_dir():
                    changed |= reconcile_config_dir(
                        subdir,
                        Path.home() / ".config" / subdir.name,
                        dryrun=args.dryrun,
                        quiet=args.quiet,
                    )
    except (json.JSONDecodeError, OSError) as exc:
        logger.error(f"reconcile failed: {exc}")
        return EXIT_ERROR

    if not changed:
        if not args.quiet:
            print("Everything in sync.")
    elif args.dryrun:
        print("\nRe-run without --dryrun to apply.")

    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
