#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Reconcile Claude Code config from source to destination directory.

Push-only: src -> dest. Source keys win, dest-only keys are preserved.

CLAUDE.md: straight copy.
settings.json: deep merge -- lists are unioned, dicts are merged (src wins),
scalars from src overwrite dest.
"""

import argparse
import json
import logging
import shutil
import sys
from pathlib import Path

EXIT_SUCCESS = 0
EXIT_ERROR = 1

logger = logging.getLogger("reconcile")


def merge_settings(dest_data: dict, src_data: dict) -> dict:
    """Merge src settings on top of dest. Src wins, dest-only keys kept."""
    merged = dict(dest_data)

    for key, src_val in src_data.items():
        dest_val = merged.get(key)

        if isinstance(src_val, dict) and isinstance(dest_val, dict):
            merged[key] = merge_settings(dest_val, src_val)
        elif isinstance(src_val, list) and isinstance(dest_val, list):
            seen = set()
            unioned = []
            for item in dest_val + src_val:
                item_key = (
                    json.dumps(item, sort_keys=True)
                    if isinstance(item, (dict, list))
                    else item
                )
                if item_key not in seen:
                    seen.add(item_key)
                    unioned.append(item)
            merged[key] = unioned
        else:
            merged[key] = src_val

    return merged


def reconcile_claude_md(
    src_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    src = src_dir / "CLAUDE.md"
    dest = dest_dir / "CLAUDE.md"

    if not src.exists():
        logger.warning(f"source does not exist: {src}")
        return False

    if dest.exists() and src.read_text(encoding="utf-8") == dest.read_text(
        encoding="utf-8"
    ):
        logger.info("CLAUDE.md already in sync")
        return False

    if dryrun:
        print(f"Would copy: {src} -> {dest}")
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        if not quiet:
            print(f"Copied: {src} -> {dest}")
    return True


def reconcile_settings(
    src_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    src = src_dir / "settings.json"
    dest = dest_dir / "settings.json"

    if not src.exists():
        logger.warning(f"source does not exist: {src}")
        return False

    src_data = json.loads(src.read_text(encoding="utf-8"))

    if dest.exists():
        dest_data = json.loads(dest.read_text(encoding="utf-8"))
    else:
        dest_data = {}

    merged = merge_settings(dest_data, src_data)

    if merged == dest_data:
        logger.info("settings.json already in sync")
        return False

    merged_text = json.dumps(merged, indent=2) + "\n"

    if dryrun:
        print(f"Would merge: {src} -> {dest}")
        print(merged_text, end="")
    else:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(merged_text, encoding="utf-8")
        if not quiet:
            print(f"Merged: {src} -> {dest}")

    return True


def reconcile_scripts(
    repo_dir: Path,
    dest_dir: Path,
    *,
    dryrun: bool = False,
    quiet: bool = False,
) -> bool:
    """Copy scripts/ from repo into dest_dir/my-claude-stuff/scripts/."""
    src_scripts = repo_dir / "scripts"
    dest_scripts = dest_dir / "my-claude-stuff" / "scripts"

    if not src_scripts.is_dir():
        logger.warning(f"source scripts dir not found: {src_scripts}")
        return False

    changed = False
    for src_file in sorted(src_scripts.glob("*.py")):
        dest_file = dest_scripts / src_file.name
        try:
            if dest_file.exists() and src_file.read_text(
                encoding="utf-8"
            ) == dest_file.read_text(encoding="utf-8"):
                continue
        except OSError:
            pass

        changed = True
        if dryrun:
            print(f"Would copy: {src_file} -> {dest_file}")
        else:
            dest_scripts.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dest_file)
            if not quiet:
                print(f"Copied: {src_file} -> {dest_file}")

    return changed


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="push Claude Code config from source to destination"
    )
    parser.add_argument("src", type=Path, help="source directory")
    parser.add_argument("dest", type=Path, help="destination directory")
    parser.add_argument(
        "--dryrun", action="store_true", help="preview changes without writing"
    )
    parser.add_argument("--debug", action="store_true", help="enable debug output")
    parser.add_argument(
        "--quiet", "-q", action="store_true", help="suppress non-essential output"
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    level = logging.WARNING
    if args.debug:
        level = logging.DEBUG
    elif not args.quiet:
        level = logging.INFO
    logging.basicConfig(level=level, format="%(levelname)s: %(message)s")

    if not args.src.exists():
        logger.error(f"source dir not found: {args.src}")
        return EXIT_ERROR

    changed = False
    try:
        changed |= reconcile_claude_md(
            args.src, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
        changed |= reconcile_settings(
            args.src, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
        changed |= reconcile_scripts(
            args.src.parent, args.dest, dryrun=args.dryrun, quiet=args.quiet
        )
    except (json.JSONDecodeError, OSError) as exc:
        logger.error(f"reconcile failed: {exc}")
        return EXIT_ERROR

    if not changed:
        if not args.quiet:
            print("Everything in sync.")
    elif args.dryrun:
        print("\nRe-run without --dryrun to apply.")

    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
