#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Session tracking for Claude Code statusline.

Persists full statusline JSON blobs to date-partitioned directories
under ~/.claude/session-tracker/. Each session is keyed by session_id
(UUID, stable across detach/resume).

Layout:
  ~/.claude/session-tracker/
    2026-03-16/
      {uuid}.json
    2026-03-17/
      {uuid}.json
"""

import json
from datetime import date
from pathlib import Path

DEFAULT_DIR = Path.home() / ".claude" / "session-tracker"


def track_session(data, base_dir=DEFAULT_DIR):
    """Write the full statusline JSON blob to {date}/{session_id}.json."""
    session_id = data.get("session_id")
    if not session_id:
        return

    today_dir = Path(base_dir) / date.today().isoformat()
    try:
        today_dir.mkdir(parents=True, exist_ok=True)
        session_file = today_dir / f"{session_id}.json"
        with open(session_file, "w") as fh:
            json.dump(data, fh)
    except OSError:
        pass


def get_daily_cost(base_dir=DEFAULT_DIR):
    """Sum cost.total_cost_usd from all session files in today's directory."""
    today_dir = Path(base_dir) / date.today().isoformat()
    if not today_dir.is_dir():
        return 0.0

    total = 0.0
    for session_file in today_dir.iterdir():
        if not session_file.suffix == ".json":
            continue
        try:
            with open(session_file, "r") as fh:
                data = json.load(fh)
            total += (data.get("cost") or {}).get("total_cost_usd", 0.0)
        except (json.JSONDecodeError, OSError):
            continue
    return total
