#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Session tracking for Claude Code statusline.

Persists full statusline JSON blobs to date-partitioned directories
under ~/.claude/my-claude-stuff-data/session-tracker/.
Each session is keyed by session_id
(UUID, stable across detach/resume).

Layout:
  ~/.claude/my-claude-stuff-data/session-tracker/
    2026-03-16/
      {uuid}.json
    2026-03-17/
      {uuid}.json
"""

import json
import re
import sys
from datetime import date
from pathlib import Path, PurePosixPath

_scripts_parent = str(Path(__file__).resolve().parent.parent)
if _scripts_parent not in sys.path:
    sys.path.insert(0, _scripts_parent)

from scripts.config import DATA_DIR  # noqa: E402

DEFAULT_DIR = DATA_DIR / "session-tracker"
SESSION_FILE_SUFFIX = ".json"
WORKTREE_DIR_NAME = "git-worktrees"


def track_session(data, base_dir=DEFAULT_DIR):
    """Write the full statusline JSON blob to {date}/{session_id}.json.

    On the first write of a session each day, snapshots the prior
    cost into _prior_cost so get_daily_cost can compute today's
    delta without scanning historical directories.
    """
    session_id = data.get("session_id")
    if not session_id:
        return

    # Reject session_ids that could escape the target directory
    if not re.match(r"^[\w-]+$", session_id):
        return

    today_str = date.today().isoformat()
    today_dir = Path(base_dir) / today_str
    try:
        today_dir.mkdir(parents=True, exist_ok=True)
        session_file = today_dir / f"{session_id}{SESSION_FILE_SUFFIX}"

        # On first write today, look up prior cost (one-time scan)
        if not session_file.exists():
            prior = _find_prior_cost(session_file.name, today_str, base_dir)
            data = dict(data, _prior_cost=prior)
        else:
            # Preserve the prior cost from the first write
            try:
                with open(session_file, "r", encoding="utf-8") as fh:
                    existing = json.load(fh)
                data = dict(data, _prior_cost=existing.get("_prior_cost", 0.0))
            except (json.JSONDecodeError, OSError):
                data = dict(data, _prior_cost=0.0)

        with open(session_file, "w", encoding="utf-8") as fh:
            json.dump(data, fh)
    except OSError:
        pass


def _normalize_project_dir(path):
    """Normalize project_dir by stripping WORKTREE_DIR_NAME/<name> suffix.

    If path contains the worktree directory, return the grandparent.
    This ensures worktree sessions roll up to the main project.
    """
    parts = PurePosixPath(path).parts
    for i, part in enumerate(parts):
        if part == WORKTREE_DIR_NAME and i + 1 < len(parts):
            return str(PurePosixPath(*parts[:i]))
    return path


def _find_prior_cost(session_filename, today_str, base_dir):
    """Find the prior cost for a session before today.

    Globs for the session file across all date directories, then picks
    the most recent one before today. Single filesystem call regardless
    of how many date directories exist.
    """
    base = Path(base_dir)
    matches = sorted(
        (p for p in base.glob(f"*/{session_filename}") if p.parent.name < today_str),
        key=lambda p: p.parent.name,
        reverse=True,
    )
    if not matches:
        return 0.0
    try:
        with open(matches[0], "r", encoding="utf-8") as fh:
            data = json.load(fh)
        return (data.get("cost") or {}).get("total_cost_usd", 0.0)
    except (json.JSONDecodeError, OSError):
        return 0.0


def get_daily_cost(base_dir=DEFAULT_DIR):
    """Sum today's cost delta for all sessions.

    For sessions that span multiple days, subtracts the prior cost
    snapshot stored in _prior_cost (written by track_session on
    first appearance each day) so only today's portion is counted.
    """
    today_dir = Path(base_dir) / date.today().isoformat()
    if not today_dir.is_dir():
        return 0.0

    total = 0.0
    for session_file in today_dir.iterdir():
        if session_file.suffix != SESSION_FILE_SUFFIX:
            continue
        try:
            with open(session_file, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            session_cost = (data.get("cost") or {}).get("total_cost_usd", 0.0)
            prior_cost = data.get("_prior_cost", 0.0)
            total += session_cost - prior_cost
        except (json.JSONDecodeError, OSError):
            continue
    return total


def get_previous_day_cost(base_dir=DEFAULT_DIR):
    """Return (daily_total, session_count) for the most recent day before today."""
    base = Path(base_dir)
    if not base.is_dir():
        return 0.0, 0

    today = date.today().isoformat()
    date_dirs = sorted(
        (d.name for d in base.iterdir() if d.is_dir() and d.name < today),
        reverse=True,
    )
    if not date_dirs:
        return 0.0, 0

    prev_dir = base / date_dirs[0]
    total = 0.0
    count = 0
    for sf in prev_dir.iterdir():
        if sf.suffix != SESSION_FILE_SUFFIX:
            continue
        try:
            with open(sf, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            total += (data.get("cost") or {}).get("total_cost_usd", 0.0)
            count += 1
        except (json.JSONDecodeError, OSError):
            continue
    return total, count


def get_project_cost(project_dir, base_dir=DEFAULT_DIR):
    """Sum cost.total_cost_usd across ALL dates for sessions matching project_dir.

    Normalizes project_dir (stripping git-worktrees suffixes) before comparison.
    """
    base = Path(base_dir)
    if not base.is_dir():
        return 0.0

    normalized_query = _normalize_project_dir(project_dir)
    total = 0.0

    for date_dir in base.iterdir():
        if not date_dir.is_dir():
            continue
        for session_file in date_dir.iterdir():
            if session_file.suffix != SESSION_FILE_SUFFIX:
                continue
            try:
                with open(session_file, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
                session_project = (data.get("workspace") or {}).get("project_dir")
                if not session_project:
                    continue
                if _normalize_project_dir(session_project) == normalized_query:
                    total += (data.get("cost") or {}).get("total_cost_usd", 0.0)
            except (json.JSONDecodeError, OSError):
                continue
    return total
