#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code status line.

Output:
  Context | <reset>: <pct>% | ... | S/T/P: $x / $y / $z | model | session_id

Colors:
  Quota %:  green < 60%, yellow 60-89%, red >= 90%
  Costs:    blue ramp (dark to bright), $15 steps, saturates at $195+
  Model:    orange
  Session:  purple

Quota labels show time remaining until reset, e.g.:
  3h4m: 20% | 4d12h: 4%
At most 2 units of precision: d+h, h+m, m+s, or single unit.
Freshness only shown on stale/error: (!5m)

S/T/P = Session / Today / Project cost (USD).
Session ID appended for cross-session prompt log correlation.
"""

import json
import logging
import logging.handlers
import sys
import time
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

# Ensure scripts/ parent is on sys.path so `from scripts.config` works
# when invoked directly (e.g. by Claude Code statusline command).
_scripts_parent = str(Path(__file__).resolve().parent.parent)
if _scripts_parent not in sys.path:
    sys.path.insert(0, _scripts_parent)

from scripts.config import (  # noqa: E402
    ANSI_GREEN,
    ANSI_ORANGE,
    ANSI_PURPLE,
    ANSI_RED,
    ANSI_RESET,
    ANSI_YELLOW,
    DATA_DIR,
    THRESHOLD_HIGH,
    THRESHOLD_MID,
)

USAGE_CACHE_TTL_SECONDS = 120
USAGE_CACHE_DIR = DATA_DIR / "statusline-cache"
USAGE_CACHE_FILE = USAGE_CACHE_DIR / "oauth_usage.json"
LOG_FILE = USAGE_CACHE_DIR / "statusline.log"
CREDENTIALS_FILE = Path.home() / ".claude" / ".credentials.json"

logger = logging.getLogger("statusline")
_log_configured = False


def _configure_logging():
    global _log_configured
    if _log_configured:
        return
    _log_configured = True
    try:
        USAGE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            str(LOG_FILE),
            maxBytes=256 * 1024,
            backupCount=1,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
        logger.addHandler(handler)
        logger.setLevel(logging.DEBUG)
    except OSError:
        pass


# source: reddit.com/r/ClaudeAI/comments/1rqnryw
USAGE_API_URL = "https://api.anthropic.com/api/oauth/usage"


def format_duration(seconds):
    """Format seconds as compact duration, max 2 units.

    Build full d+h+m+s, then truncate after the second unit.
    """
    seconds = max(0, int(seconds))
    days = seconds // 86400
    hours = (seconds % 86400) // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    parts = []
    if days:
        parts.append(f"{days}d")
    if hours:
        parts.append(f"{hours}h")
    if minutes:
        parts.append(f"{minutes}m")
    if secs or not parts:
        parts.append(f"{secs}s")
    return "".join(parts[:2])


# Blue ramp: dark to bright in $15 steps, caps at $195+
_COST_SHADES = [17, 18, 19, 20, 21, 27, 33, 39, 45, 51, 87, 123, 159, 195]
_COST_STEP = 15


def colorize_cost(amount):
    """Return dollar amount colored by absolute value.

    Single blue ramp, $15 steps, saturates at $195+.
    """
    idx = min(int(amount / _COST_STEP), len(_COST_SHADES) - 1)
    return f"\033[38;5;{_COST_SHADES[idx]}m${amount:.2f}{ANSI_RESET}"


def colorize_pct(pct):
    """Return pct formatted as a string with ANSI color based on magnitude.

    Green  < THRESHOLD_MID
    Yellow THRESHOLD_MID to THRESHOLD_HIGH
    Red    >= THRESHOLD_HIGH
    """
    value = f"{pct:.0f}%"
    if pct >= THRESHOLD_HIGH * 100:
        color = ANSI_RED
    elif pct >= THRESHOLD_MID * 100:
        color = ANSI_YELLOW
    else:
        color = ANSI_GREEN
    return f"{color}{value}{ANSI_RESET}"


def format_remaining(resets_at):
    """Parse resets_at ISO timestamp, return compact time remaining."""
    if not resets_at:
        return None
    try:
        reset_dt = datetime.fromisoformat(resets_at)
        now = datetime.now(timezone.utc)
        remaining = int((reset_dt - now).total_seconds())
        if remaining <= 0:
            return "0s"
        return format_duration(remaining)
    except (ValueError, OverflowError):
        return None


def get_oauth_token():
    try:
        data = json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))
        return data["claudeAiOauth"]["accessToken"]
    except (OSError, KeyError, json.JSONDecodeError) as e:
        logger.error("Failed to read OAuth token: %s", e)
        return None


def fetch_usage():
    token = get_oauth_token()
    if not token:
        logger.warning("No OAuth token available, skipping fetch")
        return None

    req = urllib.request.Request(USAGE_API_URL)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("anthropic-beta", "oauth-2025-04-20")

    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read())
            logger.debug("Fetch succeeded")
            return data
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode()[:200]
        except Exception:
            pass
        logger.error("HTTP %d %s: %s", e.code, e.reason, body)
        return None
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as e:
        logger.error("Fetch failed: %s: %s", type(e).__name__, e)
        return None


def _read_cache():
    """Read and migrate cache file. Returns dict or None."""
    if not USAGE_CACHE_FILE.exists():
        return None
    try:
        cached = json.loads(USAGE_CACHE_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    # Migrate old single-letter keys to new schema
    if "v" in cached and "response_data" not in cached:
        cached = {
            "response_data": cached["v"],
            "last_success_at": cached.get("t", 0),
            "last_attempt_at": cached.get("t", 0),
            "consecutive_failures": 0,
        }
    return cached


def _write_cache(cache_dict):
    """Write cache dict to disk."""
    try:
        USAGE_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
        USAGE_CACHE_FILE.write_text(json.dumps(cache_dict), encoding="utf-8")
    except OSError:
        pass


MAX_COOLDOWN_SECONDS = 3600
# If no attempt in this window, assume stale failure (sleep/resume) and retry
STALE_FAILURE_SECONDS = 21600  # 6 hours


def get_usage():
    """Return (usage_dict, age_seconds, stale) or (None, 0, False)."""
    now = time.time()
    cached = _read_cache()

    if cached:
        age = now - cached.get("last_success_at", 0)
        if age < USAGE_CACHE_TTL_SECONDS:
            return cached.get("response_data"), age, False

        # Stale — check if we should skip fetch due to backoff cooldown
        failures = cached.get("consecutive_failures", 0)
        since_last_attempt = now - cached.get("last_attempt_at", 0)
        # Long gap (sleep/resume) — reset backoff and retry immediately
        if failures > 0 and since_last_attempt >= STALE_FAILURE_SECONDS:
            logger.info(
                "Stale failure: %.0fs since last attempt, resetting backoff",
                since_last_attempt,
            )
            failures = 0
        if failures > 0:
            cooldown = min(
                USAGE_CACHE_TTL_SECONDS * (2**failures), MAX_COOLDOWN_SECONDS
            )
            if since_last_attempt < cooldown:
                logger.info(
                    "Backoff: skipping fetch, %d consecutive failures, "
                    "cooldown %.0fs, %.0fs remaining",
                    failures,
                    cooldown,
                    cooldown - since_last_attempt,
                )
                return cached.get("response_data"), age, True

    result = fetch_usage()

    if result is not None:
        _write_cache(
            {
                "response_data": result,
                "last_success_at": now,
                "last_attempt_at": now,
                "consecutive_failures": 0,
            }
        )
        return result, 0, False

    # Fetch failed — update attempt tracking, preserve stale data
    if cached:
        cached["last_attempt_at"] = now
        cached["consecutive_failures"] = cached.get("consecutive_failures", 0) + 1
        _write_cache(cached)
        age = now - cached.get("last_success_at", 0)
        logger.warning(
            "Fetch failed, consecutive_failures=%d, serving stale cache (%.0fs old)",
            cached["consecutive_failures"],
            age,
        )
        return cached.get("response_data"), age, True

    return None, 0, False


def main():
    _configure_logging()
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        print("Claude Code")
        return

    model = data.get("model", {}).get("display_name", "Claude")
    parts = []

    ctx = data.get("context_window", {})
    used_pct = ctx.get("used_percentage")
    if used_pct is not None:
        parts.append(f"Context: {colorize_pct(used_pct)}")

    usage, age_seconds, stale = get_usage()
    if usage:
        for bucket in ("five_hour", "seven_day"):
            entry = usage.get(bucket)
            if not entry:
                continue
            pct = entry.get("utilization")
            if pct is None:
                continue
            label = format_remaining(entry.get("resets_at"))
            if label is None:
                label = "5h" if bucket == "five_hour" else "1w"
            parts.append(f"{label}: {colorize_pct(pct)}")

        if stale:
            age_str = format_duration(age_seconds)
            parts.append(f"({ANSI_RED}!{age_str}{ANSI_RESET})")

    # When invoked directly (python3 path/to/statusline.py), the parent
    # of scripts/ must be on sys.path for the package import to work.
    _scripts_parent = str(Path(__file__).resolve().parent.parent)
    if _scripts_parent not in sys.path:
        sys.path.insert(0, _scripts_parent)
    from scripts.session_tracker import get_daily_cost, get_project_cost, track_session

    track_session(data)
    cost = (data.get("cost") or {}).get("total_cost_usd") or 0.0
    daily = get_daily_cost()
    project_dir = (data.get("workspace") or {}).get("project_dir")
    proj_cost = get_project_cost(project_dir) if project_dir else 0.0
    parts.append(
        f"S/T/P: {colorize_cost(cost)} / {colorize_cost(daily)}"
        f" / {colorize_cost(proj_cost)}"
    )

    parts.append(f"{ANSI_ORANGE}{model}{ANSI_RESET}")
    session_id = data.get("session_id", "")
    if session_id:
        parts.append(f"{ANSI_PURPLE}{session_id}{ANSI_RESET}")
    print(" | ".join(parts))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        _configure_logging()
        logger.exception("statusline crashed")
        print(f"{ANSI_RED}!ERR check {LOG_FILE}{ANSI_RESET}")
