#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code status line.

Output:
  Context | <reset>: <pct>% | ... | S/T/P: $x / $y / $z | model | session_id

Colors:
  Quota %:  green < 60%, yellow 60-89%, red >= 90%
  Costs:    cyan ramp (monotonic brightness), $15 steps, saturates at $195+
  Model:    orange
  Session:  purple

Quota labels show time remaining until reset, e.g.:
  3h4m: 20% | 4d12h: 4%
At most 2 units of precision: d+h, h+m, m+s, or single unit.
When 5h quota hits 100% and extra usage is enabled, appends $used/$limit.
Freshness only shown on stale/error: (!5m)

S/T/P = Session / Today / Project cost (USD).
Session ID appended for cross-session prompt log correlation.
"""

import json
import logging
import logging.handlers
import os
import platform
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

# Ensure scripts/ parent is on sys.path so `from scripts.config` works
# when invoked directly (e.g. by Claude Code statusline command).
_scripts_parent = str(Path(__file__).resolve().parent.parent)
if _scripts_parent not in sys.path:
    sys.path.insert(0, _scripts_parent)

from scripts.config import (  # noqa: E402
    ANSI_GREEN,
    ANSI_ORANGE,
    ANSI_PURPLE,
    ANSI_RED,
    ANSI_RESET,
    ANSI_YELLOW,
    DATA_DIR,
    THRESHOLD_HIGH,
    THRESHOLD_MID,
)

LOG_DIR = DATA_DIR / "statusline-cache"
LOG_FILE = LOG_DIR / "statusline.log"

logger = logging.getLogger("statusline")
_log_configured = False


def _configure_logging():
    global _log_configured
    if _log_configured:
        return
    _log_configured = True
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        handler = logging.handlers.RotatingFileHandler(
            str(LOG_FILE),
            maxBytes=256 * 1024,
            backupCount=1,
            encoding="utf-8",
        )
        handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
        logger.addHandler(handler)
        logger.setLevel(logging.DEBUG)
    except OSError:
        pass


def format_duration(seconds):
    """Format seconds as compact duration, max 2 units.

    Build full d+h+m+s, then truncate after the second unit.
    """
    seconds = max(0, int(seconds))
    days = seconds // 86400
    hours = (seconds % 86400) // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60

    parts = []
    if days:
        parts.append(f"{days}d")
    if hours:
        parts.append(f"{hours}h")
    if minutes:
        parts.append(f"{minutes}m")
    if secs or not parts:
        parts.append(f"{secs}s")
    return "".join(parts[:2])


# Cyan monotonic ramp: follows 256-color cube diagonal for strict brightness increase.
# $15 steps, caps at $195+. Visible on both dark terminals and VSCode.
_COST_SHADES = [30, 37, 44, 51, 80, 87, 116, 123, 152, 159, 181, 188, 195, 231]
_COST_STEP = 15


def colorize_cost(amount):
    """Return dollar amount colored by absolute value.

    Single blue ramp, $15 steps, saturates at $195+.
    """
    idx = min(int(amount / _COST_STEP), len(_COST_SHADES) - 1)
    return f"\033[38;5;{_COST_SHADES[idx]}m${amount:.2f}{ANSI_RESET}"


def _pct_color(pct):
    """Return ANSI color code for a percentage value.

    Green  < THRESHOLD_MID
    Yellow THRESHOLD_MID to THRESHOLD_HIGH
    Red    >= THRESHOLD_HIGH
    """
    if pct >= THRESHOLD_HIGH * 100:
        return ANSI_RED
    elif pct >= THRESHOLD_MID * 100:
        return ANSI_YELLOW
    return ANSI_GREEN


def colorize_pct(pct):
    """Return pct formatted as a string with ANSI color based on magnitude."""
    return f"{_pct_color(pct)}{pct:.0f}%{ANSI_RESET}"


def format_remaining(resets_at):
    """Parse resets_at ISO timestamp, return compact time remaining."""
    if not resets_at:
        return None
    try:
        reset_dt = datetime.fromisoformat(resets_at)
        now = datetime.now(timezone.utc)
        remaining = int((reset_dt - now).total_seconds())
        if remaining <= 0:
            return "0s"
        return format_duration(remaining)
    except (ValueError, OverflowError):
        return None


_AGENTPULSE_CONFIG = Path.home() / ".claude" / "agentpulse" / "config.json"


def get_usage():
    """Fetch usage data from agentpulse GET /api/v1/limits.

    Returns (usage_dict, age_seconds, stale) or (None, 0, False).
    Agentpulse owns OAuth, caching, and backoff — statusline is a pure
    display client.  The response has buckets (five_hour, seven_day, etc.)
    and metadata (age_seconds, stale) at the top level; we pass the whole
    dict as usage_dict so main() can read buckets directly.
    """
    try:
        if not _AGENTPULSE_CONFIG.exists():
            return None, 0, False
        cfg = json.loads(_AGENTPULSE_CONFIG.read_text(encoding="utf-8"))
        if not cfg.get("fetch_limits", True):
            return None, 0, False
        host = cfg.get("host", "127.0.0.1")
        port = cfg.get("port", 17385)
        url = f"http://{host}:{port}/api/v1/limits"
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=2) as resp:
            data = json.loads(resp.read())
            return (
                data,
                data.get("age_seconds", 0),
                data.get("stale", False),
            )
    except Exception:
        return None, 0, False


def _relay_to_agentpulse(data):
    """POST statusline data to agentpulse. Silent on failure."""
    try:
        if not _AGENTPULSE_CONFIG.exists():
            return
        cfg = json.loads(_AGENTPULSE_CONFIG.read_text(encoding="utf-8"))
        host = cfg.get("host", "127.0.0.1")
        port = cfg.get("port", 17385)

        # Inject source_system and pid so agentpulse can create the session
        # on the first statusline tick, before any hooks fire.
        data["source_system"] = platform.node()
        try:
            import psutil

            claude_pid = 0
            for proc in psutil.Process(os.getpid()).parents():
                try:
                    if "claude" in proc.name().lower():
                        claude_pid = proc.pid
                        break
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    break
            data["pid"] = claude_pid or os.getppid()
        except ImportError:
            data["pid"] = os.getppid()

        url = f"http://{host}:{port}/statusline/claude"
        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode(),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=1)
    except Exception:
        pass


def main():
    _configure_logging()
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        print("Claude Code")
        return

    _relay_to_agentpulse(data)

    model = data.get("model", {}).get("display_name", "Claude")
    parts = []

    ctx = data.get("context_window", {})
    used_pct = ctx.get("used_percentage")
    if used_pct is not None:
        parts.append(f"Context: {colorize_pct(used_pct)}")

    usage, age_seconds, stale = get_usage()
    if usage:
        for bucket in ("five_hour", "seven_day"):
            entry = usage.get(bucket)
            if not entry:
                continue
            pct = entry.get("utilization")
            if pct is None:
                continue
            label = format_remaining(entry.get("resets_at"))
            if label is None:
                label = "5h" if bucket == "five_hour" else "1w"
            segment = f"{label}: {colorize_pct(pct)}"
            if bucket == "five_hour" and pct >= 100:
                extra = usage.get("extra_usage")
                if extra and extra.get("is_enabled"):
                    used = extra.get("used_credits_usd", 0)
                    limit = extra.get("monthly_limit_usd", 0)
                    extra_pct = (used / limit * 100) if limit else 0
                    color = _pct_color(extra_pct)
                    segment += f" {color}${used:.0f}/${limit:.0f}{ANSI_RESET}"
            parts.append(segment)

        if stale:
            age_str = format_duration(age_seconds)
            parts.append(f"({ANSI_RED}!{age_str}{ANSI_RESET})")

    from scripts.session_tracker import get_daily_cost, get_project_cost, track_session

    track_session(data)
    cost = (data.get("cost") or {}).get("total_cost_usd") or 0.0
    daily = get_daily_cost()
    project_dir = (data.get("workspace") or {}).get("project_dir")
    proj_cost = get_project_cost(project_dir) if project_dir else 0.0
    parts.append(
        f"S/T/P: {colorize_cost(cost)} / {colorize_cost(daily)}"
        f" / {colorize_cost(proj_cost)}"
    )

    parts.append(f"{ANSI_ORANGE}{model}{ANSI_RESET}")
    session_id = data.get("session_id", "")
    if session_id:
        parts.append(f"{ANSI_PURPLE}{session_id}{ANSI_RESET}")
    print(" | ".join(parts))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        _configure_logging()
        logger.exception("statusline crashed")
        print(f"{ANSI_RED}!ERR check {LOG_FILE}{ANSI_RESET}")
