#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Claude Code status line.

Output: Model | Context | 5h | 1w (freshness) | Session | Today

Quota utilization is fetched from the Anthropic OAuth usage API.
Cached for 2 minutes; on 429/error, stale cache is used.
Freshness indicator shows age and fetch status:
  (2m)  = data is 2 minutes old, last fetch succeeded
  (!5m) = data is 5 minutes old, last fetch failed

Session cost (Vertex only) from Claude Code stdin.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

USAGE_CACHE_TTL_SECONDS = 120
USAGE_CACHE_FILE = Path.home() / ".claude" / "statusline-cache" / "oauth_usage.json"
CREDENTIALS_FILE = Path.home() / ".claude" / ".credentials.json"
# source: reddit.com/r/ClaudeAI/comments/1rqnryw
USAGE_API_URL = "https://api.anthropic.com/api/oauth/usage"


def format_age(seconds):
    """Format seconds into a compact age string."""
    seconds = max(0, int(seconds))
    if seconds < 60:
        return f"{seconds}s"
    minutes = seconds // 60
    if minutes < 60:
        return f"{minutes}m"
    hours = minutes // 60
    return f"{hours}h"


def get_oauth_token():
    try:
        data = json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))
        return data["claudeAiOauth"]["accessToken"]
    except (OSError, KeyError, json.JSONDecodeError):
        return None


def fetch_usage():
    token = get_oauth_token()
    if not token:
        return None

    req = urllib.request.Request(USAGE_API_URL)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("anthropic-beta", "oauth-2025-04-20")

    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, OSError, json.JSONDecodeError):
        return None


def get_usage():
    """Return (usage_dict, age_seconds, stale) or (None, 0, False)."""
    now = time.time()

    if USAGE_CACHE_FILE.exists():
        try:
            cached = json.loads(USAGE_CACHE_FILE.read_text(encoding="utf-8"))
            age = now - cached.get("t", 0)
            if age < USAGE_CACHE_TTL_SECONDS:
                return cached.get("v"), age, False
        except (json.JSONDecodeError, OSError):
            cached = None

    result = fetch_usage()

    if result is not None:
        try:
            USAGE_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
            USAGE_CACHE_FILE.write_text(
                json.dumps({"v": result, "t": now}),
                encoding="utf-8",
            )
        except OSError:
            pass
        return result, 0, False

    # On failure (429 or other), return stale cache
    if USAGE_CACHE_FILE.exists():
        try:
            cached = json.loads(USAGE_CACHE_FILE.read_text(encoding="utf-8"))
            age = now - cached.get("t", 0)
            return cached.get("v"), age, True
        except (json.JSONDecodeError, OSError):
            pass

    return None, 0, False


def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        print("Claude Code")
        return

    model = data.get("model", {}).get("display_name", "Claude")
    parts = [f"Model: {model}"]

    ctx = data.get("context_window", {})
    used_pct = ctx.get("used_percentage")
    if used_pct is not None:
        parts.append(f"Context: {used_pct}%")

    usage, age_seconds, stale = get_usage()
    if usage:
        five_h = usage.get("five_hour", {})
        seven_d = usage.get("seven_day", {})
        five_h_pct = five_h.get("utilization") if five_h else None
        seven_d_pct = seven_d.get("utilization") if seven_d else None

        if five_h_pct is not None:
            parts.append(f"5h: {five_h_pct:.0f}%")
        if seven_d_pct is not None:
            parts.append(f"1w: {seven_d_pct:.0f}%")

        age_str = format_age(age_seconds)
        if stale:
            parts.append(f"(!{age_str})")
        else:
            parts.append(f"({age_str})")

    is_vertex = bool(os.environ.get("CLAUDE_CODE_USE_VERTEX"))

    if is_vertex:
        from scripts.session_tracker import get_daily_cost, track_session

        track_session(data)
        cost = (data.get("cost") or {}).get("total_cost_usd")
        parts.append(f"Session: ${cost:.2f}" if cost is not None else "Session: $0.00")
        daily = get_daily_cost()
        parts.append(f"Today: ${daily:.2f}")

    print(" | ".join(parts))


if __name__ == "__main__":
    main()
