#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Render color sample statuslines directly in the terminal for visual comparison."""

RESET = "\033[0m"
RED = "\033[31m"
GREEN = "\033[32m"

# Current blue ramp
CURRENT_SHADES = [17, 18, 19, 20, 21, 27, 33, 39, 45, 51, 87, 123, 159, 195]

# Option G: Teal diagonal — follows cube diagonal for monotonic brightness
# r0g1b1 -> r0g2b2 -> ... -> r0g5b5 -> r1g4b4 -> r1g5b5 -> ... -> r4g5b5
TEAL_DIAG = [23, 30, 37, 44, 51, 80, 87, 116, 123, 152, 159, 188, 195, 231]

# Option H: Cyan monotonic — starts brighter, stays strictly ordered
# Skips darkest teal, wider gaps in the saturated range
CYAN_MONO = [30, 37, 44, 51, 80, 87, 116, 123, 152, 159, 181, 188, 195, 231]

# Option I: Green-to-cyan diagonal — green start, monotonic via cube walk
# r0g2b0 -> r0g3b1 -> r0g4b2 -> r0g5b3 -> r0g5b5 -> then cyan diagonal up
GREEN_DIAG = [28, 35, 42, 49, 50, 51, 87, 123, 152, 159, 181, 188, 195, 231]

STEP = 15


def colorize_cost(amount, shades):
    idx = min(int(amount / STEP), len(shades) - 1)
    return f"\033[38;5;{shades[idx]}m${amount:.2f}{RESET}"


def render_sample(label, shades):
    # Simulate S/T/P with $0, ~$22, ~$200 like the screenshot
    costs = [0.0, 22.37, 200.07]
    cost_str = " / ".join(colorize_cost(c, shades) for c in costs)
    print(f"  {RED}S/T/P:{RESET} {cost_str}")

    # Also show the full ramp
    ramp = "  Ramp: "
    for i, shade in enumerate(shades):
        amt = i * STEP
        ramp += f"\033[38;5;{shade}m${amt:<4}{RESET} "
    print(ramp)
    print()


def main():
    print()
    print("=" * 60)
    print("Color comparison for statusline costs")
    print("=" * 60)
    print()

    schemes = [
        ("CURRENT (dark blue ramp)", CURRENT_SHADES),
        ("Option G: Teal diagonal (monotonic)", TEAL_DIAG),
        ("Option H: Cyan monotonic (brighter start)", CYAN_MONO),
        ("Option I: Green-to-cyan diagonal", GREEN_DIAG),
    ]

    for label, shades in schemes:
        print(f"{GREEN}{label}{RESET}")
        render_sample(label, shades)


if __name__ == "__main__":
    main()
