#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
"""Discover all gws subcommands recursively and output --help permission entries.

The gws CLI is based on gcloud API responses, so commands can change over time.
Run this script to regenerate the list of --help permission entries for
settings.json whenever gws is updated.

Usage:
    python3 scripts/discover_gws_help.py
"""

import re
import subprocess
import sys


def get_help_output(cmd_parts: list[str]) -> str:
    """Run a command with --help and return combined output.

    Returns empty string if the command errors or returns JSON error responses
    (some gws subcommands like 'schema' don't support --help).
    """
    try:
        result = subprocess.run(
            [*cmd_parts, "--help"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        output = result.stdout + result.stderr
        # Skip commands that return JSON errors instead of help text
        stripped = output.strip()
        if stripped.startswith("{"):
            return ""
        # Must contain some recognizable help content
        if not any(
            kw in output.lower() for kw in ["usage", "commands", "options", "services"]
        ):
            return ""
        return output
    except Exception:
        return ""


def extract_subcommands(help_text: str) -> list[str]:
    """Extract subcommand names from help text.

    Handles multiple formats:
    - "SERVICES:" section (top-level gws --help)
    - "Commands:" section (clap-style subcommand listings)
    - "Usage: gws cmd <sub1|sub2|...>" inline syntax
    """
    subcommands: list[str] = []
    in_section = False
    skip_words = frozenset(
        {
            "use",
            "the",
            "for",
            "and",
            "see",
            "help",
            "flags",
            "global",
            "options",
            "usage",
        }
    )

    section_headers = re.compile(
        r"^(Commands|Available Commands|Subcommands|COMMANDS|SERVICES):?\s*$",
        re.IGNORECASE,
    )
    other_header = re.compile(r"^[A-Z][A-Za-z -]+:\s*$")

    for line in help_text.splitlines():
        stripped = line.strip()

        # Detect section headers for commands/services
        if section_headers.match(stripped):
            in_section = True
            continue

        if in_section:
            if not stripped or (
                other_header.match(stripped) and not section_headers.match(stripped)
            ):
                in_section = False
                continue

            # Match lines like "  command-name   Description text"
            # Also handles "+command" helper commands
            match = re.match(r"^\+?(\w[\w-]*)\s", stripped)
            if match:
                cmd = match.group(1)
                if cmd.lower() not in skip_words:
                    subcommands.append(cmd)

    # Also parse "Usage: gws cmd <sub1|sub2|sub3>" style
    usage_match = re.search(r"<([\w|]+)>", help_text)
    if usage_match:
        candidates = usage_match.group(1).split("|")
        for c in candidates:
            c = c.strip()
            if c and c.lower() not in skip_words and c not in subcommands:
                subcommands.append(c)

    return subcommands


def discover(prefix: list[str], depth: int = 0, max_depth: int = 3) -> list[list[str]]:
    """Recursively discover subcommands that accept --help."""
    if depth > max_depth:
        return []

    help_text = get_help_output(prefix)
    if not help_text:
        return []

    results: list[list[str]] = []
    results.append(list(prefix))

    for sub in extract_subcommands(help_text):
        results.extend(discover([*prefix, sub], depth + 1, max_depth))

    return results


# Starting points for discovery. "gws" covers all services listed under
# SERVICES:, but utility commands like "auth" are not listed there and
# need their own entry point.
ROOTS: list[list[str]] = [
    ["gws"],
    ["gws", "auth"],
]


def main() -> None:
    all_cmds: list[list[str]] = []
    for root in ROOTS:
        all_cmds.extend(discover(root))

    if not all_cmds:
        print("No gws commands found. Is gws installed?", file=sys.stderr)
        sys.exit(1)

    print("All gws --help commands:")
    print()
    for cmd in all_cmds:
        print(f"  {' '.join(cmd)} --help")

    print()
    print("settings.json permission entries:")
    print()
    for cmd in all_cmds:
        entry = " ".join(cmd) + " --help"
        print(f'      "Bash({entry})",')


if __name__ == "__main__":
    main()
