# Generated By: Claude Code (Claude Opus 4.6)
"""Extract gws Bash commands from Claude session JSONL files for specific dates.

Reads prompt-log date directories to get session IDs, then scans the
corresponding Claude project session files for Bash tool_use blocks
containing gws commands. Classifies each as read-only or write and
checks against the existing allowlist in settings.json.
"""

import json
import os
import re


def get_session_ids(dates):
    """Get session IDs from prompt-log directories for given dates."""
    ids = set()
    for d in dates:
        path = os.path.expanduser(f"~/.claude/my-claude-stuff-data/prompt-log/{d}/")
        if os.path.isdir(path):
            for f in os.listdir(path):
                if f.endswith(".jsonl"):
                    ids.add(f.replace(".jsonl", ""))
    return ids


def find_session_files(session_ids):
    """Find Claude project JSONL files matching session IDs."""
    base = os.path.expanduser("~/.claude/projects")
    files = []
    for root, _, filenames in os.walk(base):
        for f in filenames:
            if not f.endswith(".jsonl"):
                continue
            sid = f.replace(".jsonl", "")
            parts = root.split("/")
            if sid in session_ids or any(p in session_ids for p in parts):
                files.append(os.path.join(root, f))
    return files


def extract_gws_base_cmd(full_cmd):
    """Extract the base gws command (before pipes/redirects) from a shell command."""
    results = []
    for part in full_cmd.split("&&"):
        part = part.strip()
        if part.startswith("cd "):
            continue
        if "gws " not in part:
            continue
        base = re.split(r"\s*[|><]", part)[0].strip()
        if base.startswith("gws "):
            results.append(base)
    return results


def extract_commands(session_files):
    """Extract unique gws base commands from session JSONL files."""
    commands = set()
    for fpath in session_files:
        try:
            with open(fpath) as fh:
                for line in fh:
                    if "gws " not in line:
                        continue
                    try:
                        entry = json.loads(line.strip())
                    except json.JSONDecodeError:
                        continue
                    msg = entry.get("message", {})
                    if not isinstance(msg, dict):
                        continue
                    content = msg.get("content", [])
                    if not isinstance(content, list):
                        continue
                    for block in content:
                        if not isinstance(block, dict):
                            continue
                        if (
                            block.get("type") == "tool_use"
                            and block.get("name") == "Bash"
                        ):
                            cmd = block.get("input", {}).get("command", "")
                            for base in extract_gws_base_cmd(cmd):
                                commands.add(base)
        except (OSError, PermissionError):
            continue
    return commands


def load_gws_patterns(settings_path):
    """Load gws-related Bash allowlist patterns from settings.json."""
    with open(settings_path) as f:
        settings = json.load(f)
    return [a for a in settings.get("permissions", {}).get("allow", []) if "gws" in a]


def matches_allowlist(cmd, patterns):
    """Check if a command matches any allowlist pattern. Returns the pattern or None."""
    for p in patterns:
        m = re.match(r"Bash\((.+)\)", p)
        if not m:
            continue
        pat = m.group(1)
        regex = re.escape(pat).replace(r"\*", ".*")
        if re.fullmatch(regex, cmd):
            return p
    return None


def classify_command(cmd):
    """Return True if the command is a write/sensitive operation."""
    # --help is always safe
    if cmd.rstrip().endswith("--help"):
        return False

    # auth subcommands that modify state or expose credentials
    if re.search(r"auth\s+(login|logout|refresh|setup|export|token)", cmd):
        return True

    # Explicit write verbs
    write_verbs = [
        "insert",
        "create",
        "delete",
        "update",
        "patch",
        "batchUpdate",
        "clear",
        "move",
        "copy",
    ]
    # Safe file-retrieval verbs (not API writes)
    safe_verbs = ["export", "download", "+download", "+export"]

    cmd_parts = cmd.split()
    for v in safe_verbs:
        if v in cmd_parts:
            return False
    for v in write_verbs:
        if v in cmd_parts:
            return True

    return False


def main():
    dates = ["2026-03-28", "2026-03-29"]
    settings_path = os.path.expanduser("~/source/my-claude-stuff/claude/settings.json")

    session_ids = get_session_ids(dates)
    session_files = find_session_files(session_ids)
    commands = extract_commands(session_files)
    patterns = load_gws_patterns(settings_path)

    already_allowed = []
    missing_readonly = []
    missing_write = []

    for cmd in sorted(commands):
        match = matches_allowlist(cmd, patterns)
        is_write = classify_command(cmd)

        if match:
            already_allowed.append((cmd, match))
        elif is_write:
            missing_write.append(cmd)
        else:
            missing_readonly.append(cmd)

    print("=" * 70)
    print("ALREADY COVERED BY ALLOWLIST")
    print("=" * 70)
    for cmd, pat in already_allowed:
        print(f"  {cmd}")
        print(f"    -> {pat}")
    print(f"\nTotal: {len(already_allowed)}")

    print()
    print("=" * 70)
    print("READ-ONLY — SAFE TO ADD TO ALLOWLIST")
    print("=" * 70)
    for cmd in missing_readonly:
        print(f"  {cmd}")
    print(f"\nTotal: {len(missing_readonly)}")

    print()
    print("=" * 70)
    print("WRITE/SENSITIVE — DO NOT AUTO-ALLOW")
    print("=" * 70)
    for cmd in missing_write:
        print(f"  {cmd}")
    print(f"\nTotal: {len(missing_write)}")


if __name__ == "__main__":
    main()
